### ISSUE TITLE
psycopg2.IntegrityError/sqlalchemy.exc.IntegrityError not handled on Update

### ISSUE THREAD

**Issue by hodigy** [dpgaspar/Flask-AppBuilder#1004]
### Environment

Flask-Appbuilder version: 1.12.0

pip freeze output:
Flask==1.0.2
Flask-AppBuilder==1.12.0
Flask-Babel==0.12.2
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
psycopg2==2.7.7
SQLAlchemy==1.2.16
WTForms==2.2.1
...

### Describe the expected results

The unique key on the DB causes and Integrity (psycopg2.IntegrityError, sqlalchemy.exc.IntegrityError) exception, it should be handled and shown to the user. At the moment that is not handled so the app shows and error:

```
[2019-05-15 11:27:46,625] ERROR in app: Exception on /admin/edit/1 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1230, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "key"
DETAIL:  Key (a,b)=(1, 2) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_appbuilder/views.py", line 524, in edit
    widgets = self._edit(pk)
  File "/usr/local/lib/python3.6/dist-packages/flask_appbuilder/baseviews.py", line 965, in _edit
    form.populate_obj(item)
  File "/usr/local/lib/python3.6/dist-packages/wtforms/form.py", line 96, in populate_obj
    field.populate_obj(obj, name)
  File "/usr/local/lib/python3.6/dist-packages/wtforms/fields/core.py", line 330, in populate_obj
    setattr(obj, name, self.data)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/attributes.py", line 263, in __set__
    instance_state(instance), instance_dict(instance), value, None
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/attributes.py", line 1226, in set
    old = self.get(state, dict_, passive=PASSIVE_ONLY_PERSISTENT)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/attributes.py", line 676, in get
    value = self.callable_(state, passive)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/strategies.py", line 708, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/strategies.py", line 850, in _emit_lazyload
    .with_post_criteria(set_default_params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/ext/baked.py", line 477, in all
    return list(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/ext/baked.py", line 375, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1569, in _autoflush
    util.raise_from_cause(e)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1558, in _autoflush
    self.flush()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2424, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2562, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2522, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 416, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 583, in execute
    uow,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 976, in _emit_update_statements
    statement, multiparams
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 974, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1093, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1234, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1452, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1230, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) duplicate key value violates unique constraint "key"
DETAIL:  Key (a,b)=(1, 2) already exists.
 [SQL: 'UPDATE ...

```

### Describe the actual results

The a composite unique constraint on the DB causes and Integrity exception  (psycopg2.IntegrityError, sqlalchemy.exc.IntegrityError) that is not handled so the app shows error. How to handle the exception and show it to the user?

### Steps to reproduce

Have a composite unique constraint on the DB and try to update a value to non unique.

**Comment by dpgaspar** [comment]
One way is:
- override ``pre_add`` and verify what you want, then raise an exception with the message you want the user to see
Other way could be:
- Write a custom WTForm validator

Hope this helps

**Comment by hodigy** [comment]
I choose to write a custom validator, but for other cases I'll need to override `pre_add` too. 
It would help to have more documentation and an example of `pre_add` override.
