### ISSUE TITLE
Error going online on Windows Server

### ISSUE THREAD

**Issue by Ulixestoitaca** [dpgaspar/Flask-AppBuilder#1005]
Hello,

trying to install latest version on Windows Server (Python 3 installed and website configured).
WSGI_HANDLER is configured like that

```
<configuration>
    <appSettings>
        <add key="WSGI_HANDLER" value="run.py" />
```

**It correctly works on localhost** but going online it cannot find the module flask_appbuilder and gives this error

Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\wfastcgi.py", line 616, in get_wsgi_handler
    raise ValueError('"%s" could not be imported%s' % (handler_name, last_tb))
ValueError: "run.py" could not be imported: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
  File "C:\inetpub\wwwroot\telegramtest.tk\venv\linkedhelper\run.py", line 1, in <module>
    from app import app
  File "C:\inetpub\wwwroot\telegramtest.tk\venv\linkedhelper\app\__init__.py", line 4, in <module>
    from flask_appbuilder import AppBuilder, SQLA
ModuleNotFoundError: No module named 'flask_appbuilder'

StdOut: 

StdErr:

**Comment by dpgaspar** [comment]
You should not run Flask dev server on production `run.py`
This is a deploy problem not a flask-appbuilder problem.

**Comment by Ulixestoitaca** [comment]
Hello,

I am running run.py just as
`from app import app`
no using dev server. 

But it cannot find flask appbuilder module

**Comment by dpgaspar** [comment]
run.py is a development server
