### ISSUE TITLE
Heroku Deployment SQL Error. 

### ISSUE THREAD

**Issue by jnorton2** [dpgaspar/Flask-AppBuilder#1038]
After deploying to heroku, occasionally I get a SQL Timeout error after the server isn't used for a while. Restarting the dyno fixes it. 
It looks like it is coming from the user part of the application. Are there any configurations to fix this? 

The logs are below. 

```
2019-06-18T19:42:30.906428+00:00 app[web.1]: [2019-06-18 19:42:30 +0000] [10] [ERROR] Error handling request /
2019-06-18T19:42:30.906449+00:00 app[web.1]: Traceback (most recent call last):
2019-06-18T19:42:30.906457+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pymysql/connections.py", line 713, in _write_bytes
2019-06-18T19:42:30.906461+00:00 app[web.1]:     self._sock.sendall(data)
2019-06-18T19:42:30.906463+00:00 app[web.1]: TimeoutError: [Errno 110] Connection timed out
2019-06-18T19:42:30.906466+00:00 app[web.1]: 
2019-06-18T19:42:30.906468+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2019-06-18T19:42:30.906470+00:00 app[web.1]: 
2019-06-18T19:42:30.906472+00:00 app[web.1]: Traceback (most recent call last):
2019-06-18T19:42:30.906476+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
2019-06-18T19:42:30.906478+00:00 app[web.1]:     cursor, statement, parameters, context
2019-06-18T19:42:30.906480+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
2019-06-18T19:42:30.906482+00:00 app[web.1]:     cursor.execute(statement, parameters)
2019-06-18T19:42:30.906484+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
2019-06-18T19:42:30.906486+00:00 app[web.1]:     result = self._query(query)
2019-06-18T19:42:30.906488+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
2019-06-18T19:42:30.906490+00:00 app[web.1]:     conn.query(q)
2019-06-18T19:42:30.906492+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
2019-06-18T19:42:30.906495+00:00 app[web.1]:     self._execute_command(COMMAND.COM_QUERY, sql)
2019-06-18T19:42:30.906497+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pymysql/connections.py", line 771, in _execute_command
2019-06-18T19:42:30.906499+00:00 app[web.1]:     self._write_bytes(packet)
2019-06-18T19:42:30.906501+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pymysql/connections.py", line 718, in _write_bytes
2019-06-18T19:42:30.906503+00:00 app[web.1]:     "MySQL server has gone away (%r)" % (e,))
2019-06-18T19:42:30.906504+00:00 app[web.1]: pymysql.err.OperationalError: (2006, "MySQL server has gone away (TimeoutError(110, 'Connection timed out'))")
2019-06-18T19:42:30.906506+00:00 app[web.1]: 
2019-06-18T19:42:30.906508+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2019-06-18T19:42:30.906510+00:00 app[web.1]: 
2019-06-18T19:42:30.906512+00:00 app[web.1]: Traceback (most recent call last):
2019-06-18T19:42:30.906514+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
2019-06-18T19:42:30.906516+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2019-06-18T19:42:30.906518+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
2019-06-18T19:42:30.906520+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2019-06-18T19:42:30.906523+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
2019-06-18T19:42:30.906525+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2019-06-18T19:42:30.906527+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
2019-06-18T19:42:30.906529+00:00 app[web.1]:     response = self.handle_exception(e)
2019-06-18T19:42:30.906531+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
2019-06-18T19:42:30.906533+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2019-06-18T19:42:30.906536+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
2019-06-18T19:42:30.906538+00:00 app[web.1]:     raise value
2019-06-18T19:42:30.906540+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
2019-06-18T19:42:30.906542+00:00 app[web.1]:     response = self.full_dispatch_request()
2019-06-18T19:42:30.906544+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
2019-06-18T19:42:30.906546+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2019-06-18T19:42:30.906547+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
2019-06-18T19:42:30.906549+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2019-06-18T19:42:30.906551+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
2019-06-18T19:42:30.906553+00:00 app[web.1]:     raise value
2019-06-18T19:42:30.906555+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
2019-06-18T19:42:30.906557+00:00 app[web.1]:     rv = self.dispatch_request()
2019-06-18T19:42:30.906559+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
2019-06-18T19:42:30.906561+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2019-06-18T19:42:30.906563+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_appbuilder/views.py", line 39, in index
2019-06-18T19:42:30.906565+00:00 app[web.1]:     return self.render_template(self.index_template, appbuilder=self.appbuilder)
2019-06-18T19:42:30.906567+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_appbuilder/baseviews.py", line 183, in render_template
2019-06-18T19:42:30.906569+00:00 app[web.1]:     template, **dict(list(kwargs.items()) + list(self.extra_args.items()))
2019-06-18T19:42:30.906571+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/templating.py", line 133, in render_template
2019-06-18T19:42:30.906573+00:00 app[web.1]:     ctx.app.update_template_context(context)
2019-06-18T19:42:30.906575+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 792, in update_template_context
2019-06-18T19:42:30.906577+00:00 app[web.1]:     context.update(func())
2019-06-18T19:42:30.906579+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_login/utils.py", line 368, in _user_context_processor
2019-06-18T19:42:30.906588+00:00 app[web.1]:     return dict(current_user=_get_user())
2019-06-18T19:42:30.906590+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_login/utils.py", line 335, in _get_user
2019-06-18T19:42:30.906592+00:00 app[web.1]:     current_app.login_manager._load_user()
2019-06-18T19:42:30.906594+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_login/login_manager.py", line 359, in _load_user
2019-06-18T19:42:30.906596+00:00 app[web.1]:     return self.reload_user()
2019-06-18T19:42:30.906598+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_login/login_manager.py", line 321, in reload_user
2019-06-18T19:42:30.906600+00:00 app[web.1]:     user = self.user_callback(user_id)
2019-06-18T19:42:30.906602+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_appbuilder/security/manager.py", line 1366, in load_user
2019-06-18T19:42:30.906605+00:00 app[web.1]:     return self.get_user_by_id(int(pk))
2019-06-18T19:42:30.906606+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask_appbuilder/security/sqla/manager.py", line 207, in get_user_by_id
2019-06-18T19:42:30.906608+00:00 app[web.1]:     return self.get_session.query(self.user_model).get(pk)
2019-06-18T19:42:30.906610+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 959, in get
2019-06-18T19:42:30.906612+00:00 app[web.1]:     return self._get_impl(ident, loading.load_on_pk_identity)
2019-06-18T19:42:30.906614+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 1069, in _get_impl
2019-06-18T19:42:30.906616+00:00 app[web.1]:     return db_load_fn(self, primary_key_identity)
2019-06-18T19:42:30.906618+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 282, in load_on_pk_identity
2019-06-18T19:42:30.906620+00:00 app[web.1]:     return q.one()
2019-06-18T19:42:30.906622+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3275, in one
2019-06-18T19:42:30.906624+00:00 app[web.1]:     ret = self.one_or_none()
2019-06-18T19:42:30.906626+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3244, in one_or_none
2019-06-18T19:42:30.906628+00:00 app[web.1]:     ret = list(self)
2019-06-18T19:42:30.906630+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
2019-06-18T19:42:30.906632+00:00 app[web.1]:     return self._execute_and_instances(context)
2019-06-18T19:42:30.906634+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
2019-06-18T19:42:30.906637+00:00 app[web.1]:     result = conn.execute(querycontext.statement, self._params)
2019-06-18T19:42:30.906639+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
2019-06-18T19:42:30.906641+00:00 app[web.1]:     return meth(self, multiparams, params)
2019-06-18T19:42:30.906642+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
2019-06-18T19:42:30.906645+00:00 app[web.1]:     return connection._execute_clauseelement(self, multiparams, params)
2019-06-18T19:42:30.906647+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
2019-06-18T19:42:30.906649+00:00 app[web.1]:     distilled_params,
2019-06-18T19:42:30.906650+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
2019-06-18T19:42:30.906652+00:00 app[web.1]:     e, statement, parameters, cursor, context
2019-06-18T19:42:30.906654+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
2019-06-18T19:42:30.906656+00:00 app[web.1]:     util.raise_from_cause(sqlalchemy_exception, exc_info)
2019-06-18T19:42:30.906658+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
2019-06-18T19:42:30.906660+00:00 app[web.1]:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
2019-06-18T19:42:30.906662+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
2019-06-18T19:42:30.906664+00:00 app[web.1]:     raise value.with_traceback(tb)
2019-06-18T19:42:30.906666+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
2019-06-18T19:42:30.906668+00:00 app[web.1]:     cursor, statement, parameters, context
2019-06-18T19:42:30.906670+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
2019-06-18T19:42:30.906672+00:00 app[web.1]:     cursor.execute(statement, parameters)
2019-06-18T19:42:30.906674+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
2019-06-18T19:42:30.906676+00:00 app[web.1]:     result = self._query(query)
2019-06-18T19:42:30.906678+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
2019-06-18T19:42:30.906680+00:00 app[web.1]:     conn.query(q)
2019-06-18T19:42:30.906682+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
2019-06-18T19:42:30.906684+00:00 app[web.1]:     self._execute_command(COMMAND.COM_QUERY, sql)
2019-06-18T19:42:30.906686+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pymysql/connections.py", line 771, in _execute_command
2019-06-18T19:42:30.906688+00:00 app[web.1]:     self._write_bytes(packet)
2019-06-18T19:42:30.906690+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pymysql/connections.py", line 718, in _write_bytes
2019-06-18T19:42:30.906692+00:00 app[web.1]:     "MySQL server has gone away (%r)" % (e,))
2019-06-18T19:42:30.906701+00:00 app[web.1]: sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (TimeoutError(110, 'Connection timed out'))")
2019-06-18T19:42:30.906704+00:00 app[web.1]: [SQL: SELECT ab_user.id AS ab_user_id, ab_user.first_name AS ab_user_first_name, ab_user.last_name AS ab_user_last_name, ab_user.username AS ab_user_username, ab_user.password AS ab_user_password, ab_user.active AS ab_user_active, ab_user.email AS ab_user_email, ab_user.last_login AS ab_user_last_login, ab_user.login_count AS ab_user_login_count, ab_user.fail_login_count AS ab_user_fail_login_count, ab_user.created_on AS ab_user_created_on, ab_user.changed_on AS ab_user_changed_on, ab_user.created_by_fk AS ab_user_created_by_fk, ab_user.changed_by_fk AS ab_user_changed_by_fk 
2019-06-18T19:42:30.906706+00:00 app[web.1]: FROM ab_user 
2019-06-18T19:42:30.906708+00:00 app[web.1]: WHERE ab_user.id = %(param_1)s]
2019-06-18T19:42:30.906710+00:00 app[web.1]: [parameters: {'param_1': 2}]
2019-06-18T19:42:30.906713+00:00 app[web.1]: (Background on this error at: http://sqlalche.me/e/e3q8)
2019-06-18T19:42:30.906906+00:00 app[web.1]: 10.63.100.123 - - [18/Jun/2019:19:42:30 +0000] "GET / HTTP/1.1" 500 0 "-" "-"
2019-06-18T19:42:30.907930+00:00 heroku[router]: at=info method=GET path="/" host=obd-powertools.herokuapp.com request_id=078268cf-f8ea-4e44-8239-e415759a0cff fwd="69.253.18.239" dyno=web.1 connect=1ms service=20ms status=500 bytes=244 protocol=https 
```

**Comment by dpgaspar** [comment]
Hi @jnorton2,

Check flask-sqlalchemy `SQLALCHEMY_POOL_PRE_PING` config option.

I'm closing this, if it does not solve your problem, feel free to reopen
