### ISSUE TITLE
App creation --> syntax error

### ISSUE THREAD

**Issue by Ulixestoitaca** [dpgaspar/Flask-AppBuilder#1052]
Ubuntu 14.04
Installed latest flask-appbuilder (got trougth pip)
installed virtaul environment
at the moment of creating the first app I get this issue

(venv) root@TrustingLightgray-VM:/var/www/socializit.tk# flask fab create-app
Traceback (most recent call last):
  File "/var/www/socializit.tk/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/var/www/socializit.tk/venv/lib/python3.4/site-packages/flask/cli.py", line 906, in main
    cli.main(args=args, prog_name=name)
  File "/var/www/socializit.tk/venv/lib/python3.4/site-packages/flask/cli.py", line 569, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/var/www/socializit.tk/venv/lib/python3.4/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/var/www/socializit.tk/venv/lib/python3.4/site-packages/click/core.py", line 1132, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/var/www/socializit.tk/venv/lib/python3.4/site-packages/click/core.py", line 1171, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/var/www/socializit.tk/venv/lib/python3.4/site-packages/flask/cli.py", line 511, in get_command
    self._load_plugin_commands()
  File "/var/www/socializit.tk/venv/lib/python3.4/site-packages/flask/cli.py", line 507, in _load_plugin_commands
    self.add_command(ep.load(), ep.name)
  File "/var/www/socializit.tk/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/var/www/socializit.tk/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/var/www/socializit.tk/venv/lib/python3.4/site-packages/flask_appbuilder/__init__.py", line 5, in <module>
    from .api import ModelRestApi  # noqa: F401
  File "/var/www/socializit.tk/venv/lib/python3.4/site-packages/flask_appbuilder/api/__init__.py", line 440
    f"Registering route {self.blueprint.url_prefix}{url} {methods}"
                                                                  ^
SyntaxError: invalid syntax

**Comment by dpgaspar** [comment]
Only python 3.6 and 3.7 are supported
