### ISSUE TITLE
apispec.exceptions.InvalidParameterError: Missing keys ['name', 'in'] for parameter

### ISSUE THREAD

**Issue by heckad** [dpgaspar/Flask-AppBuilder#1055]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version: 2.1.6

pip freeze output:
apispec==2.0.2
attrs==19.1.0
Babel==2.7.0
Click==7.0
colorama==0.4.1
defusedxml==0.6.0
Flask==1.1.1
Flask-AppBuilder==2.1.6
Flask-Babel==0.12.2
Flask-JWT-Extended==3.20.0
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.0
Flask-WTF==0.14.2
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==3.0.1
MarkupSafe==1.1.1
marshmallow==2.19.5
marshmallow-enum==1.4.1
marshmallow-sqlalchemy==0.17.0
prison==0.1.2
psycopg2-binary==2.8.3
PyJWT==1.7.1
pyrsistent==0.15.3
python-dateutil==2.8.0
python3-openid==3.1.0
pytz==2019.1
PyYAML==5.1.1
six==1.12.0
SQLAlchemy==1.3.5
SQLAlchemy-Utils==0.34.0
Werkzeug==0.15.4
WTForms==2.2.1

### Describe the expected results

When going to `/api/v1/_openapi` opened API spec.

### Describe the actual results

Error: `apispec.exceptions.InvalidParameterError: Missing keys ['name', 'in'] for parameter`

```pytb
Traceback (most recent call last):
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\flask_appbuilder\api\__init__.py", line 79, in wraps
    return f(self, *args, **kwargs)
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\flask_appbuilder\api\manager.py", line 44, in get
    base_api.add_api_spec(api_spec)
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\flask_appbuilder\api\__init__.py", line 413, in add_api_spec
    api_spec.path(path=path, operations=operations)
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\apispec\core.py", line 363, in path
    clean_operations(operations, self.openapi_version.major)
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\apispec\core.py", line 102, in clean_operations
    operation["parameters"], openapi_major_version
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\apispec\core.py", line 57, in clean_parameters
    "Missing keys {} for parameter".format(missing_attrs)
apispec.exceptions.InvalidParameterError: Missing keys ['name', 'in'] for parameter
```

### Steps to reproduce
Create app from example `crud_rest_api` and go to '/swaggerview/v1'

**Comment by dpgaspar** [comment]
Thank you for reporting this.

Seems like that apispec 2.0.0 broke FAB 2.1.6, downgrade to apispec to 1.3.3.

I'll put a cap on apispec or change FAB to accept both versions if possible

**Comment by dpgaspar** [comment]
For reference:
This is related with this: https://apispec.readthedocs.io/en/stable/upgrading.html#components-must-be-referenced-by-id-not-full-path

**Comment by dpgaspar** [comment]
Released FAB 2.1.7 that caps apispec version. Still I need to refactor the OpenAPI spec output for v2

**Comment by aahumada-git** [comment]
I found this problem in the base_api example in the method "greeting4", I replaced the old reference:
```
        ---
        get:
          parameters:
          - $ref: '#/components/parameters/greeting_schema'
```
by its id and works fine:
```
        ---
        get:
          parameters:
          - greeting_schema
```

**Comment by memjr** [comment]
> I found this problem in the base_api example in the method "greeting4", I replaced the old reference:
> 
> ```
>         ---
>         get:
>           parameters:
>           - $ref: '#/components/parameters/greeting_schema'
> ```
> 
> by its id and works fine:
> 
> ```
>         ---
>         get:
>           parameters:
>           - greeting_schema
> ```

However, it breaks the swagger screen when you try to use the api from there.
![error](https://user-images.githubusercontent.com/7396886/95513150-d85adb00-0987-11eb-9dd1-b7839c51ee84.png)

**Comment by kxbin** [comment]
@dpgaspar I had the same problem in fab 4.3.0 and the apispec it used was 5.2.2

The results of pip list are as follows：
```
Package                Version
---------------------- --------
apispec                5.2.2
attrs                  22.2.0
Babel                  2.12.1
click                  8.1.3
colorama               0.4.6
Deprecated             1.2.13
dnspython              2.3.0
email-validator        1.3.1
Flask                  2.2.3
Flask-AppBuilder       4.3.0
Flask-Babel            2.0.0
Flask-JWT-Extended     4.4.4
Flask-Limiter          3.3.0
Flask-Login            0.6.2
Flask-SQLAlchemy       2.5.1
Flask-WTF              1.1.1
greenlet               2.0.2
idna                   3.4
importlib-metadata     6.0.0
importlib-resources    5.12.0
itsdangerous           2.1.2
Jinja2                 3.1.2
jsonschema             4.17.3
limits                 3.2.0
markdown-it-py         2.2.0
MarkupSafe             2.1.2
marshmallow            3.19.0
marshmallow-enum       1.5.1
marshmallow-sqlalchemy 0.26.1
mdurl                  0.1.2
ordered-set            4.1.0
packaging              23.0
pip                    20.1.1
pkgutil-resolve-name   1.3.10
prison                 0.2.1
Pygments               2.14.0
PyJWT                  2.6.0
pyrsistent             0.19.3
python-dateutil        2.8.2
pytz                   2022.7.1
PyYAML                 6.0
rich                   13.3.2
setuptools             47.1.0
six                    1.16.0
SQLAlchemy             1.4.46
SQLAlchemy-Utils       0.40.0
typing-extensions      4.5.0
Werkzeug               2.2.3
wrapt                  1.15.0
WTForms                3.0.1
zipp                   3.15.0
```
