### ISSUE TITLE
How to use `synonym` in sqlalchemy models?

### ISSUE THREAD

**Issue by heckad** [dpgaspar/Flask-AppBuilder#1056]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version: 2.1.6

pip freeze output:
apispec==1.3.3
atomicwrites==1.3.0
attrs==19.1.0
Babel==2.7.0
Click==7.0
colorama==0.4.1
coverage==4.5.3
defusedxml==0.6.0
entrypoints==0.3
flake8==3.7.8
Flask==1.1.1
Flask-AppBuilder==2.1.6
Flask-Babel==0.12.2
Flask-JWT-Extended==3.20.0
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.0
Flask-WTF==0.14.2
glob2==0.7
importlib-metadata==0.18
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==3.0.1
Mako==1.0.13
MarkupSafe==1.1.1
marshmallow==2.19.5
marshmallow-enum==1.4.1
marshmallow-sqlalchemy==0.17.0
mccabe==0.6.1
mock==3.0.5
more-itertools==7.1.0
packaging==19.0
parse==1.12.0
parse-type==0.4.2
pluggy==0.12.0
prison==0.1.2
psycopg2-binary==2.8.3
py==1.8.0
pycodestyle==2.5.0
pyflakes==2.1.1
PyJWT==1.7.1
pyparsing==2.4.0
pyrsistent==0.15.3
pytest==5.0.1
pytest-bdd==3.1.1
pytest-cov==2.7.1
pytest-dependency==0.4.0
python-dateutil==2.8.0
python3-openid==3.1.0
pytz==2019.1
PyYAML==5.1.1
six==1.12.0
SQLAlchemy==1.3.5
SQLAlchemy-Utils==0.34.0
wcwidth==0.1.7
Werkzeug==0.15.4
WTForms==2.2.1
zipp==0.5.2

### Describe the expected results

All works

### Describe the actual results

Exception: AttributeError: columns

```pytb
Traceback (most recent call last):
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\flask\cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\flask\cli.py", line 119, in call_factory
    return app_factory()
  File "C:\Users\Asus\Documents\Projects\work\instamenu\instamenu\__init__.py", line 78, in create_app
    from . import views
  File "C:\Users\Asus\Documents\Projects\work\instamenu\instamenu\views.py", line 46, in <module>
    from . import views_for_models, crud_api_for_models
  File "C:\Users\Asus\Documents\Projects\work\instamenu\instamenu\crud_api_for_models.py", line 25, in <module>
    appbuilder.add_api(api_builder(model))
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\flask_appbuilder\base.py", line 532, in add_api
    return self.add_view_no_menu(baseview)
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\flask_appbuilder\base.py", line 518, in add_view_no_menu
    baseview, endpoint=endpoint, static_folder=static_folder
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\flask_appbuilder\base.py", line 623, in register_blueprint
    self, endpoint=endpoint, static_folder=static_folder
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\flask_appbuilder\api\__init__.py", line 899, in create_blueprint
    self._init_model_schemas()
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\flask_appbuilder\api\__init__.py", line 925, in _init_model_schemas
    self.list_columns
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\flask_appbuilder\api\convert.py", line 223, in convert
    enum_dump_by_name
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\flask_appbuilder\api\convert.py", line 130, in _column2field
    nested=False
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\flask_appbuilder\api\convert.py", line 228, in convert
    return self._meta_schema_factory(_columns, _model, SchemaMixin)()
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\flask_appbuilder\api\convert.py", line 105, in _meta_schema_factory
    class MetaSchema(ModelSchema, class_mixin):
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\marshmallow\schema.py", line 118, in __new__
    dict_cls=dict_cls
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\marshmallow_sqlalchemy\schema.py", line 64, in get_declared_fields
    fields = mcs.get_fields(converter, opts, declared_fields, dict_cls)
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\marshmallow_sqlalchemy\schema.py", line 98, in get_fields
    dict_cls=dict_cls,
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\marshmallow_sqlalchemy\convert.py", line 100, in fields_for_model
    field = base_fields.get(prop.key) or self.property2field(prop)
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\marshmallow_sqlalchemy\convert.py", line 129, in property2field
    field_class = field_class or self._get_field_class_for_property(prop)
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\marshmallow_sqlalchemy\convert.py", line 190, in _get_field_class_for_property
    column = prop.columns[0]
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 949, in __getattr__
    return self._fallback_getattr(key)
  File "C:\Users\Asus\Documents\Projects\work\instamenu\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 923, in _fallback_getattr
    raise AttributeError(key)
AttributeError: columns
```

### Steps to reproduce
Need to create a model with synonym field(`name = synonym("name_en")`) and ItemRestApi for this model.

**Comment by dpgaspar** [comment]
Use a `@property` instead
