### ISSUE TITLE
commit() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by shizidushu** [dpgaspar/Flask-AppBuilder#1063]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version: 2.1.6

pip freeze output:

```
alembic==1.0.11
apispec==2.0.2
attrs==19.1.0
Babel==2.7.0
Click==7.0
colorama==0.4.1
defusedxml==0.6.0
Flask==1.1.1
Flask-AppBuilder==2.1.6
Flask-Babel==0.12.2
Flask-JWT-Extended==3.20.0
Flask-Login==0.4.1
Flask-Migrate==2.5.2
Flask-OpenID==1.2.5
flask-sqlacodegen==1.1.6.1
Flask-SQLAlchemy==2.4.0
Flask-WTF==0.14.2
inflect==2.1.0
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==3.0.1
Mako==1.0.13
MarkupSafe==1.1.1
marshmallow==2.19.5
marshmallow-enum==1.4.1
marshmallow-sqlalchemy==0.17.0
Pillow==6.1.0
pkg-resources==0.0.0
prison==0.1.2
psycopg2==2.8.3
PyJWT==1.7.1
pyodbc==4.0.26
pyrsistent==0.15.3
python-dateutil==2.8.0
python-editor==1.0.4
python3-openid==3.1.0
pytz==2019.1
PyYAML==5.1.1
six==1.12.0
sqlacodegen==2.0.1
SQLAlchemy==1.3.5
SQLAlchemy-Utils==0.34.1
Werkzeug==0.15.5
WTForms==2.2.1
```

### Describe the expected results

no error

```python
# models.py
from . import db
class AppUserUser(Model):
    ID = Column(Integer, primary_key=True)
    UserId = Column(Integer, nullable=False)
    LoginUser = Column(Unicode(50), nullable=False, unique=True)
    UserName = Column(Unicode(50))


class TUser(Model):
    UserId = Column(Integer, primary_key=True)
    LoginUser = Column(Unicode(50), nullable=False)
    UserName = Column(Unicode(50), nullable=False)

    def give_right(self):
        try:
            user_to_be_add = AppUserUser(UserId = self.UserId, LoginUser=self.LoginUser, UserName=self.UserName)
            db.session.add(user_to_be_add)
            db.session.commit(user_to_be_add)
            flash(str(user_to_be_add) + 'success!')
        except Exception as e:
            print(e)
            db.session.rollback()
            flash(str(user_to_be_add) + 'failed!')

# views.py
class TUserModelView(ModelView):
    datamodel = SQLAInterface(TUser)
    @action("give_right", "give right", "really?", "fa-rocket", single=True)
    def give_right(self, users):
        for user in users:
                user.give_right()


        self.update_redirect()
        return redirect(self.get_redirect())
```

### Describe the actual results

Tell us what happens instead.

```pytb
Traceback (most recent call last):
  File "C:\Users\hanyong\Documents\Python Scripts\flask-data-app\venv\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\hanyong\Documents\Python Scripts\flask-data-app\venv\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\hanyong\Documents\Python Scripts\flask-data-app\venv\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\hanyong\Documents\Python Scripts\flask-data-app\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\hanyong\Documents\Python Scripts\flask-data-app\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\hanyong\Documents\Python Scripts\flask-data-app\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\hanyong\Documents\Python Scripts\flask-data-app\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\hanyong\Documents\Python Scripts\flask-data-app\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\hanyong\Documents\Python Scripts\flask-data-app\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\hanyong\Documents\Python Scripts\flask-data-app\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\hanyong\Documents\Python Scripts\flask-data-app\venv\lib\site-packages\flask_appbuilder\views.py", line 653, in action_post
    return action.func(items)
  File "C:\Users\hanyong\Documents\Python Scripts\flask-data-app\dataapp\app\views.py", line 62, in give_right
    user.give_right()
  File "C:\Users\hanyong\Documents\Python Scripts\flask-data-app\dataapp\app\models.py", line 132, in give_right
    db.session.commit(user_to_be_add)
  File "C:\Users\hanyong\Documents\Python Scripts\flask-data-app\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
TypeError: commit() takes 1 positional argument but 2 were given
```

**Comment by dpgaspar** [comment]
Hi @shizidushu 

One question:
- Where is the `db` object coming from? Can you post the full stacktrace also?

Can you work in a request context on your method? If yes, you can use `current_app.flask_appbuilder.get_session.commit( ... )`

**Comment by shizidushu** [comment]
`db`: `from . import db` in models.py

> Can you work in a request context on your method? If yes, you can use `current_app.flask_appbuilder.get_session.commit( ... )`

Can you give more detailed step?

**Comment by shizidushu** [comment]
`db.session.commit(user_to_be_add)` should be `db.session.commit()`. After changed, it works. I make a silly mistake.

Is `from . import db` (in models.py) the right way to refer the `db` object?
