### ISSUE TITLE
[api] excluding columns from related models not possible

### ISSUE THREAD

**Issue by CameronNemo** [dpgaspar/Flask-AppBuilder#1126]
### Environment

Flask-Appbuilder version: git master

pip freeze output:

```
alembic==1.1.0
apispec==1.3.3
attrs==19.1.0
Babel==2.7.0
certifi==2019.3.9
chardet==3.0.4
Click==7.0
colorama==0.4.1
decorator==4.4.0
defusedxml==0.6.0
Flask==1.1.1
Flask-AppBuilder==2.1.13
Flask-Babel==0.12.2
Flask-JWT-Extended==3.23.0
Flask-Login==0.4.1
Flask-Migrate==2.5.2
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.0
Flask-WTF==0.14.2
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==3.0.2
Mako==1.1.0
MarkupSafe==1.1.1
marshmallow==2.19.5
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.19.0
Pillow==6.1.0
prison==0.1.2
psycopg2-binary==2.8.3
pyasn1==0.4.7
pyasn1-modules==0.2.6
PyJWT==1.7.1
pyrsistent==0.15.4
python-dateutil==2.8.0
python-editor==1.0.4
python-ldap==3.2.0
python3-openid==3.1.0
pytz==2019.2
PyYAML==5.1.2
requests==2.22.0
six==1.12.0
SQLAlchemy==1.3.8
SQLAlchemy-Searchable==1.1.0
SQLAlchemy-Utils==0.34.2
urllib3==1.25.3
uWSGI==2.0.18
validators==0.14.0
Werkzeug==0.15.6
WTForms==2.2.1
```

### Describe the expected results

I am attempting to add a text search vector column to one of my models and exclude it from the API endpoint, because marshmallow cannot handle it. The problem is that I cannot include relationship columns for the relevant model in other unrelated models' APIs. I want to be able to use the relationship column in general as field in the API, but I cannot seem to selectively exclude a column for a related model using the `ModelRestApi` class.

```python
from sqlalchemy import Integer, Text, String
from sqlalchemy.orm import relationship, backref
from sqlalchemy_utils.types import TSVectorType
from flask_appbuilder import Model

class Bert(Model):
    id = Column(Integer, primary_key=True)
    name = Column(String)
    notes = Column(Text)
    search_vector = Column(TSVectorType('name', 'notes'))
    ernie = relationship('Ernie', backref=backref('bert', uselist=False))

class Ernie(Model):
    id = Column(Integer, primary_key=True)

class BertApi(ModelRestApi):
    datamodel = SQLAInterface(Bert)
    search_exclude_columns = ['search_vector']
    list_exclude_columns = ['search_vector']
    show_exclude_columns = ['search_vector']
    edit_exclude_columns = ['search_vector']
    add_exclude_columns = ['search_vector']

class ErnieApi(ModelRestApi):
    datamodel = SQLAInterface(Ernie)
    # here I try to exclude a specific column
    search_exclude_columns = ['bert.search_vector']
    list_exclude_columns = ['bert.search_vector']
    show_exclude_columns = ['bert.search_vector']
    edit_exclude_columns = ['bert.search_vector']
    add_exclude_columns = ['bert.search_vector']
```

### Describe the actual results

Marshmallow chokes on the nested column I try to exclude, and I see a traceback similar to the below.

```pytb
Traceback (most recent call last):
  File "./run.py", line 1, in <module>
    from app import app
  File "./app/__init__.py", line 31, in <module>
    from app import views, apis
  File "./app/apis.py", line 104, in <module>
    ab.add_api(ConnectionApi)
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/flask_appbuilder/base.py", line 530, in add_api
    return self.add_view_no_menu(baseview)
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/flask_appbuilder/base.py", line 516, in add_view_no_menu
    baseview, endpoint=endpoint, static_folder=static_folder
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/flask_appbuilder/base.py", line 621, in register_blueprint
    self, endpoint=endpoint, static_folder=static_folder
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/flask_appbuilder/api/__init__.py", line 898, in create_blueprint
    self._init_model_schemas()
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/flask_appbuilder/api/__init__.py", line 924, in _init_model_schemas
    self.list_columns
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/flask_appbuilder/api/convert.py", line 224, in convert
    enum_dump_by_name
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/flask_appbuilder/api/convert.py", line 130, in _column2field
    nested=False
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/flask_appbuilder/api/convert.py", line 230, in convert
    return self._meta_schema_factory(_columns, _model, SchemaMixin)()
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/flask_appbuilder/api/convert.py", line 105, in _meta_schema_factory
    class MetaSchema(ModelSchema, class_mixin):
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 118, in __new__
    dict_cls=dict_cls
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/marshmallow_sqlalchemy/schema.py", line 62, in get_declared_fields
    fields = mcs.get_fields(converter, opts, declared_fields, dict_cls)
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/marshmallow_sqlalchemy/schema.py", line 96, in get_fields
    dict_cls=dict_cls,
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/marshmallow_sqlalchemy/convert.py", line 97, in fields_for_model
    field = base_fields.get(prop.key) or self.property2field(prop)
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/marshmallow_sqlalchemy/convert.py", line 127, in property2field
    field_class = field_class or self._get_field_class_for_property(prop)
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/marshmallow_sqlalchemy/convert.py", line 189, in _get_field_class_for_property
    field_cls = self._get_field_class_for_column(column)
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/marshmallow_sqlalchemy/convert.py", line 155, in _get_field_class_for_column
    return self._get_field_class_for_data_type(column.type)
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/marshmallow_sqlalchemy/convert.py", line 178, in _get_field_class_for_data_type
    return self._get_field_class_for_data_type(data_type.impl)
  File "/Users/cameronnemo/docs/pgndb/venv/lib/python3.7/site-packages/marshmallow_sqlalchemy/convert.py", line 180, in _get_field_class_for_data_type
    "Could not find field column of type {}.".format(types[0])
marshmallow_sqlalchemy.exceptions.ModelConversionError: Could not find field column of type <class 'sqlalchemy.dialects.postgresql.base.TSVECTOR'>.
```

### Steps to reproduce

1. Create a model with a column that cannot be serialized.
2. Create a second model related to the first model.
3. Create REST API endpoints for the second model, and try to exclude the unserializable column.

The documentation was not clear on how to approach such a situation.

**Comment by CameronNemo** [comment]
I found an interesting workaround for this problem. I define an attribute `marshmallow_exclude_columns` on my model, and check for that in the fab conversion module:

```diff
diff --git a/flask_appbuilder/api/convert.py b/flask_appbuilder/api/convert.py
index 73597e78..f306db54 100644
--- a/flask_appbuilder/api/convert.py
+++ b/flask_appbuilder/api/convert.py
@@ -84,7 +84,7 @@ class Model2SchemaConverter(BaseModel2SchemaConverter):
         for k, v in schema._declared_fields.items():
             print(k, v)

-    def _meta_schema_factory(self, columns, model, class_mixin):
+    def _meta_schema_factory(self, columns, model, class_mixin, exclude):
         """
             Creates ModelSchema marshmallow-sqlalchemy

@@ -94,17 +94,20 @@ class Model2SchemaConverter(BaseModel2SchemaConverter):
         :return: ModelSchema
         """
         _model = model
+        _exclude = exclude
         if columns:
             class MetaSchema(ModelSchema, class_mixin):
                 class Meta:
                     model = _model
                     fields = columns
+                    exclude = _exclude
                     strict = True
                     sqla_session = self.datamodel.session
         else:
             class MetaSchema(ModelSchema, class_mixin):
                 class Meta:
                     model = _model
+                    exclude = _exclude
                     strict = True
                     sqla_session = self.datamodel.session
         return MetaSchema
@@ -214,7 +217,10 @@ class Model2SchemaConverter(BaseModel2SchemaConverter):

         _columns = list()
         tree_columns = columns2Tree(columns)
+        exclude_columns = getattr(_model, 'marshmallow_exclude_columns', ())
         for column in tree_columns.root.childs:
+            if column.data in exclude_columns:
+                continue
             # Get child model is column is dotted notation
             ma_sqla_fields_override[column.data] = self._column2field(
                 _datamodel,
@@ -225,4 +231,4 @@ class Model2SchemaConverter(BaseModel2SchemaConverter):
             _columns.append(column.data)
         for k, v in ma_sqla_fields_override.items():
             setattr(SchemaMixin, k, v)
-        return self._meta_schema_factory(_columns, _model, SchemaMixin)()
+        return self._meta_schema_factory(_columns, _model, SchemaMixin, exclude=exclude_columns)()
```

It *seems* to work alright, but I have yet to test.

**Comment by dpgaspar** [comment]
Made some comments on the PR

**Comment by CameronNemo** [comment]
Hmm I am not seeing those comments.
