### ISSUE TITLE
ListField(StringField()) in a view's "related_views" raises "AttributeError: 'StringField' object has no attribute 'document_type'"

### ISSUE THREAD

**Issue by tconstantl** [dpgaspar/Flask-AppBuilder#1144]
### Environment

Flask-Appbuilder==2.1.13
flask-mongoengine==0.9.5
mongoengine==0.18.2

##
I am trying to use ReferenceField and related views to display a list of documents belonging to a specific DocumentCollection. The Document show and list views work just fine, and the DocumentCollection list view is working as well. However, when I try to access the DocumentCollection show view, this error is raised : **AttributeError: 'StringField' object has no attribute 'document_type'**. After some testing, I figured out that the error was by the **get_related_model** function (at the very end of the stack trace below) because of the ListField(StringField()). This error wasn't raised when using ListField(ReferenceField(_AnyDocument_). 

Is this a known/wanted behavior ? And is there something wrong with my codes when defining the models ? Thank you a lot for your help

Below my code and the stacktrace of the error, please tell me if anything else is needed 

### models.py
```python
class MyDocumentCollection(Document):
    name = StringField()
    def __unicode__(self):
        return self.name
    def __repr__(self):
        return self.name
    def __str__(self):
        return self.name

class MyDocument(Document):
    name = StringField()
    random_list = ListField(StringField())
    collection = ReferenceField(DocumentCollection)
    def __unicode__(self):
        return self.name
    def __repr__(self):
        return self.name
    def __str__(self):
        return self.name
```

### views.py
```python
class MyDocumentView(ModelView):
    datamodel = MongoEngineInterface(MyDocument)

class MyDocumentCollectionView(ModelView):
    datamodel = MongoEngineInterface(MyDocumentCollection)
    related_views = [MyDocumentView]
```

### Stacktrace
```pytb
Traceback (most recent call last):
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask_appbuilder/security/decorators.py", line 123, in wraps
    return f(self, *args, **kwargs)
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask_appbuilder/views.py", line 544, in show
    widgets = self._show(pk)
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask_appbuilder/baseviews.py", line 1095, in _show
    item, orders=orders, pages=pages, page_sizes=page_sizes, widgets=widgets
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask_appbuilder/baseviews.py", line 937, in _get_related_views_widgets
    page_size=page_sizes.get(view.__class__.__name__),
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask_appbuilder/baseviews.py", line 884, in _get_related_view_widget
    fk = related_view.datamodel.get_related_fk(self.datamodel.obj)
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask_appbuilder/models/mongoengine/interface.py", line 318, in get_related_fk
    if model == self.get_related_model(col_name):
  File "/Users/thibautconstant/cnrs_env/venv/lib/python3.7/site-packages/flask_appbuilder/models/mongoengine/interface.py", line 294, in get_related_model
    return field.field.document_type
AttributeError: 'StringField' object has no attribute 'document_type'
```

**Comment by dpgaspar** [comment]
Hi,

MongoDB is partially supported, so currently `ListField` can only be used with a `ReferenceField` kind of a many to many relation on SQL.

**Comment by tconstantl** [comment]
Hi,

Thanks for the answer ! I found a quick workaround as I really needed to implement this.
