### ISSUE TITLE
Pain points while setting up a development environment for FAB itself

### ISSUE THREAD

**Issue by CameronNemo** [dpgaspar/Flask-AppBuilder#1279]
### Environment

Flask-Appbuilder version: master

pip freeze output: not relevant, using requirements-dev.txt from git master

### Describe the expected results

I expect to be able to install the development requirements and run the test suite locally.

### Describe the actual results

postgres package install error:

```
Collecting psycopg2-binary==2.7.5 (from -r requirements-dev.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/17/dc/3f6bfae668594013cb9ef0cba4f4863451220944650868ad67332ca9069c/psycopg2-binary-2.7.5.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/cameronnemo/docs/src/flask-appbuilder/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tlkmi5zl/psycopg2-binary/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tlkmi5zl/psycopg2-binary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-tlkmi5zl/psycopg2-binary/
    Complete output (23 lines):
    running egg_info
    creating pip-egg-info/psycopg2_binary.egg-info
    writing pip-egg-info/psycopg2_binary.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2_binary.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2_binary.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2_binary.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

mysql package install error:

```
Collecting mysqlclient<2.0.0,>=1.4.2 (from -r requirements-dev.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/d0/97/7326248ac8d5049968bf4ec708a5d3d4806e412a42e74160d7f266a3e03a/mysqlclient-1.4.6.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/cameronnemo/docs/src/flask-appbuilder/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nr56sri1/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nr56sri1/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-nr56sri1/mysqlclient/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nr56sri1/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-nr56sri1/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-nr56sri1/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

mssql package install error:

```
Collecting pymssql==2.1.4 (from -r requirements-dev.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/2e/81/99562b93d75f3fc5956fa65decfb35b38a4ee97cf93c1d0d3cb799fffb99/pymssql-2.1.4.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/cameronnemo/docs/src/flask-appbuilder/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5zz_p158/pymssql/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5zz_p158/pymssql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-5zz_p158/pymssql/
    Complete output (7 lines):
    /home/cameronnemo/docs/src/flask-appbuilder/venv/lib/python3.8/site-packages/setuptools/dist.py:45: DistDeprecationWarning: Do not call this function
      warnings.warn("Do not call this function", DistDeprecationWarning)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5zz_p158/pymssql/setup.py", line 88, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

(minor issue) flake8 conflicts:

```
ERROR: flake8 3.6.0 has requirement pycodestyle<2.5.0,>=2.4.0, but you'll have pycodestyle 2.5.0 which is incompatible.
```

### Steps to reproduce

Python 3.8.1, Linux glibc

Got any tips?

**Comment by dpgaspar** [comment]
You need to install OS pre reqs for those packages. For example for mysqlclient `sudo apt-get install libmysqlclient-dev` on Ubuntu

Yet a nice CONTRIBUTING.md document woud help a lot. Going to leave this open

**Comment by CameronNemo** [comment]
bump
