### ISSUE TITLE
Unable to access foreign key relationship in "user" table

### ISSUE THREAD

**Issue by jdc91** [dpgaspar/Flask-AppBuilder#1284]
### Environment

**Flask-Appbuilder version:**
2.2.1

**pip freeze output:**
apispec==1.3.3
attrs==19.3.0
Babel==2.8.0
Click==7.0
colorama==0.4.3
defusedxml==0.6.0
Flask==1.1.1
Flask-AppBuilder==2.2.1
Flask-Babel==0.12.2
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.1
Flask-WTF==0.14.2
importlib-metadata==1.4.0
itsdangerous==1.1.0
Jinja2==2.10.3
jsonschema==3.2.0
MarkupSafe==1.1.1
marshmallow==2.19.5
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.21.0
more-itertools==8.1.0
prison==0.1.2
psycopg2==2.8.4
PyJWT==1.7.1
pyrsistent==0.15.7
python-dateutil==2.8.1
python3-openid==3.1.0
pytz==2019.3
PyYAML==5.3
six==1.14.0
SQLAlchemy==1.3.12
SQLAlchemy-Utils==0.36.1
Werkzeug==0.16.0
WTForms==2.2.1
zipp==2.0.0

### Describe the expected results
I have 2 tables called shipment and user. The shipment has a foreign key to the table user. Each shipment has a user. I am trying to create a model class by linking the users name to the shipment. as shown below

```python
##models.py
class Shipments(Model):
    __bind_key__ = 'swyft-db'
    __tablename__ = 'shipment'
    id = Column(Integer, nullable=False, primary_key=True)

    user_id = Column(Integer,  ForeignKey(
        "user.id"), nullable=True)
    # TODO: Cannot get user due to conflict with the internal user db
    user = relationship("User")
```

### Describe the actual results
I get an error when I try to  use 
`user = relationship("User")`
```pytb

2020-02-15 18:49:47,871:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/show/<pk> ['GET']
2020-02-15 18:49:47,916:INFO:flask_appbuilder.base:Registering class MenuApi on menu 
2020-02-15 18:49:47,916:INFO:flask_appbuilder.api:Registering route /api/v1/menu/ ['GET']
Traceback (most recent call last):
  File "/home/dehan/.pyenv/versions/3.7.5/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/flask/cli.py", line 848, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/flask/cli.py", line 305, in __init__
    self._load_unlocked()
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/flask/cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/dehan/Play/swyft/swyft-adminapp/app/__init__.py", line 31, in <module>
    from app import views
  File "/home/dehan/Play/swyft/swyft-adminapp/app/views.py", line 19, in <module>
    class UserTierModelView(ModelView):
  File "/home/dehan/Play/swyft/swyft-adminapp/app/views.py", line 20, in UserTierModelView
    datamodel = SQLAInterface(UserTier)
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/flask_appbuilder/models/sqla/interface.py", line 61, in __init__
    for prop in sa.orm.class_mapper(obj).iterate_properties:
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/sqlalchemy/orm/base.py", line 441, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/sqlalchemy/orm/base.py", line 420, in _inspect_mapped_class
    mapper._configure_all()
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 1337, in _configure_all
    configure_mappers()
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3248, in configure_mappers
    mapper._post_configure_properties()
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 1947, in _post_configure_properties
    prop.init()
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 196, in init
    self.do_init()
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1913, in do_init
    self._process_dependent_arguments()
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1975, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1880, in entity
    argument = self.argument()
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 294, in __call__
    x = eval(self.arg, globals(), self._dict)
  File "<string>", line 1, in <module>
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 734, in __missing__
    self[key] = val = self.creator(key)
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 273, in _access_cls
    return _determine_container(key, cls._decl_class_registry[key])
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 257, in _determine_container
    value = value.attempt_get([], key)
  File "/home/dehan/.pyenv/versions/3.7.5/lib/python3.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 97, in attempt_get
    % (".".join(path + [key]))
sqlalchemy.exc.InvalidRequestError: Multiple classes found for path "User" in the registry of this declarative base. Please use a fully module-qualified path.
```

### Steps to reproduce
Create a table named user
Create another table  and create a foreign key relationship between them
Try to access the user "Relationship" from the other table inside models

I'm willing to do the fix but I might need some guidance from you :)

**Comment by dpgaspar** [comment]
The SQLAlchemy model named "User" already exist on flask-appbuilder, why not use that one?

**Comment by jdc91** [comment]
I used a different class name and it worked :)
