### ISSUE TITLE
IntegerField causes "TypeError: 'UnboundField' object is not callable"

### ISSUE THREAD

**Issue by DACRepair** [dpgaspar/Flask-AppBuilder#1306]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Python 3.7.6
Flask-Appbuilder version: 2.2.4

pip freeze output:
alembic==1.4.1
apache-airflow==1.10.9
apispec==1.3.3
argcomplete==1.11.1
attrs==19.3.0
Babel==2.8.0
cached-property==1.5.1
cattrs==0.9.0
certifi==2019.11.28
chardet==3.0.4
Click==7.0
colorama==0.4.3
colorlog==4.0.2
configparser==3.5.3
croniter==0.3.31
defusedxml==0.6.0
dill==0.3.1.1
docutils==0.16
Flask==1.1.1
Flask-Admin==1.5.4
Flask-AppBuilder==2.2.4
Flask-Babel==1.0.0
Flask-Caching==1.3.3
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.1
flask-swagger==0.2.13
Flask-WTF==0.14.3
funcsigs==1.0.2
future==0.16.0
graphviz==0.13.2
gunicorn==19.10.0
idna==2.9
importlib-metadata==1.5.0
iso8601==0.1.12
itsdangerous==1.1.0
Jinja2==2.10.3
json-merge-patch==0.2
jsonschema==3.2.0
lazy-object-proxy==1.4.3
lockfile==0.12.2
Mako==1.1.2
Markdown==2.6.11
MarkupSafe==1.1.1
marshmallow==2.19.5
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.22.3
numpy==1.18.1
pandas==0.25.3
pendulum==1.4.4
prison==0.1.2
psutil==5.7.0
Pygments==2.5.2
PyJWT==1.7.1
pyrsistent==0.15.7
python-daemon==2.1.2
python-dateutil==2.8.1
python-editor==1.0.4
python3-openid==3.1.0
pytz==2019.3
pytzdata==2019.3
PyYAML==5.3
requests==2.23.0
setproctitle==1.1.10
six==1.14.0
SQLAlchemy==1.3.13
SQLAlchemy-JSONField==0.9.0
SQLAlchemy-Utils==0.36.1
tabulate==0.8.6
tenacity==4.12.0
termcolor==1.1.0
text-unidecode==1.2
thrift==0.13.0
typing-extensions==3.7.4.1
tzlocal==1.5.1
unicodecsv==0.14.1
urllib3==1.25.8
Werkzeug==0.16.1
WTForms==2.2.1
zipp==3.0.0
zope.deprecation==4.4.0

### Describe the expected results

A field should render for an integer

```python
class RepomanForm(DynamicForm):
    ...
    refresh = IntegerField(lazy_gettext('Refresh Interval'), widget=BS3TextFieldWidget(),
                           validators=[NumberRange(min=0)])
```

### Describe the actual results

The List view works perfectly, but when trying to Add, it causes an error

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_appbuilder/security/decorators.py", line 123, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_appbuilder/views.py", line 584, in add
    widget = self._add()
  File "/usr/local/lib/python3.6/dist-packages/flask_appbuilder/baseviews.py", line 1150, in _add
    form = self.add_form.refresh()
TypeError: 'UnboundField' object is not callable
```

### Steps to reproduce
It's quite long since its technically a FAB plugin written for Apache Airflow, my repo is available at:
https://github.com/DACRepair/airflow-repoman

To do a full reproduce:
1. `pip install apache-airflow`
2. `airflow initdb`
3. Edit your airflow.cfg in the $AIRFLOW_HOME directory to have: `[webserver] rbac=True` (The default $AIRFLOW_HOME is `~/airflow`)
4. `flask fab create_user` and create an admin user to log in
5. `pip install git+https://github.com/DACRepair/airflow-repoman.git` to install my plugin or copy whole `airflow_repoman` subdirectory in the repo to the `$AIRFLOW_HOME/plugins` directory (IE you should see `$AIRFLOW_HOME/plugins/airflow_repoman/plugin.py`)
6. After logging in, go to Admin -> DAG Repos and try to add an entry.

###  Other Notes
I have tried and so far the only field that keeps breaking this is the `refresh` field. Everything else works great so far.
I have tried to

**Comment by DACRepair** [comment]
This was resolved. It was due to the column being named `refresh` and there being a classmethod called `refresh`. I changed the column name and it is now resolved.
