### ISSUE TITLE
There is noway to run flask-appbuilder with waitress

### ISSUE THREAD

**Issue by andreamancini-work** [dpgaspar/Flask-AppBuilder#1388]
I'm trying to run my app with waitress via command line "waitress-serve" but there is a possible "create_app" to apply to the call of the command.
Thanks for your time.

**Comment by dpgaspar** [comment]
don't no waitress, when you run flask-appbuilder you're running a flask app, can you run a simples test flask app with waitress?

If yes, can you share logs

**Comment by andreamancini-work** [comment]
I added a new file in project called wsgi.py containing this code:

```
from app import app

if __name__ == "__main__":
    app.run()
```

and I run waitress with this command:

waitress-serve --call 'wsgi:app'

This is the log:
2020-06-06 00:10:47,344:INFO:flask_appbuilder.base:Registering class IndexView on menu 
2020-06-06 00:10:47,344:INFO:flask_appbuilder.baseviews:Registering route / ('GET',)
2020-06-06 00:10:47,349:INFO:flask_appbuilder.base:Registering class UtilView on menu 
2020-06-06 00:10:47,349:INFO:flask_appbuilder.baseviews:Registering route /back ('GET',)
2020-06-06 00:10:47,357:INFO:flask_appbuilder.base:Registering class LocaleView on menu 
2020-06-06 00:10:47,358:INFO:flask_appbuilder.baseviews:Registering route /lang/<string:locale> ('GET',)
2020-06-06 00:10:47,368:INFO:flask_appbuilder.base:Registering class SecurityApi on menu 
2020-06-06 00:10:47,372:INFO:flask_appbuilder.api:Registering route /api/v1/security/login ['POST']
2020-06-06 00:10:47,373:INFO:flask_appbuilder.api:Registering route /api/v1/security/refresh ['POST']
2020-06-06 00:10:47,380:INFO:flask_appbuilder.base:Registering class ResetPasswordView on menu 
2020-06-06 00:10:47,381:INFO:flask_appbuilder.baseviews:Registering route /resetpassword/form ['GET']
2020-06-06 00:10:47,381:INFO:flask_appbuilder.baseviews:Registering route /resetpassword/form ['POST']
2020-06-06 00:10:47,404:INFO:flask_appbuilder.base:Registering class ResetMyPasswordView on menu 
2020-06-06 00:10:47,405:INFO:flask_appbuilder.baseviews:Registering route /resetmypassword/form ['GET']
2020-06-06 00:10:47,405:INFO:flask_appbuilder.baseviews:Registering route /resetmypassword/form ['POST']
2020-06-06 00:10:47,441:INFO:flask_appbuilder.base:Registering class UserInfoEditView on menu 
2020-06-06 00:10:47,442:INFO:flask_appbuilder.baseviews:Registering route /userinfoeditview/form ['GET']
2020-06-06 00:10:47,442:INFO:flask_appbuilder.baseviews:Registering route /userinfoeditview/form ['POST']
2020-06-06 00:10:47,449:INFO:flask_appbuilder.base:Registering class AuthDBView on menu 
2020-06-06 00:10:47,458:INFO:flask_appbuilder.baseviews:Registering route /login/ ['GET', 'POST']
2020-06-06 00:10:47,458:INFO:flask_appbuilder.baseviews:Registering route /logout/ ('GET',)
2020-06-06 00:10:47,474:INFO:flask_appbuilder.base:Registering class UserDBModelView on menu List Users
2020-06-06 00:10:47,474:INFO:flask_appbuilder.baseviews:Registering route /users/action/<string:name>/<pk> ['GET', 'POST']
2020-06-06 00:10:47,474:INFO:flask_appbuilder.baseviews:Registering route /users/action_post ['POST']
2020-06-06 00:10:47,474:INFO:flask_appbuilder.baseviews:Registering route /users/add ['GET', 'POST']
2020-06-06 00:10:47,475:INFO:flask_appbuilder.baseviews:Registering route /users/api ['GET']
2020-06-06 00:10:47,475:INFO:flask_appbuilder.baseviews:Registering route /users/api/column/add/<col_name> ['GET']
2020-06-06 00:10:47,475:INFO:flask_appbuilder.baseviews:Registering route /users/api/column/edit/<col_name> ['GET']
2020-06-06 00:10:47,475:INFO:flask_appbuilder.baseviews:Registering route /users/api/create ['POST']
2020-06-06 00:10:47,475:INFO:flask_appbuilder.baseviews:Registering route /users/api/delete/<pk> ['DELETE']
2020-06-06 00:10:47,475:INFO:flask_appbuilder.baseviews:Registering route /users/api/get/<pk> ['GET']
2020-06-06 00:10:47,475:INFO:flask_appbuilder.baseviews:Registering route /users/api/read ['GET']
2020-06-06 00:10:47,475:INFO:flask_appbuilder.baseviews:Registering route /users/api/readvalues ['GET']
2020-06-06 00:10:47,475:INFO:flask_appbuilder.baseviews:Registering route /users/api/update/<pk> ['PUT']
2020-06-06 00:10:47,498:INFO:flask_appbuilder.baseviews:Registering route /users/delete/<pk> ['GET', 'POST']
2020-06-06 00:10:47,498:INFO:flask_appbuilder.baseviews:Registering route /users/download/<string:filename> ('GET',)
2020-06-06 00:10:47,499:INFO:flask_appbuilder.baseviews:Registering route /users/edit/<pk> ['GET', 'POST']
2020-06-06 00:10:47,499:INFO:flask_appbuilder.baseviews:Registering route /users/list/ ('GET',)
2020-06-06 00:10:47,500:INFO:flask_appbuilder.baseviews:Registering route /users/show/<pk> ['GET']
2020-06-06 00:10:47,510:INFO:flask_appbuilder.baseviews:Registering route /users/userinfo/ ('GET',)
2020-06-06 00:10:47,582:INFO:flask_appbuilder.base:Registering class RoleModelView on menu List Roles
2020-06-06 00:10:47,582:INFO:flask_appbuilder.baseviews:Registering route /roles/action/<string:name>/<pk> ['GET', 'POST']
2020-06-06 00:10:47,582:INFO:flask_appbuilder.baseviews:Registering route /roles/action_post ['POST']
2020-06-06 00:10:47,582:INFO:flask_appbuilder.baseviews:Registering route /roles/add ['GET', 'POST']
2020-06-06 00:10:47,583:INFO:flask_appbuilder.baseviews:Registering route /roles/api ['GET']
2020-06-06 00:10:47,583:INFO:flask_appbuilder.baseviews:Registering route /roles/api/column/add/<col_name> ['GET']
2020-06-06 00:10:47,583:INFO:flask_appbuilder.baseviews:Registering route /roles/api/column/edit/<col_name> ['GET']
2020-06-06 00:10:47,584:INFO:flask_appbuilder.baseviews:Registering route /roles/api/create ['POST']
2020-06-06 00:10:47,585:INFO:flask_appbuilder.baseviews:Registering route /roles/api/delete/<pk> ['DELETE']
2020-06-06 00:10:47,586:INFO:flask_appbuilder.baseviews:Registering route /roles/api/get/<pk> ['GET']
2020-06-06 00:10:47,586:INFO:flask_appbuilder.baseviews:Registering route /roles/api/read ['GET']
2020-06-06 00:10:47,586:INFO:flask_appbuilder.baseviews:Registering route /roles/api/readvalues ['GET']
2020-06-06 00:10:47,586:INFO:flask_appbuilder.baseviews:Registering route /roles/api/update/<pk> ['PUT']
2020-06-06 00:10:47,586:INFO:flask_appbuilder.baseviews:Registering route /roles/delete/<pk> ['GET', 'POST']
2020-06-06 00:10:47,587:INFO:flask_appbuilder.baseviews:Registering route /roles/download/<string:filename> ('GET',)
2020-06-06 00:10:47,587:INFO:flask_appbuilder.baseviews:Registering route /roles/edit/<pk> ['GET', 'POST']
2020-06-06 00:10:47,587:INFO:flask_appbuilder.baseviews:Registering route /roles/list/ ('GET',)
2020-06-06 00:10:47,587:INFO:flask_appbuilder.baseviews:Registering route /roles/show/<pk> ['GET']
2020-06-06 00:10:47,663:INFO:flask_appbuilder.base:Registering class UserStatsChartView on menu User's Statistics
2020-06-06 00:10:47,663:INFO:flask_appbuilder.baseviews:Registering route /userstatschartview/chart/ ('GET',)
2020-06-06 00:10:47,663:INFO:flask_appbuilder.baseviews:Registering route /userstatschartview/chart/<group_by> ('GET',)
2020-06-06 00:10:47,699:INFO:flask_appbuilder.base:Registering class PermissionModelView on menu Base Permissions
2020-06-06 00:10:47,700:INFO:flask_appbuilder.baseviews:Registering route /permissions/action/<string:name>/<pk> ['GET', 'POST']
2020-06-06 00:10:47,700:INFO:flask_appbuilder.baseviews:Registering route /permissions/action_post ['POST']
2020-06-06 00:10:47,700:INFO:flask_appbuilder.baseviews:Registering route /permissions/add ['GET', 'POST']
2020-06-06 00:10:47,700:INFO:flask_appbuilder.baseviews:Registering route /permissions/api ['GET']
2020-06-06 00:10:47,707:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/column/add/<col_name> ['GET']
2020-06-06 00:10:47,708:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/column/edit/<col_name> ['GET']
2020-06-06 00:10:47,708:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/create ['POST']
2020-06-06 00:10:47,708:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/delete/<pk> ['DELETE']
2020-06-06 00:10:47,709:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/get/<pk> ['GET']
2020-06-06 00:10:47,713:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/read ['GET']
2020-06-06 00:10:47,713:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/readvalues ['GET']
2020-06-06 00:10:47,714:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/update/<pk> ['PUT']
2020-06-06 00:10:47,714:INFO:flask_appbuilder.baseviews:Registering route /permissions/delete/<pk> ['GET', 'POST']
2020-06-06 00:10:47,714:INFO:flask_appbuilder.baseviews:Registering route /permissions/download/<string:filename> ('GET',)
2020-06-06 00:10:47,714:INFO:flask_appbuilder.baseviews:Registering route /permissions/edit/<pk> ['GET', 'POST']
2020-06-06 00:10:47,715:INFO:flask_appbuilder.baseviews:Registering route /permissions/list/ ('GET',)
2020-06-06 00:10:47,724:INFO:flask_appbuilder.baseviews:Registering route /permissions/show/<pk> ['GET']
2020-06-06 00:10:47,794:INFO:flask_appbuilder.base:Registering class ViewMenuModelView on menu Views/Menus
2020-06-06 00:10:47,795:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/action/<string:name>/<pk> ['GET', 'POST']
2020-06-06 00:10:47,795:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/action_post ['POST']
2020-06-06 00:10:47,795:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/add ['GET', 'POST']
2020-06-06 00:10:47,795:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api ['GET']
2020-06-06 00:10:47,795:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/column/add/<col_name> ['GET']
2020-06-06 00:10:47,795:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/column/edit/<col_name> ['GET']
2020-06-06 00:10:47,795:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/create ['POST']
2020-06-06 00:10:47,796:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/delete/<pk> ['DELETE']
2020-06-06 00:10:47,796:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/get/<pk> ['GET']
2020-06-06 00:10:47,796:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/read ['GET']
2020-06-06 00:10:47,796:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/readvalues ['GET']
2020-06-06 00:10:47,796:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/update/<pk> ['PUT']
2020-06-06 00:10:47,796:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/delete/<pk> ['GET', 'POST']
2020-06-06 00:10:47,796:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/download/<string:filename> ('GET',)
2020-06-06 00:10:47,796:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/edit/<pk> ['GET', 'POST']
2020-06-06 00:10:47,796:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/list/ ('GET',)
2020-06-06 00:10:47,796:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/show/<pk> ['GET']
2020-06-06 00:10:47,847:INFO:flask_appbuilder.base:Registering class PermissionViewModelView on menu Permission on Views/Menus
2020-06-06 00:10:47,847:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/action/<string:name>/<pk> ['GET', 'POST']
2020-06-06 00:10:47,847:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/action_post ['POST']
2020-06-06 00:10:47,847:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/add ['GET', 'POST']
2020-06-06 00:10:47,847:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api ['GET']
2020-06-06 00:10:47,847:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/column/add/<col_name> ['GET']
2020-06-06 00:10:47,847:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/column/edit/<col_name> ['GET']
2020-06-06 00:10:47,848:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/create ['POST']
2020-06-06 00:10:47,848:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/delete/<pk> ['DELETE']
2020-06-06 00:10:47,848:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/get/<pk> ['GET']
2020-06-06 00:10:47,848:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/read ['GET']
2020-06-06 00:10:47,848:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/readvalues ['GET']
2020-06-06 00:10:47,848:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/update/<pk> ['PUT']
2020-06-06 00:10:47,848:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/delete/<pk> ['GET', 'POST']
2020-06-06 00:10:47,848:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/download/<string:filename> ('GET',)
2020-06-06 00:10:47,848:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/edit/<pk> ['GET', 'POST']
2020-06-06 00:10:47,848:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/list/ ('GET',)
2020-06-06 00:10:47,849:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/show/<pk> ['GET']
2020-06-06 00:10:47,907:INFO:flask_appbuilder.base:Registering class OpenApi on menu 
2020-06-06 00:10:47,907:INFO:flask_appbuilder.api:Registering route /api/<version>/_openapi ('GET',)
2020-06-06 00:10:47,913:INFO:flask_appbuilder.base:Registering class SwaggerView on menu 
2020-06-06 00:10:47,914:INFO:flask_appbuilder.baseviews:Registering route /swaggerview/<version> ('GET',)
2020-06-06 00:10:47,922:INFO:flask_appbuilder.base:Registering class MenuApi on menu 
2020-06-06 00:10:47,922:INFO:flask_appbuilder.api:Registering route /api/v1/menu/ ['GET']
2020-06-06 00:10:48,049:INFO:flask_appbuilder.base:Registering class ParamatersModelView on menu Parameters
2020-06-06 00:10:48,050:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/action/<string:name>/<pk> ['GET', 'POST']
2020-06-06 00:10:48,050:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/action_post ['POST']
2020-06-06 00:10:48,050:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/add ['GET', 'POST']
2020-06-06 00:10:48,050:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/api ['GET']
2020-06-06 00:10:48,050:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/api/column/add/<col_name> ['GET']
2020-06-06 00:10:48,051:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/api/column/edit/<col_name> ['GET']
2020-06-06 00:10:48,051:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/api/create ['POST']
2020-06-06 00:10:48,051:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/api/delete/<pk> ['DELETE']
2020-06-06 00:10:48,053:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/api/get/<pk> ['GET']
2020-06-06 00:10:48,054:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/api/read ['GET']
2020-06-06 00:10:48,054:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/api/readvalues ['GET']
2020-06-06 00:10:48,054:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/api/update/<pk> ['PUT']
2020-06-06 00:10:48,054:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/delete/<pk> ['GET', 'POST']
2020-06-06 00:10:48,054:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/download/<string:filename> ('GET',)
2020-06-06 00:10:48,055:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/edit/<pk> ['GET', 'POST']
2020-06-06 00:10:48,055:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/list/ ('GET',)
2020-06-06 00:10:48,055:INFO:flask_appbuilder.baseviews:Registering route /paramatersmodelview/show/<pk> ['GET']
2020-06-06 00:10:48,128:INFO:flask_appbuilder.base:Registering class AreasModelView on menu Areas
2020-06-06 00:10:48,128:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/action/<string:name>/<pk> ['GET', 'POST']
2020-06-06 00:10:48,128:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/action_post ['POST']
2020-06-06 00:10:48,129:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/add ['GET', 'POST']
2020-06-06 00:10:48,129:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/api ['GET']
2020-06-06 00:10:48,129:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/api/column/add/<col_name> ['GET']
2020-06-06 00:10:48,129:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/api/column/edit/<col_name> ['GET']
2020-06-06 00:10:48,129:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/api/create ['POST']
2020-06-06 00:10:48,129:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/api/delete/<pk> ['DELETE']
2020-06-06 00:10:48,129:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/api/get/<pk> ['GET']
2020-06-06 00:10:48,129:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/api/read ['GET']
2020-06-06 00:10:48,129:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/api/readvalues ['GET']
2020-06-06 00:10:48,129:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/api/update/<pk> ['PUT']
2020-06-06 00:10:48,129:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/delete/<pk> ['GET', 'POST']
2020-06-06 00:10:48,129:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/download/<string:filename> ('GET',)
2020-06-06 00:10:48,129:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/edit/<pk> ['GET', 'POST']
2020-06-06 00:10:48,129:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/list/ ('GET',)
2020-06-06 00:10:48,129:INFO:flask_appbuilder.baseviews:Registering route /areasmodelview/show/<pk> ['GET']
2020-06-06 00:10:48,192:INFO:flask_appbuilder.base:Registering class EntriesModelView on menu Entries
2020-06-06 00:10:48,193:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/action/<string:name>/<pk> ['GET', 'POST']
2020-06-06 00:10:48,193:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/action_post ['POST']
2020-06-06 00:10:48,193:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/add ['GET', 'POST']
2020-06-06 00:10:48,193:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/api ['GET']
2020-06-06 00:10:48,193:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/api/column/add/<col_name> ['GET']
2020-06-06 00:10:48,193:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/api/column/edit/<col_name> ['GET']
2020-06-06 00:10:48,193:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/api/create ['POST']
2020-06-06 00:10:48,194:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/api/delete/<pk> ['DELETE']
2020-06-06 00:10:48,194:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/api/get/<pk> ['GET']
2020-06-06 00:10:48,194:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/api/read ['GET']
2020-06-06 00:10:48,194:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/api/readvalues ['GET']
2020-06-06 00:10:48,194:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/api/update/<pk> ['PUT']
2020-06-06 00:10:48,194:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/delete/<pk> ['GET', 'POST']
2020-06-06 00:10:48,194:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/download/<string:filename> ('GET',)
2020-06-06 00:10:48,194:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/edit/<pk> ['GET', 'POST']
2020-06-06 00:10:48,194:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/list/ ('GET',)
2020-06-06 00:10:48,194:INFO:flask_appbuilder.baseviews:Registering route /entriesmodelview/show/<pk> ['GET']
2020-06-06 00:10:48,269:INFO:flask_appbuilder.base:Registering class GatesModelView on menu Gates
2020-06-06 00:10:48,270:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/action/<string:name>/<pk> ['GET', 'POST']
2020-06-06 00:10:48,270:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/action_post ['POST']
2020-06-06 00:10:48,270:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/add ['GET', 'POST']
2020-06-06 00:10:48,270:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/api ['GET']
2020-06-06 00:10:48,270:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/api/column/add/<col_name> ['GET']
2020-06-06 00:10:48,270:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/api/column/edit/<col_name> ['GET']
2020-06-06 00:10:48,270:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/api/create ['POST']
2020-06-06 00:10:48,271:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/api/delete/<pk> ['DELETE']
2020-06-06 00:10:48,271:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/api/get/<pk> ['GET']
2020-06-06 00:10:48,271:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/api/read ['GET']
2020-06-06 00:10:48,271:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/api/readvalues ['GET']
2020-06-06 00:10:48,271:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/api/update/<pk> ['PUT']
2020-06-06 00:10:48,271:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/delete/<pk> ['GET', 'POST']
2020-06-06 00:10:48,271:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/download/<string:filename> ('GET',)
2020-06-06 00:10:48,271:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/edit/<pk> ['GET', 'POST']
2020-06-06 00:10:48,271:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/list/ ('GET',)
2020-06-06 00:10:48,271:INFO:flask_appbuilder.baseviews:Registering route /gatesmodelview/show/<pk> ['GET']
2020-06-06 00:10:48,330:INFO:flask_appbuilder.base:Registering class TerminalsModelView on menu Terminals
2020-06-06 00:10:48,330:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/action/<string:name>/<pk> ['GET', 'POST']
2020-06-06 00:10:48,330:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/action_post ['POST']
2020-06-06 00:10:48,330:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/add ['GET', 'POST']
2020-06-06 00:10:48,330:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/api ['GET']
2020-06-06 00:10:48,330:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/api/column/add/<col_name> ['GET']
2020-06-06 00:10:48,330:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/api/column/edit/<col_name> ['GET']
2020-06-06 00:10:48,330:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/api/create ['POST']
2020-06-06 00:10:48,330:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/api/delete/<pk> ['DELETE']
2020-06-06 00:10:48,330:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/api/get/<pk> ['GET']
2020-06-06 00:10:48,330:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/api/read ['GET']
2020-06-06 00:10:48,331:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/api/readvalues ['GET']
2020-06-06 00:10:48,331:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/api/update/<pk> ['PUT']
2020-06-06 00:10:48,331:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/delete/<pk> ['GET', 'POST']
2020-06-06 00:10:48,331:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/download/<string:filename> ('GET',)
2020-06-06 00:10:48,331:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/edit/<pk> ['GET', 'POST']
2020-06-06 00:10:48,331:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/list/ ('GET',)
2020-06-06 00:10:48,331:INFO:flask_appbuilder.baseviews:Registering route /terminalsmodelview/show/<pk> ['GET']
2020-06-06 00:10:48,404:INFO:flask_appbuilder.base:Registering class TerminalTypesModelView on menu Terminal Types
2020-06-06 00:10:48,404:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/action/<string:name>/<pk> ['GET', 'POST']
2020-06-06 00:10:48,404:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/action_post ['POST']
2020-06-06 00:10:48,404:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/add ['GET', 'POST']
2020-06-06 00:10:48,404:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/api ['GET']
2020-06-06 00:10:48,405:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/api/column/add/<col_name> ['GET']
2020-06-06 00:10:48,405:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/api/column/edit/<col_name> ['GET']
2020-06-06 00:10:48,405:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/api/create ['POST']
2020-06-06 00:10:48,405:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/api/delete/<pk> ['DELETE']
2020-06-06 00:10:48,405:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/api/get/<pk> ['GET']
2020-06-06 00:10:48,405:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/api/read ['GET']
2020-06-06 00:10:48,405:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/api/readvalues ['GET']
2020-06-06 00:10:48,405:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/api/update/<pk> ['PUT']
2020-06-06 00:10:48,405:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/delete/<pk> ['GET', 'POST']
2020-06-06 00:10:48,405:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/download/<string:filename> ('GET',)
2020-06-06 00:10:48,405:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/edit/<pk> ['GET', 'POST']
2020-06-06 00:10:48,405:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/list/ ('GET',)
2020-06-06 00:10:48,405:INFO:flask_appbuilder.baseviews:Registering route /terminaltypesmodelview/show/<pk> ['GET']
2020-06-06 00:10:48,481:INFO:flask_appbuilder.base:Registering class ActionApi on menu 
2020-06-06 00:10:48,482:INFO:flask_appbuilder.api:Registering route /api/v1/actionapi/decrease ('GET',)
2020-06-06 00:10:48,482:INFO:flask_appbuilder.api:Registering route /api/v1/actionapi/increase ('GET',)
2020-06-06 00:10:48,482:INFO:flask_appbuilder.api:Registering route /api/v1/actionapi/reset ('GET',)
2020-06-06 00:10:48,488:INFO:flask_appbuilder.base:Registering class AreasApi on menu 
2020-06-06 00:10:48,488:INFO:flask_appbuilder.api:Registering route /api/v1/areasapi/areas/list ('GET',)
Traceback (most recent call last):
  File "/Users/manane/Developer/ZucchettiAxess/PeopleCounterProj/PeopleCounterWebConfig/venv/bin/waitress-serve", line 8, in <module>
    sys.exit(run())
  File "/Users/manane/Developer/ZucchettiAxess/PeopleCounterProj/PeopleCounterWebConfig/venv/lib/python3.7/site-packages/waitress/runner.py", line 280, in run
    app = app()
TypeError: __call__() missing 2 required positional arguments: 'environ' and 'start_response'

**Comment by moqca** [comment]
Currently running flask appbuilder with waitress:

```
from waitress import serve
from app import app

serve(app)
```

Or procfile:

`web: waitress-serve --port=$PORT app:app`

**Comment by andreamancini-work** [comment]
It works very well. Thanks
