### ISSUE TITLE
[AuditMixin] Cannot update row because of 'changed_by_fk' cannot be null

### ISSUE THREAD

**Issue by fainyang** [dpgaspar/Flask-AppBuilder#1397]
https://github.com/dpgaspar/Flask-AppBuilder/issues/225

### Environment
Package                Version
apispec                1.3.3  
attrs                  19.3.0 
Babel                  2.8.0  
click                  7.1.2  
colorama               0.4.3  
defusedxml             0.6.0  
dnspython              1.16.0 
email-validator        1.0.5  
Flask                  1.1.2  
Flask-AppBuilder       2.3.4  
Flask-Babel            1.0.0  
Flask-JWT-Extended     3.24.1 
Flask-Login            0.4.1  
Flask-OpenID           1.2.5  
Flask-SQLAlchemy       2.4.1  
Flask-WTF              0.14.3 
idna                   2.9    
importlib-metadata     1.6.0  
itsdangerous           1.1.0  
Jinja2                 2.11.2 
jsonschema             3.2.0  
MarkupSafe             1.1.1  
marshmallow            2.21.0 
marshmallow-enum       1.5.1  
marshmallow-sqlalchemy 0.23.0 
Pillow                 7.1.2  
pip                    20.0.2 
prison                 0.1.3  
PyJWT                  1.7.1  
pyrsistent             0.16.0 
python-dateutil        2.8.1  
python3-openid         3.1.0  
pytz                   2019.3 
PyYAML                 5.3.1  
setuptools             41.2.0 
six                    1.14.0 
SQLAlchemy             1.3.16 
SQLAlchemy-Utils       0.36.3 
Werkzeug               1.0.1  
WTForms                2.3.1  
zipp                   3.1.0  

pip freeze output: 

### Describe the expected results

I want to update a row in table book1 with AuditMixin, but when I update it's failed, but it can succeed if change_by user is different from the old one

```python
# model.py
from flask_appbuilder import Model
from sqlalchemy import Column, Integer, String, Date
from flask_appbuilder.models.mixins import AuditMixin

class Book1(Model,AuditMixin):
    id = Column(Integer, primary_key=True)
    name = Column(
        String(64), unique=True, nullable=False
    )
    publish = Column(Date)

    def __repr__(self):
        return self.name

# -----------------------------------------------
# views.py
from flask_babel import lazy_gettext as _
from app import appbuilder
from flask_appbuilder.api import BaseApi, expose
from flask_appbuilder.security.sqla.models import User
from app import db
from flask_appbuilder import ModelView
from flask_appbuilder.models.sqla.interface import SQLAInterface
from app.models import Book1
from datetime import date, timedelta

class BookView(ModelView):
    datamodel = SQLAInterface(Book1)
    list_columns = [
        "name",
        "publish",
        "created_by",
        "created_on",
    ]
    add_exclude_columns = [
        "created_by",
        "changed_by",
        "created_on",
        "changed_on",
    ]

class TestApi(BaseApi):
    resource_name = "change"

    @expose("/test/<int:pk>", methods=["GET"])
    def approval_s3(self, pk):
        book = (
            appbuilder.get_session.query(Book1)
            .filter(Book1.id == pk) 
            .first()
        )

        user = (
            appbuilder.get_session.query(User)
            .filter(User.id == 1)  # here can change user_id when test
            .first()
        )

        expire_date = date.today() + timedelta(days=12)
        book.publish = expire_date
        book.changed_by = user
        db.session.add(book)
        db.session.commit()

        return "ok"


appbuilder.add_api(TestApi)
appbuilder.add_view(BookView, "test", icon="fa-group", label=_('My Book View'),
                     category="My Book", category_icon="fa-cogs")
```

### Describe the actual results
I have 2 admin users: user1 and user2, I have add some book records by user1. 

when I call the API http://127.0.0.1:5000/api/v1/change/test/1 to change publish date, if the first time call, the change_by(user1) is the same with old one(user1), it will fail, the return is 
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or
	there is an error in the application.</p> 
```

If I change to use user2, the change_by(user2) is different from the old one(user1), then can update the row. For next time call, it's ok whatever the user is the same or different from old one

```pytb
2020-06-12 22:20:37,477:ERROR:app:Exception on /api/v1/change/test/4 [GET]
Traceback (most recent call last):
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: book1.changed_by_fk

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yang.fei/python/flask_project/feiyang/app/views.py", line 53, in approval_s3
    db.session.commit()
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 995, in _emit_update_statements
    statement, multiparams
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/Users/yang.fei/python/flask_project/.env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: book1.changed_by_fk
[SQL: UPDATE book1 SET changed_on=?, publish=?, changed_by_fk=? WHERE book1.id = ?]
[parameters: ('2020-06-12 22:20:37.477360', '2020-06-24', None, 4)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2020-06-12 22:20:37,479:INFO:werkzeug:127.0.0.1 - - [12/Jun/2020 22:20:37] "GET /api/v1/change/test/4 HTTP/1.1" 500 -

```

### Steps to reproduce
1. create the fab app, copy views.py and model.py
2. run fab app, create 2 admin users
3. add some record of books
4. use postman without Cookie call the API http://127.0.0.1:5000/api/v1/change/test/1
5. first-time call will fail, then change code in views.py User.id == 2, then call again will success
6. then can continue to call, it always success whatever user is user1 or user2

**Comment by fainyang** [comment]
If I use @protect() for auth, no need changed_by, it's ok.
