### ISSUE TITLE
LocaleView index lang raises exception for non-existent languages

### ISSUE THREAD

**Issue by kb100** [dpgaspar/Flask-AppBuilder#1459]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version: 3.0.1

pip freeze output:
apispec==3.3.1
attrs==20.1.0
Babel==2.8.0
blinker==1.4
click==7.1.2
colorama==0.4.3
defusedxml==0.6.0
dnspython==2.0.0
email-validator==1.1.1
Flask==1.1.2
Flask-AppBuilder==3.0.1
Flask-Babel==1.0.0
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.4
Flask-WTF==0.14.3
idna==2.10
itsdangerous==1.1.0
Jinja2==2.11.2
jsonschema==3.2.0
MarkupSafe==1.1.1
marshmallow==3.7.1
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.1
prison==0.1.3
PyJWT==1.7.1
pyrsistent==0.16.0
python-dateutil==2.8.1
python3-openid==3.2.0
pytz==2020.1
PyYAML==5.3.1
six==1.15.0
SQLAlchemy==1.3.19
SQLAlchemy-Utils==0.36.8
Werkzeug==1.0.1
WTForms==2.3.3

### Describe the expected results

1. Visit any example app route /lang/nonexistentlanguage, e.g. http://flaskappbuilder.pythonanywhere.com/lang/nonexistentlanguage
2. 404 or other error page stating translations not available for nonexistentlanguage

### Describe the actual results

1. Visit any example app route /lang/nonexistentlanguage, e.g. http://flaskappbuilder.pythonanywhere.com/lang/nonexistentlanguage
2. 500 Internal Server Error The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

```pytb
Traceback (most recent call last):
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\views.py", line 41, in index
    return self.render_template(self.index_template, appbuilder=self.appbuilder)
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\baseviews.py", line 280, in render_template
    return render_template(
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\app\templates\index.html", line 1, in top-level template code
    {% extends "appbuilder/base.html" %}
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\templates\appbuilder\base.html", line 1, in top-level template code
    {% extends base_template %}
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\app\templates\mybase.html", line 1, in top-level template code
    {% extends 'appbuilder/baselayout.html' %}
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\templates\appbuilder\baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\templates\appbuilder\init.html", line 46, in top-level template code
    {% block body %}
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\templates\appbuilder\baselayout.html", line 5, in block "body"
    {% include 'appbuilder/general/confirm.html' %}
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\templates\appbuilder\general\confirm.html", line 6, in top-level template code
    {{_('User confirmation needed')}}
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\jinja2\ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "C:\Users\myuserPycharmProjects\FAB-test-site\venv\Lib\site-packages\jinja2\ext.py", line 150, in gettext
    rv = __context.call(func, __string)
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_babel\__init__.py", line 110, in <lambda>
    lambda x: get_translations().ugettext(x),
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_babel\__init__.py", line 221, in get_translations
    [get_locale()],
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_babel\__init__.py", line 255, in get_locale
    locale = Locale.parse(rv)
  File "C:\Users\myuser\PycharmProjects\FAB-test-site\venv\Lib\site-packages\babel\core.py", line 331, in parse
    raise UnknownLocaleError(input_id)
babel.core.UnknownLocaleError: unknown locale 'nonexistentlanguage'
```

The issue seems to be related to LocaleView's index method, which does not check to see if the locale exists before setting it.

**Comment by dpgaspar** [comment]
Thank you for reporting this!

Should be a simple PR, are you willing to take a stab at it?

**Comment by kb100** [comment]
@dpgaspar I'm very new to FAB, I took a stab at it, let me know if I attacked it the right way.
