### ISSUE TITLE
Crash: List views do not validate request arguments

### ISSUE THREAD

**Issue by kb100** [dpgaspar/Flask-AppBuilder#1469]
Apparently list views, which allow searching on different fields, do not check their request arguments before acting upon them (even querying the database!!) I've gotten crashes by providing a few bad args, but the few examples provided below are likely not the only ways to crash with bad args.

Environment
Flask-Appbuilder version: 3.0.1

pip freeze output:
apispec==3.3.1
attrs==20.1.0
Babel==2.8.0
blinker==1.4
click==7.1.2
colorama==0.4.3
defusedxml==0.6.0
dnspython==2.0.0
email-validator==1.1.1
Flask==1.1.2
Flask-AppBuilder==3.0.1
Flask-Babel==1.0.0
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.4
Flask-WTF==0.14.3
idna==2.10
itsdangerous==1.1.0
Jinja2==2.11.2
jsonschema==3.2.0
MarkupSafe==1.1.1
marshmallow==3.7.1
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.1
prison==0.1.3
PyJWT==1.7.1
pyrsistent==0.16.0
python-dateutil==2.8.1
python3-openid==3.2.0
pytz==2020.1
PyYAML==5.3.1
six==1.15.0
SQLAlchemy==1.3.19
SQLAlchemy-Utils==0.36.8
Werkzeug==1.0.1
WTForms==2.3.3

### Steps to Reproduce

1. Go to any FAB list view with request args, e.g. http://127.0.0.1:5000/users/list/?_flt_0_username=test
2. Fiddle with the request args.

### Expected

1. The app should validate that args are valid and not crash
2. If invalid args are given, an error should be displayed

### Actual

The following args cause 500 server error
1.  http://127.0.0.1:5000/users/list/?_flt_0_nonexistantkey=anything
2. http://127.0.0.1:5000/users/list/?_flt_1_changed_on=notadate

### Tracebacks

```pytb
2020-09-10 16:20:30,745:INFO:werkzeug:127.0.0.1 - - [10/Sep/2020 16:20:30] "GET /users/list/?_flt_0_nonexistent=1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\security\decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\views.py", line 551, in list
    widgets = self._list()
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\baseviews.py", line 1121, in _list
    get_filter_args(self._filters)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\urltools.py", line 99, in get_filter_args
    filters.add_filter_index(
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\models\filters.py", line 178, in add_filter_index
    self._add_filter(self._all_filters[column_name][filter_instance_index], value)
KeyError: 'nonexistent'


2020-09-10 16:23:52,963:INFO:werkzeug:127.0.0.1 - - [10/Sep/2020 16:23:52] "GET /users/list/?_flt_1_changed_on=notadate HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\security\decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\views.py", line 551, in list
    widgets = self._list()
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\baseviews.py", line 1122, in _list
    widgets = self._get_list_widget(
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\baseviews.py", line 1021, in _get_list_widget
    count, lst = self.datamodel.query(
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\models\sqla\interface.py", line 361, in query
    count = self.query_count(query, filters, select_columns)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\models\sqla\interface.py", line 284, in query_count
    return self._apply_inner_all(
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\models\sqla\interface.py", line 272, in _apply_inner_all
    query = self.apply_filters(query, inner_filters)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\models\sqla\interface.py", line 162, in apply_filters
    return filters.apply_all(query)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\models\filters.py", line 295, in apply_all
    query = flt.apply(query, value)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\flask_appbuilder\models\sqla\filters.py", line 159, in apply
    return query.filter(field > value)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\sqlalchemy\sql\operators.py", line 404, in __gt__
    return self.operate(gt, other)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\sqlalchemy\orm\attributes.py", line 219, in operate
    return op(self.comparator, *other, **kwargs)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\sqlalchemy\sql\operators.py", line 404, in __gt__
    return self.operate(gt, other)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\sqlalchemy\orm\properties.py", line 367, in operate
    return op(self.__clause_element__(), *other, **kwargs)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\sqlalchemy\sql\operators.py", line 404, in __gt__
    return self.operate(gt, other)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 762, in operate
    return op(self.comparator, *other, **kwargs)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\sqlalchemy\sql\operators.py", line 404, in __gt__
    return self.operate(gt, other)
  File "<string>", line 1, in <lambda>

  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\sqlalchemy\sql\type_api.py", line 67, in operate
    return o[0](self.expr, op, *(other + o[1:]), **kwargs)
  File "C:\Users\user\PycharmProjects\FAB-test-site\venv\Lib\site-packages\sqlalchemy\sql\default_comparator.py", line 99, in _boolean_compare
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Only '=', '!=', 'is_()', 'isnot()', 'is_distinct_from()', 'isnot_distinct_from()' operators can be used with None/True/False
```

**Comment by dpgaspar** [comment]
Thank you for reporting this, are you willing to make a PR to fix it?
