### ISSUE TITLE
Problem using LDAP authenticaion

### ISSUE THREAD

**Issue by a-mckinley** [dpgaspar/Flask-AppBuilder#150]
Hi,

I have set my app to use LDAP authentication and having a problem using it.

I am running into the following exception:

```
2015-04-15 17:00:18,020:INFO:werkzeug:192.168.30.88 - - [15/Apr/2015 17:00:18] "POST /login/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/root/flask_app/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/flask_app/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/root/flask_app/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/flask_app/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/flask_app/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/flask_app/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/flask_app/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/flask_app/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/flask_app/lib/python2.7/site-packages/flask_appbuilder/security/views.py", line 367, in login
    user = self.appbuilder.sm.auth_user_ldap(form.username.data, form.password.data)
  File "/root/flask_app/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 387, in auth_user_ldap
    self.update_user_auth_stat(user, False)
  File "/root/flask_app/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 298, in update_user_auth_stat
    if not user.login_count:
AttributeError: 'NoneType' object has no attribute 'login_count'
```

This is happening on both failed and successful logins (as verified by logs on the LDAP server).  Do the users need to be created before LDAP authentication can succeed?

**Comment by dpgaspar** [comment]
Seems like the ab_user table does not have the *login_count* column. Your using SQLAlchemy or MongoEngine?

if using SQLAlchemy send me the ab_user table DDL.

**Comment by a-mckinley** [comment]
Hi @dpgaspar 

Thanks for your quick response.

I managed to get the framework working with our ldap setup with a couple of small changes.  For our ldap server we need to bind first, and then search to get the user details.

I noticed that in the current implemenation of auth_user_ldap() that if AUTH_LDAP_SEARCH is not set, you will bind without ever searching for the user information and then ldap_user_info will be referenced before assignment in the call to add_user().

I am not familiar with ldap so I am not certain if this is the correct fix but here is the patch.

```
From b179770b41d329ef61c9bc5c13a2873a4542b237 Mon Sep 17 00:00:00 2001
From: Alastair McKinley <a.mckinley@analyticsengines.com>
Date: Thu, 16 Apr 2015 11:17:02 +0100
Subject: [PATCH] allow ldap binding before searching and self signed certs

---
 security/manager.py | 19 ++++++++++++++++++-
 1 file changed, 18 insertions(+), 1 deletion(-)

diff --git a/security/manager.py b/security/manager.py
index 3eeacc9..6e72bd2 100644
--- a/security/manager.py
+++ b/security/manager.py
@@ -134,6 +134,8 @@ class BaseSecurityManager(AbstractSecurityManager):
         # LDAP Config
         app.config.setdefault('AUTH_LDAP_SEARCH', '')
         app.config.setdefault('AUTH_LDAP_BIND_FIELD', 'cn')
+        app.config.setdefault('AUTH_LDAP_BIND_FIRST', False)
+        app.config.setdefault('AUTH_LDAP_ALLOW_SELF_SIGNED', False)
         app.config.setdefault('AUTH_LDAP_UID_FIELD', 'uid')
         app.config.setdefault('AUTH_LDAP_FIRSTNAME_FIELD', 'givenName')
         app.config.setdefault('AUTH_LDAP_LASTNAME_FIELD', 'sn')
@@ -205,6 +207,14 @@ class BaseSecurityManager(AbstractSecurityManager):
         return self.appbuilder.get_app.config['AUTH_LDAP_EMAIL_FIELD']
 
     @property
+    def auth_ldap_bind_first(self):
+        return self.appbuilder.get_app.config['AUTH_LDAP_BIND_FIRST']
+
+    @property
+    def auth_ldap_allow_self_signed(self):
+        return self.appbuilder.get_app.config['AUTH_LDAP_ALLOW_SELF_SIGNED']
+
+    @property
     def openid_providers(self):
         return self.appbuilder.get_app.config['OPENID_PROVIDERS']
 
@@ -350,9 +360,15 @@ class BaseSecurityManager(AbstractSecurityManager):
             except:
                 raise Exception("No ldap library for python.")
             try:
+                if self.auth_ldap_allow_self_signed:
+                    ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_ALLOW)
+
                 con = ldap.initialize(self.auth_ldap_server)
                 con.set_option(ldap.OPT_REFERRALS, 0)
                 try:
+                    if self.auth_ldap_bind_first:
+                        con.bind_s(username, password)
+
                     if not self.auth_ldap_search:
                         bind_username = username
                     else:
@@ -370,7 +386,8 @@ class BaseSecurityManager(AbstractSecurityManager):
                             bind_username = bind_username_array[0][0]
                             ldap_user_info = bind_username_array[0][1]
 
-                    con.bind_s(bind_username, password)
+                    if not self.auth_ldap_bind_first:
+                        con.bind_s(bind_username, password)
 
                     if self.auth_user_registration and user is None:
                         user = self.add_user(
-- 
1.8.3.1
```

**Comment by dpgaspar** [comment]
Could you please submit a pull request for this?
