### ISSUE TITLE
Enum columns with names that do not match values cause KeyError

### ISSUE THREAD

**Issue by joshzana** [dpgaspar/Flask-AppBuilder#1544]
### Environment

Flask-Appbuilder version:
3.1.1

pip freeze output:
<details><summary>click to expand</summary>
```
aiobotocore==1.1.2
aiohttp==3.7.3
aioitertools==0.7.1
alembic==1.4.3
apache-airflow==1.10.14
apispec==3.3.2
argcomplete==1.12.2
async-timeout==3.0.1
attrs==20.3.0
aws-encryption-sdk==1.4.1
Babel==2.9.0
boto3==1.16.45
botocore==1.19.45
cached-property==1.5.2
cachetools==4.2.0
cattrs==1.1.2
certifi==2020.12.5
cffi==1.14.4
chardet==3.0.4
click==7.1.2
cmdstanpy==0.9.5
colorama==0.4.4
colorlog==4.0.2
configcat-client==5.0.0
configparser==3.5.3
convertdate==2.3.0
croniter==0.3.36
cryptography==3.3.1
cycler==0.10.0
Cython==0.29.21
datadog==0.39.0
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.3
dnspython==2.0.0
docopt==0.6.2
docutils==0.15.2
ecdsa==0.14.1
email-validator==1.1.2
enum-compat==0.0.3
ephem==3.7.7.1
fastapi==0.62.0
fbprophet==0.7.1
Flask==1.1.2
Flask-Admin==1.5.4
Flask-AppBuilder==3.1.1
Flask-Babel==1.0.0
Flask-Caching==1.3.3
Flask-JWT-Extended==3.25.0
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.4
flask-swagger==0.2.14
Flask-WTF==0.14.3
fsspec==0.8.5
funcsigs==1.0.2
future==0.18.2
google-auth==1.24.0
graphviz==0.16
gunicorn==20.0.4
h11==0.12.0
holidays==0.10.4
idna==2.10
importlib-metadata==3.3.0
importlib-resources==1.5.0
iso8601==0.1.13
itsdangerous==1.1.0
Jinja2==2.11.2
jmespath==0.10.0
joblib==1.0.0
json-merge-patch==0.2
jsonschema==3.2.0
kiwisolver==1.3.1
korean-lunar-calendar==0.2.1
kubernetes==11.0.0
lazy-object-proxy==1.4.3
lockfile==0.12.2
LunarCalendar==0.0.9
Mako==1.1.3
Markdown==2.6.11
MarkupSafe==1.1.1
marshmallow==3.10.0
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.1
matplotlib==3.3.3
more-itertools==8.6.0
multidict==5.0.2
natsort==7.1.0
networkx==2.5
numpy==1.19.4
oauthlib==2.1.0
packaging==20.8
pandas==1.1.4
parse==1.18.0
patsy==0.5.1
pendulum==1.4.4
Pillow==8.1.0
pluggy==0.13.1
prison==0.1.3
psutil==5.8.0
psycopg2-binary==2.8.6
py==1.10.0
pyarrow==2.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pydantic==1.7.3
pydlm==0.1.1.11
Pygments==2.7.3
PyJWT==1.7.1
PyMeeus==0.3.7
pyparsing==2.4.7
pyrsistent==0.17.3
pystan==2.19.1.1
pytest==5.4.1
pytest-watch==4.2.0
python-daemon==2.2.4
python-dateutil==2.8.1
python-editor==1.0.4
python-jose==3.2.0
python-nvd3==0.15.0
python-slugify==4.0.1
python3-openid==3.2.0
pytz==2020.5
pytzdata==2020.1
PyYAML==5.3.1
requests==2.23.0
requests-oauthlib==1.1.0
rsa==4.6
s3fs==0.5.1
s3transfer==0.3.3
scikit-learn==0.23.2
scipy==1.5.4
semver==2.13.0
sentry-sdk==0.19.4
setproctitle==1.2.1
setuptools-git==1.2
six==1.15.0
SQLAlchemy==1.3.22
SQLAlchemy-JSONField==0.9.0
SQLAlchemy-Utils==0.36.8
sqlparse==0.3.1
starlette==0.13.6
statsmodels==0.12.1
tabulate==0.8.7
tenacity==4.12.0
text-unidecode==1.3
threadpoolctl==2.1.0
thrift==0.13.0
tqdm==4.55.1
typing-extensions==3.7.4.3
tzlocal==1.5.1
unicodecsv==0.14.1
urllib3==1.26.2
uvicorn==0.12.3
watchdog==1.0.2
wcwidth==0.2.5
websocket-client==0.57.0
Werkzeug==1.0.1
wrapt==1.12.1
WTForms==2.3.3
yarl==1.6.3
zipp==3.4.0
zope.deprecation==4.4.0
```
</details>

SqlAlchemy allows enum columns where the name and value differ (eg in terms of case) but Flask App Builder throws a KeyError when using one.

### Sample Code:
models.py:
```python
from enum import Enum
from sqlalchemy import Column, Integer, Enum as SqlEnum
from sqlalchemy.schema import MetaData
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base(metadata=MetaData())


class Interval(Enum):
    HOUR = "hour"
    DAY = "day"


class Metric(Base):

    __tablename__ = "metrics"
    id = Column(Integer, primary_key=True)
    interval = Column(
        SqlEnum(
            Interval,
            values_callable=lambda enum: [e.value for e in enum],
            name="interval_enum",
            create_type=False,
        ),
        nullable=False,
    )

```

views.py:
```
from flask_appbuilder import ModelView
from flask_appbuilder.models.sqla.interface import SQLAInterface
from . import appbuilder
from .models import Metric


class MetricModelView(ModelView):
    datamodel = SQLAInterface(Metric)
    list_columns = ["id", "interval"]


appbuilder.add_view(
    MetricModelView,
    "Metric",
    category="Data",
)
```

### Describe the actual results

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/middleware/dispatcher.py", line 66, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/views.py", line 584, in add
    widget = self._add()
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/baseviews.py", line 1159, in _add
    form = self.add_form.refresh()
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/forms.py", line 329, in refresh
    form = self(obj=obj)
  File "/usr/local/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wtforms/form.py", line 268, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "/usr/local/lib/python3.8/site-packages/wtforms/form.py", line 51, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "/usr/local/lib/python3.8/site-packages/wtforms/meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "/usr/local/lib/python3.8/site-packages/wtforms/fields/core.py", line 376, in bind
    return self.field_class(*self.args, **kw)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/fields.py", line 245, in __init__
    labels = [
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/fields.py", line 246, in <listcomp>
    text_type(enum_class.__members__[enum_member].value)
KeyError: 'hour'
```

### Steps to reproduce

- Add a SqlAlchemy model with a column that is of type sqlalchemy.Enum
- For the enum type, declare a Python enum, where the names are UPPER_CASE and the values are lower_case
- Should be able to read and write rows of that table in the FAB UI
- Instead, get the above exception
- Switching the enum to have HOUR = "HOUR" etc fixes the issue, but that is not an option for us as we have an existing database that we do not want to migrate.

**Comment by dpgaspar** [comment]
Strange, `enum`'s are supported and tested like this: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/tests/sqla/models.py#L107

where the members are totally different from the value, can you do a simple SQLAlchemy query from your model, fetch and test in someway `enum_class.__members__[enum_member].value` ?

**Comment by joshzana** [comment]
@dpgaspar thanks for the quick response!

I wasn't aware of that test case, but when I use the syntax there, I don't get the exception either.

To answer your immediate question, if I try this:
```
print([
    (Interval.__members__[enum_member].value)
    for enum_member in list(Interval.__members__)
])
```

I get ` ['hour', 'day']`

(I think that's what you are asking for based on the context in `fields.py`, but I can't see the values of `enum_class` or the `enums` arg there)

Narrowing down a bit further, the issue seems to be with our use of `values_callable`. From the sa docs:

```
    In order to persist the values and not the names, the
    :paramref:`.Enum.values_callable` parameter may be used.   The value of
    this parameter is a user-supplied callable, which  is intended to be used
    with a PEP-435-compliant enumerated class and  returns a list of string
    values to be persisted.   For a simple enumeration that uses string values,
    a callable such as  ``lambda x: [e.value for e in x]`` is sufficient.
```

So it seems like your test case that uses `Column(Enum(TmpEnum)` is persisting `['e1', 'e2', 'e3']` to the db instead of the values `['a', 2, 3]`, which is not how our db schema works.  We expect to have `['hour', 'day']` in the db.

Would you mind adding a test case on your end that uses `values_callable = lambda x: [e.value for e in x]`?  That should reproduce it right away.
