### ISSUE TITLE
Define mode column variable named ‘process’ cause error

### ISSUE THREAD

**Issue by hsp8712** [dpgaspar/Flask-AppBuilder#1552]
### Environment

Flask-Appbuilder version: 3.1.1

pip freeze output:
apispec==3.3.2
attrs==20.3.0
Authlib==0.15.3
Babel==2.9.0
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
click==7.1.2
colorama==0.4.4
cryptography==3.3.1
defusedxml==0.6.0
dnspython==2.1.0
email-validator==1.1.2
Flask==1.1.2
Flask-AppBuilder==3.1.1
Flask-Babel==1.0.0
Flask-JWT-Extended==3.25.0
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.4
Flask-WTF==0.14.3
idna==2.10
importlib-metadata==3.4.0
itsdangerous==1.1.0
Jinja2==2.11.2
jmespath==0.10.0
jsonschema==3.2.0
MarkupSafe==1.1.1
marshmallow==3.10.0
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.1
packaging==20.8
prison==0.1.3
psycopg2==2.8.6
pycparser==2.20
PyJWT==1.7.1
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
python3-openid==3.2.0
pytz==2020.5
PyYAML==5.4.1
requests==2.25.1
six==1.15.0
SQLAlchemy==1.3.22
sqlalchemy-redshift==0.8.2
SQLAlchemy-Utils==0.36.8
typing-extensions==3.7.4.3
urllib3==1.26.2
Werkzeug==1.0.1
WTForms==2.3.3
zipp==3.4.0

### Describe the expected results

Below is my code:

modes.py:
```python
class Test(Model):
    id = Column(INT, primary_key=True)
    process = Column(String(100))

    def __repr__(self):
        return self.id
```
views.py:
```
class TestModelView(ModelView):
    datamodel = SQLAInterface(Test)
appbuilder.add_view(TestModelView, "Test", category="Test")

```

### Describe the actual results

When click menu link of Test, error show below:

```pytb
2021-01-24 02:10:09,451:INFO:werkzeug:127.0.0.1 - - [24/Jan/2021 02:10:09] "GET /testmodelview/list/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\flask_appbuilder\security\decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\flask_appbuilder\views.py", line 551, in list
    widgets = self._list()
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\flask_appbuilder\baseviews.py", line 1129, in _list
    form = self.search_form.refresh()
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\flask_appbuilder\forms.py", line 329, in refresh
    form = self(obj=obj)
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\hsp87\.virtualenvs\sla-meta-5mDGH48N\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
TypeError: __call__() takes 1 positional argument but 3 were given
```

I look like a namespace comflict.

Avoiding using ‘process’ as the name can be a temporary solution:
```
process_ = Column("process", String(100))
```

### Steps to reproduce
Use my code to reproduce

**Comment by dpgaspar** [comment]
Interesting, seems like a WTForm name conflict since a method named `process` already exists and conflicts with the dynamically created property (not confirmed, a guess)
