### ISSUE TITLE
Flask AppBuilder update from 2.1.5 and 3.1.1

### ISSUE THREAD

**Issue by danner26** [dpgaspar/Flask-AppBuilder#1563]
### Environment

Flask-Appbuilder version: 3.1.1

pip freeze output:
```
alembic==1.5.4
aniso8601==8.1.1
apispec==3.3.2
attrs==20.3.0
Babel==2.9.0
beautifulsoup4==4.9.3
blinker==1.4
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
click==7.1.2
colorama==0.4.4
cryptography==3.4.3
defusedxml==0.6.0
django-htmlmin==0.11.0
dnspython==2.1.0
elementpath==2.1.3
email-validator==1.1.2
Flask==1.1.2
Flask-AppBuilder==3.1.1
Flask-Babel==1.0.0
Flask-DebugToolbar==0.11.0
Flask-JWT-Extended==3.25.0
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-Migrate==2.6.0
Flask-OpenID==1.2.5
Flask-RESTful==0.3.8
Flask-SQLAlchemy==2.4.4
Flask-WTF==0.14.3
gitdb==4.0.5
GitPython==3.1.13
html5lib==1.1
htmlmin==0.1.12
idna==2.10
importlib-metadata==3.4.0
importlib-resources==5.1.0
itsdangerous==1.1.0
Jinja2==2.11.3
json2html==1.3.0
jsonschema==3.2.0
lxml==4.6.2
Mako==1.1.4
MarkupSafe==1.1.1
marshmallow==3.10.0
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.1
prettytable==2.0.0
prison==0.1.3
psycopg2==2.7.7
psycopg2-binary==2.8.6
pycparser==2.20
PyJWT==1.7.1
pyOpenSSL==20.0.1
pyrsistent==0.17.3
pysaml2==6.5.1
python-crontab==2.5.1
python-dateutil==2.8.1
python-dotenv==0.15.0
python-editor==1.0.4
python3-openid==3.2.0
pytz==2021.1
PyYAML==5.4.1
requests==2.25.1
six==1.15.0
smmap==3.0.5
soupsieve==2.1
SQLAlchemy==1.3.23
SQLAlchemy-Utils==0.36.8
typing-extensions==3.7.4.3
urllib3==1.26.3
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==1.0.1
WTForms==2.3.3
xmlschema==1.5.0
xmltodict==0.12.0
zipp==3.4.0

```

### Describe the expected results

When using the edit button it takes us to the edit page delivered by appbuilder, but it gives us this error:
```
Traceback (most recent call last):
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/usr/lib64/python3.6/cProfile.py", line 109, in runcall
    return func(*args, **kw)
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask_appbuilder/views.py", line 610, in edit
    related_views=self._related_views,
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask_appbuilder/baseviews.py", line 281, in render_template
    template, **dict(list(kwargs.items()) + list(self.extra_args.items()))
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/model/edit.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/opt/webapps/iamp/IAMP/app/templates/appbuilder/baselayout.html", line 4, in top-level template code
    {% set languages = appbuilder.languages %}
  File "/opt/webapps/iamp/IAMP/app/templates/appbuilder/init.html", line 59, in top-level template code
    {% block body %}
  File "/opt/webapps/iamp/IAMP/app/templates/appbuilder/baselayout.html", line 25, in block "body"
    {% block content %}
  File "/opt/webapps/iamp/venv/lib64/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/model/edit.html", line 5, in block "content"
    {{ lib.panel_begin(title, "edit") }}
TypeError: macro 'panel_begin' takes not more than 1 argument(s)
```
It says that panel_begin only takes 1 argument even though when we take a look at lib.html the macro accepts 2. We upgraded our modules from 2.1.5 to 3.1.1 as well as other package versions. 
This occurs for the edit, as well as the show pages. It seems anything that uses the panel_begin method with 2 objects passed to it errors out.

**Comment by walshg3** [comment]
Codebase changes seem to be begin starting Merge [1124](https://github.com/dpgaspar/Flask-AppBuilder/pull/1124/files)
the panel_begin adds the second argument in 2.2.0

**Comment by danner26** [comment]
As a heads up for anyone that finds this in a similar situation as ourselves, we inherited this project from another team member. They overwrote the lib.html file, which we did not notice yesterday. Removing that file (since there were no actual changes to it) resolved the issue for us. Thank you
