### ISSUE TITLE
Running tests: DB Creation and initialization failed 

### ISSUE THREAD

**Issue by runoutnow** [dpgaspar/Flask-AppBuilder#1567]
I don't know if this is a flask_appbuilder issue, probably not. But I do need to solve this in order to be able to run tests via bash (so I can write and test tests and finish my pull request according to the new reset password functions).

### Environment

Flask-Appbuilder version: 3.1.1

pip freeze output:
-f /usr/share/pip-wheels
apispec==3.3.2
attrs==20.2.0
Babel==2.8.0
blinker==1.4
Brotli==1.0.9
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
colorama==0.4.3
dash==1.17.0
dash-core-components==1.13.0
dash-html-components==1.1.1
dash-renderer==1.8.3
dash-table==4.11.0
defusedxml==0.6.0
dnspython==2.0.0
email-validator==1.1.1
Flask==1.1.2
Flask-AppBuilder==3.1.1
Flask-Babel==1.0.0
Flask-Compress==1.8.0
Flask-JWT-Extended==3.24.1
Flask-Limiter==1.4
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-Maintenance==0.0.1
Flask-OpenID==1.2.5
Flask-ReCaptcha==0.4.2
Flask-SQLAlchemy==2.4.4
Flask-WTF==0.14.3
future==0.18.2
idna==2.10
itsdangerous==1.1.0
Jinja2==2.11.2
jsonschema==3.2.0
limits==1.5.1
lxml==4.6.1
MarkupSafe==1.1.1
marshmallow==3.8.0
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.1
mysqlclient==2.0.1
numpy==1.19.4
oauthlib==3.1.0
onetimepass==1.0.1
pandas==1.1.4
pandas-datareader==0.9.0
pathlib==1.0.1
plotly==4.12.0
prison==0.1.3
PyJWT==1.7.1
PyQRCode==1.2.1
pyrsistent==0.17.3
python-dateutil==2.8.1
python-dotenv==0.14.0
python3-openid==3.2.0
pytz==2020.1
PyYAML==5.3.1
requests==2.24.0
requests-oauthlib==1.3.0
retrying==1.3.3
six==1.15.0
SQLAlchemy==1.3.19
SQLAlchemy-Utils==0.36.8
urllib3==1.25.10
Werkzeug==1.0.1
WTForms==2.3.3

### Describe the expected results

```python
Running the flask_appbuilder/tests without any error
```

### Describe the actual results

```pytb
ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: 'NoneType' object has no attribute 'drivername'

(No creation and initialization of the db causes all tests to fail)

Traceback (most recent call last):
  File "/home/username/.virtualenvs/venv/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 1020, in __call__
    return self.registry[key]
KeyError: 140584349521664

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/.virtualenvs/venv/lib/python3.8/site-packages/flask_appbuilder/security/sqla/manager.py", line 99, in create_db
    engine = self.get_session.get_bind(mapper=None, clause=None)
  File "/home/username/.virtualenvs/venv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/username/.virtualenvs/venv/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 1022, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/username/.virtualenvs/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3286, in __call__
    return self.class_(**local_kw)
  File "/home/username/.virtualenvs/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 138, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/username/.virtualenvs/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 943, in engine
    return self.get_engine()
  File "/home/username/.virtualenvs/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 962, in get_engine
    return connector.get_engine()
  File "/home/username/.virtualenvs/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 555, in get_engine
    options = self.get_options(sa_url, echo)
  File "/home/username/.virtualenvs/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 570, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/username/.virtualenvs/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 883, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'
```

### Steps to reproduce
1) startup Bash console on Pythonanywhere
2) workon virtualenvironment
3) copy ........site-packages/flask_appbuilder/test dir to /home/username/app/
4) cd /home/username/app
5) python -m unittest discover
--

Thanks!

**Comment by runoutnow** [comment]
I have changed config_api.py:
SQLALCHEMY_DATABASE_URI  is now pointing to an actual empty sqllite db instead of trying to get te URI from the environment variable... That variable isn't present here. Now the tests are running...
