### ISSUE TITLE
Okta Oauth - Fails with 'Response' object has no attribute 'data'

### ISSUE THREAD

**Issue by jonathonbattista** [dpgaspar/Flask-AppBuilder#1577]
We are trying to use Okta Oauth for Airflow authentication now that [PR-1571](https://github.com/dpgaspar/Flask-AppBuilder/pull/1571) has been merged and 3.2.0 released.

We are currently set up with Google Oauth and that is working perfectly.

### Environment

Flask-Appbuilder version: 3.2.0

pip freeze output: 
```
Flask-AppBuilder==3.2.0
Authlib==0.15.2
```

### Describe the expected results

Okta OAuth response should contain **data** attribute and authorize.

### Describe the actual results
OAuth response doesnt contain **data** and authorization fails.

```pytb
Retrieve temporary data: {'code': 'xxxx', 'state': 'xxxxxxx, 'redirect_uri': 'https://xxxxxx/oauth-authorized/okta'}                                                              
airflow-web [2021-02-26 20:46:32,146] {views.py:693} ERROR - Error returning OAuth user info: 'Response' object has no attribute 'data'
```

### Steps to reproduce
Configure FAB 3.2.0 to use Okta Oauth
```
# ----------------------------------------------------
# AUTHENTICATION CONFIG
# ----------------------------------------------------
# For details on how to set up each of the following authentication, see
# http://flask-appbuilder.readthedocs.io/en/latest/security.html# authentication-methods
# for details.

# The authentication type
AUTH_TYPE = AUTH_OAUTH

# Uncomment to setup Full admin role name
AUTH_ROLE_ADMIN = 'Admin'

# Uncomment to setup Public role name, no authentication needed
# AUTH_ROLE_PUBLIC = 'Public'

# Will allow user self registration
AUTH_USER_REGISTRATION = True

# The default user self registration role
AUTH_USER_REGISTRATION_ROLE = "Viewer"

# When using OAuth Auth, uncomment to setup provider(s) info
# Google OAuth example:
OAUTH_PROVIDERS = [{
    "name": "okta",
    "icon": "fa-circle-o",
    "token_key": "access_token",
    "remote_app": {
        "client_id": 'xxxxx',
        "client_secret": 'xxxxx',
        "api_base_url": "https://xxx.okta.com/oauth2/v1/",
        "client_kwargs": {"scope": "openid profile email groups"},
        "access_token_url": "https://xxx.okta.com/oauth2/v1/token",
        "authorize_url": "https://xxxx.okta.com/oauth2/v1/authorize",
    },
}]
```

**Comment by dpgaspar** [comment]
Can you double check your configuration settings, this seems like there may be an unauthorised response from OKTA that is not properly handled on FAB. Since `data` is required and expected

You can use the `oauth_user_info_getter` decorator and write your own: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/manager.py#L483. Using that you can dump to debug the OKTA response.

If you prefer probably easier with Airflow, write your own simple security class and plug using the config key: `FAB_SECURITY_MANAGER_CLASS` on your security manager class override `oauth_user_info`

``` python
from flask_appbuilder.security.sqla.manager import SecurityManager

class DebugSecurityManager(SecurityManager):
    oauth_user_info = debug_oauth_user_info

    def debug_oauth_user_info(self, provider, resp):
            me = self.appbuilder.sm.oauth_remotes[provider].get("userinfo")
            log.debug(f"response from OKTA {me}")
```
on config:
``` python
FAB_SECURITY_MANAGER_CLASS="my.path.DebugSecurityManager"

```

@thesuperzapper can you take a look?

**Comment by thesuperzapper** [comment]
@jonathonbattista its almost certainly an auth issue (e.g. wrong `token_key`/`client_id`/`client_secret`), but it also might be that you are requesting "groups" in `scope` (assuming you haven't set groups up in the Okta App)

I recommend doing what @dpgaspar said, and printing the response to see what sort of error is being returned in the response.

**Comment by thesuperzapper** [comment]
@dpgaspar we could probably improve [the docs](https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth) with reference to how to debug OAUTH responses, like you said.

**Comment by dpgaspar** [comment]
probably the security view for oauth needs an improvement also, `authorize_access_token` response

**Comment by jonathonbattista** [comment]
@dpgaspar I tried adding a custom security class for debugging, but I am running into 
```
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 37, in <module>
[2021-03-03 16:36:21,961] {cli_action_loggers.py:86} DEBUG - Calling callbacks: []
    args.func(args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 81, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/bin/cli.py", line 1179, in webserver
    app = cached_app_rbac(None) if settings.RBAC else cached_app(None)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www_rbac/app.py", line 297, in cached_app
    app, _ = create_app(config, session, testing)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www_rbac/app.py", line 115, in create_app
    update_perms=conf.getboolean('webserver', 'UPDATE_FAB_PERMS'))
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/base.py", line 148, in __init__
    self.init_app(app, session)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/base.py", line 209, in init_app
    self._add_admin_views()
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/base.py", line 316, in _add_admin_views
    self.sm.register_views()
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/security/sqla/manager.py", line 84, in register_views
    super(SecurityManager, self).register_views()
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/security/manager.py", line 713, in register_views
    category_label=_("Security"),
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/base.py", line 413, in add_view
    baseview = self._check_and_init(baseview)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/base.py", line 346, in _check_and_init
    baseview = baseview()
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/views.py", line 524, in __init__
    super(ModelView, self).__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/views.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/baseviews.py", line 803, in __init__
    super(BaseCRUDView, self).__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/baseviews.py", line 539, in __init__
    self._init_forms()
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/baseviews.py", line 826, in _init_forms
    super(BaseCRUDView, self)._init_forms()
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/baseviews.py", line 580, in _init_forms
    filter_rel_fields=self.search_form_query_rel_fields,
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/forms.py", line 317, in create_form
    form_props,
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/forms.py", line 265, in _convert_col
    col_name, label, description, lst_validators, form_props
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/forms.py", line 226, in _convert_simple
    form_props[col_name] = fc.convert()
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/forms.py", line 91, in convert
    if getattr(self.datamodel, type_marker)(self.colname):
AttributeError: 'SQLAInterface' object has no attribute 'is_utcdatetime'
```

**Comment by thesuperzapper** [comment]
@jonathonbattista please try extending from the `AirflowSecurityManager` instead of the default one:

```python
from airflow.www_rbac.security import AirflowSecurityManager

class DebugSecurityManager(AirflowSecurityManager):
    oauth_user_info = debug_oauth_user_info

    def debug_oauth_user_info(self, provider, resp):
            me = self.appbuilder.sm.oauth_remotes[provider].get("userinfo")
            log.debug(f"response from OKTA {me}")

SECURITY_MANAGER_CLASS = DebugSecurityManager
```

**Comment by jonathonbattista** [comment]
@thesuperzapper That worked, but brought up the following: 
```
[2021-03-04 15:04:14,870] {debug_security_manager.py:7} DEBUG - response from OKTA <Response [200]>
[2021-03-04 15:04:14,871] {app.py:1892} ERROR - Exception on /oauth-authorized/okta [GET]
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/security/views.py", line 710, in oauth_authorized
    user = self.appbuilder.sm.auth_user_oauth(userinfo)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/security/manager.py", line 1273, in auth_user_oauth
    if "username" in userinfo:
TypeError: argument of type 'NoneType' is not iterable
```

Should the response be the actual **userinfo** and not a **200 Status Code**?

**Comment by houqp** [comment]
@jonathonbattista it's expected to return a response object, could you change it to `me.data` or `me.json()`?

**Comment by houqp** [comment]
@jonathonbattista #1589 should fix the issue you are seeing
