### ISSUE TITLE
airflow 2.0.0 flaskappbuilder userinfogetter issue

### ISSUE THREAD

**Issue by HariAA** [dpgaspar/Flask-AppBuilder#1596]
Hi,

I am trying to implement Azure AD integration and authorization. I was able to set up the azure ad integration, but I am facing an issue with the authorization step.
As a first set step, I need to read additional info from the azure directory(group) which has the AD group for a user and i would like to use the group to decide the appropriate permission in the airflow webserver. I am trying to create a function in the webserver_config.py file to return a modified user info but I am facing an issue with the decorator.

I get the error "TypeError: oauth_user_info_getter() missing 1 required positional argument: 'f'"

The below code is what I have put for the user info getter.

from flask_appbuilder import BaseSecurityManager as smm
@smm.oauth_user_info_getter
def get_oauth_user_info(sm, provider, response=None):
    if provider == "azure":
        log.debug("Azure response received : {0}".format(resp))
        id_token = resp["id_token"]
        log.debug(str(id_token))
        me = self._azure_jwt_token_parse(id_token)
        #self.appbuilder.sm.oauth_remotes[provider].get("userinfo") 
        log.debug("Parse JWT token : {0}".format(me))
        return {
            "name": me["name"],
            "email": me["upn"],
            "first_name": me["given_name"],
            "last_name": me["family_name"],
            "id": me["oid"],
            "username": me["oid"],
            "role_keys": me["group"]
        }
    else:
        return {}
could someone please help me if you have used azure integration

**Comment by vigneshraaj** [comment]
Yes, I'm facing the same issue as well.
```
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/webserver_command.py", line 360, in webserver
    app = cached_app(None)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/www/app.py", line 145, in cached_app
    app = create_app(config=config, testing=testing)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/www/app.py", line 75, in create_app
    flask_app.config.from_pyfile(settings.WEBSERVER_CONFIG, silent=True)
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/config.py", line 132, in from_pyfile
    exec(compile(config_file.read(), filename, "exec"), d.__dict__)
  File "/opt/airflow/webserver_config.py", line 81, in <module>
    def my_user_info_getter(sm, provider, response=None):
TypeError: oauth_user_info_getter() missing 1 required positional argument: 'f'
```

**Comment by vigneshraaj** [comment]
@HariAA Here is a workaround (if interested). 

Create roles on the azure application add to `AUTH_ROLES_MAPPING`.

Add to `webserver_config.py`  File:
```
    class AzureRoleBasedSecurityManager(AirflowSecurityManager):
        def _get_oauth_user_info(self, provider, resp):
            if provider == "azure":
                me = self._azure_jwt_token_parse(resp["id_token"])
                return {
                    "id": me["oid"],
                    "username": me["upn"],
                    "name": me["name"],
                    "email": me["upn"],
                    "first_name": me["given_name"],
                    "last_name": me["family_name"],
                    "role_keys": me["roles"],
                }
            return {}
        oauth_user_info = _get_oauth_user_info

    SECURITY_MANAGER_CLASS = AzureRoleBasedSecurityManager

    AUTH_ROLES_MAPPING = {
        # For OAUTH
        "User": ["User"],
        "Admin": ["Admin"],
    }
```

**Comment by llsXuemengran** [comment]
> @HariAA Here is a workaround (if interested).
> 
> Create roles on the azure application add to `AUTH_ROLES_MAPPING`.
> 
> Add to `webserver_config.py` File:
> 
> ```
>     class AzureRoleBasedSecurityManager(AirflowSecurityManager):
>         def _get_oauth_user_info(self, provider, resp):
>             if provider == "azure":
>                 me = self._azure_jwt_token_parse(resp["id_token"])
>                 return {
>                     "id": me["oid"],
>                     "username": me["upn"],
>                     "name": me["name"],
>                     "email": me["upn"],
>                     "first_name": me["given_name"],
>                     "last_name": me["family_name"],
>                     "role_keys": me["roles"],
>                 }
>             return {}
>         oauth_user_info = _get_oauth_user_info
> 
>     SECURITY_MANAGER_CLASS = AzureRoleBasedSecurityManager
> 
>     AUTH_ROLES_MAPPING = {
>         # For OAUTH
>         "User": ["User"],
>         "Admin": ["Admin"],
>     }
> ```

solve my problem, thanks a lot !
