### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by dolphikcode** [dpgaspar/Flask-AppBuilder#1675]
### Environment

Flask-Appbuilder version: 3.3.2

pip freeze output:
apispec==3.3.2
attrs==21.2.0
Babel==2.9.1
click==7.1.2
colorama==0.4.4
defusedxml==0.7.1
dnspython==2.1.0
email-validator==1.1.3
Flask==1.1.4
Flask-AppBuilder==3.3.2
Flask-Babel==1.0.0
Flask-JWT-Extended==3.25.1
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.14.3
idna==3.2
itsdangerous==1.1.0
Jinja2==2.11.3
jsonschema==3.2.0
MarkupSafe==2.0.1
marshmallow==3.13.0
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.23.1
prison==0.1.3
PyJWT==1.7.1
pyrsistent==0.18.0
python-dateutil==2.8.2
python3-openid==3.2.0
pytz==2021.1
PyYAML==5.4.1
six==1.16.0
SQLAlchemy==1.3.24
SQLAlchemy-Utils==0.37.8
Werkzeug==1.0.1
WTForms==2.3.3

### Describe the expected results
I just created app by "flask fab create-app"
and added:

```
from flask import render_template
from flask_appbuilder.models.sqla.interface import SQLAInterface
from flask_appbuilder import ModelView, ModelRestApi
from flask_appbuilder import BaseView, expose
from flask_appbuilder.models.sqla.interface import SQLAInterface

from app import appbuilder
from flask import render_template, flash, session, url_for, redirect
from . import appbuilder, db

class HelloWorld(BaseView):
    """ This first view of the tutorial """
    route_base = "/hello"

    @expose("/")
    def hello(self):
        return "Hello, World! from Software Testing Help"

@appbuilder.app.errorhandler(404)
def page_not_found(e):
    return (
        render_template(
            "404.html", base_template=appbuilder.base_template, appbuilder=appbuilder
        ),
        404,
    )


db.create_all()
appbuilder.add_view(HelloWorld, "HelloWorld", category="Model Views")
```

### Describe the actual results

Tell us what happens instead.

```
(flaskAppbuildTesting) dolph@hapto:~/PycharmProjects/flaskAppbuildTesting$ flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
/home/dolph/.local/share/virtualenvs/flaskAppbuildTesting-h-PEt8Rq/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py:872: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  warnings.warn(FSADeprecationWarning(
2021-07-31 20:15:24,955:INFO:flask_appbuilder.base:Registering class IndexView on menu 
2021-07-31 20:15:24,955:INFO:flask_appbuilder.baseviews:Registering route / ('GET',)
2021-07-31 20:15:24,957:INFO:flask_appbuilder.base:Registering class UtilView on menu 
2021-07-31 20:15:24,957:INFO:flask_appbuilder.baseviews:Registering route /back ('GET',)
2021-07-31 20:15:24,958:INFO:flask_appbuilder.base:Registering class LocaleView on menu 
2021-07-31 20:15:24,959:INFO:flask_appbuilder.baseviews:Registering route /lang/<string:locale> ('GET',)
2021-07-31 20:15:24,960:INFO:flask_appbuilder.base:Registering class SecurityApi on menu 
2021-07-31 20:15:24,960:INFO:flask_appbuilder.api:Registering route /api/v1/security/login ['POST']
2021-07-31 20:15:24,960:INFO:flask_appbuilder.api:Registering route /api/v1/security/refresh ['POST']
2021-07-31 20:15:24,962:INFO:flask_appbuilder.base:Registering class ResetPasswordView on menu 
2021-07-31 20:15:24,963:INFO:flask_appbuilder.baseviews:Registering route /resetpassword/form ['GET']
2021-07-31 20:15:24,963:INFO:flask_appbuilder.baseviews:Registering route /resetpassword/form ['POST']
2021-07-31 20:15:24,970:INFO:flask_appbuilder.base:Registering class ResetMyPasswordView on menu 
2021-07-31 20:15:24,970:INFO:flask_appbuilder.baseviews:Registering route /resetmypassword/form ['GET']
2021-07-31 20:15:24,970:INFO:flask_appbuilder.baseviews:Registering route /resetmypassword/form ['POST']
2021-07-31 20:15:24,976:INFO:flask_appbuilder.base:Registering class UserInfoEditView on menu 
2021-07-31 20:15:24,976:INFO:flask_appbuilder.baseviews:Registering route /userinfoeditview/form ['GET']
2021-07-31 20:15:24,976:INFO:flask_appbuilder.baseviews:Registering route /userinfoeditview/form ['POST']
2021-07-31 20:15:24,980:INFO:flask_appbuilder.base:Registering class AuthDBView on menu 
2021-07-31 20:15:24,980:INFO:flask_appbuilder.baseviews:Registering route /login/ ['GET', 'POST']
2021-07-31 20:15:24,980:INFO:flask_appbuilder.baseviews:Registering route /logout/ ('GET',)
2021-07-31 20:15:24,985:INFO:flask_appbuilder.base:Registering class UserDBModelView on menu List Users
2021-07-31 20:15:24,985:INFO:flask_appbuilder.baseviews:Registering route /users/action/<string:name>/<pk> ['GET', 'POST']
2021-07-31 20:15:24,986:INFO:flask_appbuilder.baseviews:Registering route /users/action_post ['POST']
2021-07-31 20:15:24,986:INFO:flask_appbuilder.baseviews:Registering route /users/add ['GET', 'POST']
2021-07-31 20:15:24,986:INFO:flask_appbuilder.baseviews:Registering route /users/api ['GET']
2021-07-31 20:15:24,986:INFO:flask_appbuilder.baseviews:Registering route /users/api/column/add/<col_name> ['GET']
2021-07-31 20:15:24,986:INFO:flask_appbuilder.baseviews:Registering route /users/api/column/edit/<col_name> ['GET']
2021-07-31 20:15:24,986:INFO:flask_appbuilder.baseviews:Registering route /users/api/create ['POST']
2021-07-31 20:15:24,986:INFO:flask_appbuilder.baseviews:Registering route /users/api/delete/<pk> ['DELETE']
2021-07-31 20:15:24,986:INFO:flask_appbuilder.baseviews:Registering route /users/api/get/<pk> ['GET']
2021-07-31 20:15:24,986:INFO:flask_appbuilder.baseviews:Registering route /users/api/read ['GET']
2021-07-31 20:15:24,986:INFO:flask_appbuilder.baseviews:Registering route /users/api/readvalues ['GET']
2021-07-31 20:15:24,986:INFO:flask_appbuilder.baseviews:Registering route /users/api/update/<pk> ['PUT']
2021-07-31 20:15:24,986:INFO:flask_appbuilder.baseviews:Registering route /users/delete/<pk> ['GET', 'POST']
2021-07-31 20:15:24,986:INFO:flask_appbuilder.baseviews:Registering route /users/download/<string:filename> ('GET',)
2021-07-31 20:15:24,986:INFO:flask_appbuilder.baseviews:Registering route /users/edit/<pk> ['GET', 'POST']
2021-07-31 20:15:24,986:INFO:flask_appbuilder.baseviews:Registering route /users/list/ ('GET',)
2021-07-31 20:15:24,987:INFO:flask_appbuilder.baseviews:Registering route /users/show/<pk> ['GET']
2021-07-31 20:15:24,987:INFO:flask_appbuilder.baseviews:Registering route /users/userinfo/ ('GET',)
2021-07-31 20:15:25,016:INFO:flask_appbuilder.base:Registering class RoleModelView on menu List Roles
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/action/<string:name>/<pk> ['GET', 'POST']
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/action_post ['POST']
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/add ['GET', 'POST']
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/api ['GET']
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/api/column/add/<col_name> ['GET']
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/api/column/edit/<col_name> ['GET']
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/api/create ['POST']
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/api/delete/<pk> ['DELETE']
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/api/get/<pk> ['GET']
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/api/read ['GET']
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/api/readvalues ['GET']
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/api/update/<pk> ['PUT']
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/delete/<pk> ['GET', 'POST']
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/download/<string:filename> ('GET',)
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/edit/<pk> ['GET', 'POST']
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/list/ ('GET',)
2021-07-31 20:15:25,017:INFO:flask_appbuilder.baseviews:Registering route /roles/show/<pk> ['GET']
2021-07-31 20:15:25,048:INFO:flask_appbuilder.base:Registering class UserStatsChartView on menu User's Statistics
2021-07-31 20:15:25,048:INFO:flask_appbuilder.baseviews:Registering route /userstatschartview/chart/ ('GET',)
2021-07-31 20:15:25,048:INFO:flask_appbuilder.baseviews:Registering route /userstatschartview/chart/<group_by> ('GET',)
2021-07-31 20:15:25,058:INFO:flask_appbuilder.base:Registering class PermissionModelView on menu Base Permissions
2021-07-31 20:15:25,059:INFO:flask_appbuilder.baseviews:Registering route /permissions/action/<string:name>/<pk> ['GET', 'POST']
2021-07-31 20:15:25,059:INFO:flask_appbuilder.baseviews:Registering route /permissions/action_post ['POST']
2021-07-31 20:15:25,059:INFO:flask_appbuilder.baseviews:Registering route /permissions/add ['GET', 'POST']
2021-07-31 20:15:25,059:INFO:flask_appbuilder.baseviews:Registering route /permissions/api ['GET']
2021-07-31 20:15:25,059:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/column/add/<col_name> ['GET']
2021-07-31 20:15:25,059:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/column/edit/<col_name> ['GET']
2021-07-31 20:15:25,059:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/create ['POST']
2021-07-31 20:15:25,059:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/delete/<pk> ['DELETE']
2021-07-31 20:15:25,059:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/get/<pk> ['GET']
2021-07-31 20:15:25,059:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/read ['GET']
2021-07-31 20:15:25,059:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/readvalues ['GET']
2021-07-31 20:15:25,059:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/update/<pk> ['PUT']
2021-07-31 20:15:25,059:INFO:flask_appbuilder.baseviews:Registering route /permissions/delete/<pk> ['GET', 'POST']
2021-07-31 20:15:25,059:INFO:flask_appbuilder.baseviews:Registering route /permissions/download/<string:filename> ('GET',)
2021-07-31 20:15:25,059:INFO:flask_appbuilder.baseviews:Registering route /permissions/edit/<pk> ['GET', 'POST']
2021-07-31 20:15:25,060:INFO:flask_appbuilder.baseviews:Registering route /permissions/list/ ('GET',)
2021-07-31 20:15:25,060:INFO:flask_appbuilder.baseviews:Registering route /permissions/show/<pk> ['GET']
2021-07-31 20:15:25,083:INFO:flask_appbuilder.base:Registering class ViewMenuModelView on menu Views/Menus
2021-07-31 20:15:25,084:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/action/<string:name>/<pk> ['GET', 'POST']
2021-07-31 20:15:25,084:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/action_post ['POST']
2021-07-31 20:15:25,084:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/add ['GET', 'POST']
2021-07-31 20:15:25,084:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api ['GET']
2021-07-31 20:15:25,084:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/column/add/<col_name> ['GET']
2021-07-31 20:15:25,084:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/column/edit/<col_name> ['GET']
2021-07-31 20:15:25,084:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/create ['POST']
2021-07-31 20:15:25,084:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/delete/<pk> ['DELETE']
2021-07-31 20:15:25,084:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/get/<pk> ['GET']
2021-07-31 20:15:25,084:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/read ['GET']
2021-07-31 20:15:25,084:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/readvalues ['GET']
2021-07-31 20:15:25,084:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/update/<pk> ['PUT']
2021-07-31 20:15:25,084:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/delete/<pk> ['GET', 'POST']
2021-07-31 20:15:25,084:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/download/<string:filename> ('GET',)
2021-07-31 20:15:25,084:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/edit/<pk> ['GET', 'POST']
2021-07-31 20:15:25,085:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/list/ ('GET',)
2021-07-31 20:15:25,085:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/show/<pk> ['GET']
2021-07-31 20:15:25,112:INFO:flask_appbuilder.base:Registering class PermissionViewModelView on menu Permission on Views/Menus
2021-07-31 20:15:25,112:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/action/<string:name>/<pk> ['GET', 'POST']
2021-07-31 20:15:25,112:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/action_post ['POST']
2021-07-31 20:15:25,113:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/add ['GET', 'POST']
2021-07-31 20:15:25,113:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api ['GET']
2021-07-31 20:15:25,113:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/column/add/<col_name> ['GET']
2021-07-31 20:15:25,113:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/column/edit/<col_name> ['GET']
2021-07-31 20:15:25,113:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/create ['POST']
2021-07-31 20:15:25,113:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/delete/<pk> ['DELETE']
2021-07-31 20:15:25,113:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/get/<pk> ['GET']
2021-07-31 20:15:25,113:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/read ['GET']
2021-07-31 20:15:25,113:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/readvalues ['GET']
2021-07-31 20:15:25,113:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/update/<pk> ['PUT']
2021-07-31 20:15:25,113:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/delete/<pk> ['GET', 'POST']
2021-07-31 20:15:25,113:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/download/<string:filename> ('GET',)
2021-07-31 20:15:25,113:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/edit/<pk> ['GET', 'POST']
2021-07-31 20:15:25,113:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/list/ ('GET',)
2021-07-31 20:15:25,113:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/show/<pk> ['GET']
2021-07-31 20:15:25,138:INFO:flask_appbuilder.base:Registering class MenuApi on menu 
2021-07-31 20:15:25,139:INFO:flask_appbuilder.api:Registering route /api/v1/menu/ ['GET']
2021-07-31 20:15:25,170:INFO:flask_appbuilder.base:Registering class HelloWorld on menu HelloWorld
2021-07-31 20:15:25,170:INFO:flask_appbuilder.baseviews:Registering route /hello/ ('GET',)
2021-07-31 20:15:25,177:WARNING:flask_appbuilder.security.sqla.manager:Refused to delete permission view, assoc with role exists HelloWorld.menu_access Admin
2021-07-31 20:15:25,183:INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-07-31 20:15:33,510:ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/home/dolph/.local/share/virtualenvs/flaskAppbuildTesting-h-PEt8Rq/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dolph/.local/share/virtualenvs/flaskAppbuildTesting-h-PEt8Rq/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dolph/.local/share/virtualenvs/flaskAppbuildTesting-h-PEt8Rq/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dolph/.local/share/virtualenvs/flaskAppbuildTesting-h-PEt8Rq/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dolph/.local/share/virtualenvs/flaskAppbuildTesting-h-PEt8Rq/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dolph/.local/share/virtualenvs/flaskAppbuildTesting-h-PEt8Rq/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dolph/.local/share/virtualenvs/flaskAppbuildTesting-h-PEt8Rq/lib/python3.9/site-packages/flask_appbuilder/views.py", line 41, in index
    return self.render_template(self.index_template, appbuilder=self.appbuilder)
  File "/home/dolph/.local/share/virtualenvs/flaskAppbuildTesting-h-PEt8Rq/lib/python3.9/site-packages/flask_appbuilder/baseviews.py", line 287, in render_template
    return render_template(
  File "/home/dolph/.local/share/virtualenvs/flaskAppbuildTesting-h-PEt8Rq/lib/python3.9/site-packages/flask/templating.py", line 136, in render_template
    ctx.app.update_template_context(context)
  File "/home/dolph/.local/share/virtualenvs/flaskAppbuildTesting-h-PEt8Rq/lib/python3.9/site-packages/flask/app.py", line 838, in update_template_context
    context.update(func())
  File "/home/dolph/.local/share/virtualenvs/flaskAppbuildTesting-h-PEt8Rq/lib/python3.9/site-packages/flask_login/utils.py", line 368, in _user_context_processor
    return dict(current_user=_get_user())
  File "/home/dolph/.local/share/virtualenvs/flaskAppbuildTesting-h-PEt8Rq/lib/python3.9/site-packages/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/home/dolph/.local/share/virtualenvs/flaskAppbuildTesting-h-PEt8Rq/lib/python3.9/site-packages/flask_login/login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "/home/dolph/.local/share/virtualenvs/flaskAppbuildTesting-h-PEt8Rq/lib/python3.9/site-packages/flask_login/login_manager.py", line 321, in reload_user
    user = self.user_callback(user_id)
  File "/home/dolph/.local/share/virtualenvs/flaskAppbuildTesting-h-PEt8Rq/lib/python3.9/site-packages/flask_appbuilder/security/manager.py", line 2007, in load_user
    return self.get_user_by_id(int(pk))
ValueError: invalid literal for int() with base 10: '61003340e520999a1d41db66'

```

**Comment by dpgaspar** [comment]
Not able to replicate, but is it possible you were experimenting with MongoDB first and still have a session cookie associated with that user first?

So, clean your cookies and try again.

Also:
``` python
class HelloWorld(BaseView):
    """ This first view of the tutorial """
    route_base = "/hello"
    default_view = "hello"

    @expose("/")
    def hello(self):
        return "Hello, World! from Software Testing Help"
```

missing `default_view`

Good luck!
