### ISSUE TITLE
Overriding Role security model relation error

### ISSUE THREAD

**Issue by jvinolas** [dpgaspar/Flask-AppBuilder#171]
I need to add fields to Role security model so I did it like in User model example. The problem is that there is the permission relation that is not @declared_attr in Role model:

```
permissions = relationship('PermissionView', secondary=assoc_permissionview_role, backref='role')
```

so I can't implement that as I did in User model. The error comes when Fabmanager create-admin tries to add default 'admin' user:

```
ERROR:flask_appbuilder.security.sqla.manager:Error adding new user to database. Attempting to flush an item of type <class 'app.security.security_models.MyRole'> as a member of collection "User.roles". Expected an object of type <class 'flask_appbuilder.security.sqla.models.Role'> or a polymorphic subclass of this type. If <class 'app.security.security_models.MyRole'> is a subclass of <class 'flask_appbuilder.security.sqla.models.Role'>, configure mapper "Mapper|Role|ab_role" to load this subtype polymorphically, or set enable_typechecks=False to allow any subtype to be accepted for flush. 
```

Is that the problem or there is another way of implementing MyRole?

This is what I've done. First I subclassed the Role model with my new fields:

```
class MyRole(Role):
    quota_v = Column(Integer)
    quota_r = Column(Integer)
    quota_t = Column(Integer)
```

Then  the view:

```
class MyRoleModelView(RoleModelView):
    route_base = '/roles'

    list_title = lazy_gettext('List Roles')
    show_title = lazy_gettext('Show Role')
    add_title = lazy_gettext('Add Role')
    edit_title = lazy_gettext('Edit Role')

    label_columns = {'name': lazy_gettext('Name'), 'permissions': lazy_gettext('Permissions')}
    list_columns = ['name', 'permissions','quota_vm','quota_run','quota_tmpl']
    show_columns = ['name', 'permissions']
    order_columns = ['name']
    search_columns = ['name']
```

And overrided in security.py:

```
class MySecurityManager(SecurityManager):
    user_model = MyUser
    userdbmodelview = MyUserDBModelView
    role_model = MyRole
    rolemodelview = MyRoleModelView
    userldapmodelview = MyUserLDAPModelView
```

**Comment by dpgaspar** [comment]
Can you create the user using the GUI?

**Comment by jvinolas** [comment]
Ok, I found the problem. I could add it from the GUI so I found that I was calling self.find_role that returned a MyRole object, but the backend wants a Role object. As I need this only on LDAP login to append different roles to users, I just overrided find_role to return a Role object:
```
	def find_role(self, name):
		return self.get_session.query(Role).filter_by(name=name).first()
```
But I still don't understand why I can't use a MyRole object for user.roles.append(MyRole). Anyway it works with a Role object.

**Comment by jvinolas** [comment]
The last thing I had to do is create another relation between MyRoles and MyUsers. That is because the roles relation is not shared among MyUser class:

```
class User(Model):
    __tablename__ = 'ab_user'
    roles = relationship('Role', secondary=assoc_user_role, backref='user')
```
So I had to add my own relation to my subclass models:

```
from flask_appbuilder.security.sqla.models import User, Role, assoc_user_role
class MyUser(User):
	myroles = relationship('MyRole', secondary=assoc_user_role, backref='myuser')
```
Because without that relation that is not shared from User model I got this error when I tried to show or edit a role: (appbuilder tries to get related view relation name and can't find it)
```
2015-05-20 09:14:59,828:ERROR:app:Exception on /roles/edit/3 [GET]
Traceback (most recent call last):
  File "/opt/dovirt/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/dovirt/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/dovirt/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/dovirt/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/dovirt/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/dovirt/env/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 27, in wraps
    return f(self, *args, **kwargs)
  File "/opt/dovirt/env/lib/python2.7/site-packages/flask_appbuilder/views.py", line 513, in edit
    widgets = self._edit(pk)
  File "/opt/dovirt/env/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 852, in _edit
    orders=orders, pages=pages, page_sizes=page_sizes, widgets=widgets)
  File "/opt/dovirt/env/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 660, in _get_related_views_widgets
    view.__class__.__name__)))
  File "/opt/dovirt/env/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 634, in _get_related_view_widget
    log.error("Can't find relation on related view {0}".format(related_view.name))
AttributeError: 'MyUserDBModelView' object has no attribute 'name'
```
I still think that role relation must be @declared_attr to avoid having to create my own relation between MyUser and MyRole models.

**Comment by dpgaspar** [comment]
Hello, sorry for the delay, 

You really can and i have created the properties to override Role model and view, but this is not documented and it has not been tested. 

That being said, for using a @declared_attr i have to make sure that i can have the same functionality for mongoDB (the framework supports both).

Can you share what is your idea in doing this?

**Comment by jvinolas** [comment]
I realized that I didn't really need to override Role model. I need to apply quotas to Roles and I thought about adding those quota fields to Role model definition. But I don't need it anymore because I moved those quotas to tables and a roles relation so I can share a quota with the roles I need.

But I think it will not be possible to add fields to MyRole without adding the relation in your own MyUser model as I said in previous post.

**Comment by MichaelPereira** [comment]
Just wanted to contribute that I had the same `AttributeError: 'MyUserDBModelView' object has no attribute 'name'` when using an [association object](http://docs.sqlalchemy.org/en/rel_1_0/orm/basic_relationships.html#association-object) between my custom user model `MyUser` and a `Group` model.

```python
class UserGroupAssociation(Model):
    group_id = Column('group_id', INTEGER, ForeignKey('group.id'), primary_key=True)
    user_id = Column('user_id', INTEGER, ForeignKey('ab_user.id'), primary_key=True)
    group = relationship("Group", back_populates="users")
    user = relationship('MyUser', back_populates="groups")


class MyUser(User):
    __tablename__ = 'ab_user'
    groups = relationship('UserGroupAssociation', back_populates='user')

    def __repr__(self):
        return self.username


class Group(Model):
    __tablename__ = 'group'
    id = Column('id', INTEGER(unsigned=True), primary_key=True)
    name = Column('name', String(length=256))
    users = relationship('UserGroupAssociation', back_populates='group')

    def __repr__(self):
        return self.name

```

Once I switched to an [association table](http://docs.sqlalchemy.org/en/rel_1_0/orm/basic_relationships.html#many-to-many), the problem went away and I was able to use `MyUserDBModelView` as a related view:

```python
assoc_group_user = Table('user_group', Model.metadata,
                        Column('id', Integer, primary_key=True),
                        Column('user_id', Integer, ForeignKey('ab_user.id')),
                        Column('group_id', Integer, ForeignKey('group.id')))


class MyUser(User):
    __tablename__ = 'ab_user'
    groups = relationship('Group', secondary=assoc_group_user, backref='users')

    def __repr__(self):
        return self.username


class Group(Model):
    __tablename__ = 'group'
    id = Column('id', INTEGER(unsigned=True), primary_key=True)
    name = Column('name', String(length=256))

    def __repr__(self):
        return self.name
```
