### ISSUE TITLE
ModuleNotFoundError: No module named 'wtforms.compat' with WTForms 3.0.0

### ISSUE THREAD

**Issue by jiyongjung0** [dpgaspar/Flask-AppBuilder#1732]
It seems like the recent WTForms 3.0.0 dropped "compat" module in it. But flask-appbuilder is depending on it.

### Environment

Flask-Appbuilder version: 3.3.4

pip freeze output:
```
$ pip freeze
apispec==3.3.2
attrs==21.2.0
Babel==2.9.1
click==7.1.2
colorama==0.4.4
defusedxml==0.7.1
dnspython==2.1.0
email-validator==1.1.3
Flask==1.1.4
Flask-AppBuilder==3.3.4
Flask-Babel==2.0.0
Flask-JWT-Extended==3.25.1
Flask-Login==0.4.1
Flask-OpenID==1.3.0
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.14.3
idna==3.3
importlib-metadata==4.8.1
itsdangerous==1.1.0
Jinja2==2.11.3
jsonschema==3.2.0
MarkupSafe==2.0.1
marshmallow==3.14.0
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.26.1
prison==0.2.1
PyJWT==1.7.1
pyrsistent==0.18.0
python-dateutil==2.8.2
python3-openid==3.2.0
pytz==2021.3
PyYAML==6.0
six==1.16.0
SQLAlchemy==1.3.24
SQLAlchemy-Utils==0.37.9
typing-extensions==3.10.0.2
Werkzeug==1.0.1
WTForms==3.0.0
zipp==3.6.0
```

### Describe the expected results

Tell us what should happen.

We should be able to import flask_appbuilder module.
```python
$ pip install flask-appbuilder
...
$ python
>>> import flask_appbuilder
```

### Describe the actual results

Tell us what happens instead.
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jiyongjung/.pyenv/versions/t20211108/lib/python3.7/site-packages/flask_appbuilder/__init__.py", line 6, in <module>
    from .base import AppBuilder  # noqa: F401
  File "/home/jiyongjung/.pyenv/versions/t20211108/lib/python3.7/site-packages/flask_appbuilder/base.py", line 8, in <module>
    from .api.manager import OpenApiManager
  File "/home/jiyongjung/.pyenv/versions/t20211108/lib/python3.7/site-packages/flask_appbuilder/api/manager.py", line 8, in <module>
    from flask_appbuilder.baseviews import BaseView
  File "/home/jiyongjung/.pyenv/versions/t20211108/lib/python3.7/site-packages/flask_appbuilder/baseviews.py", line 21, in <module>
    from .forms import GeneralModelConverter
  File "/home/jiyongjung/.pyenv/versions/t20211108/lib/python3.7/site-packages/flask_appbuilder/forms.py", line 16, in <module>
    from .fields import EnumField, QuerySelectField, QuerySelectMultipleField
  File "/home/jiyongjung/.pyenv/versions/t20211108/lib/python3.7/site-packages/flask_appbuilder/fields.py", line 6, in <module>
    from wtforms.compat import string_types, text_type
ModuleNotFoundError: No module named 'wtforms.compat'
```

### Steps to reproduce
(Described above.)

**Comment by shawnzhu** [comment]
the source of change: https://github.com/wtforms/wtforms/pull/554

looks like it's will be simple fix in FAB since it already supports Python 3.6+ via #1097
