### ISSUE TITLE
Is using SQLAlchemy TypeDecorators supported?

### ISSUE THREAD

**Issue by ItWazzntMe** [dpgaspar/Flask-AppBuilder#186]
I see you're using it for the FileColumn mixin, but I get errors when I tried to implement my own:

``` python
class LowerCaseString(types.TypeDecorator):
    impl = types.String

    def process_bind_param(self, value, dialect):
        return value.lower()
```

and I'm using it like this:

``` python
class Device(Model):
    __table_args__ = (UniqueConstraint('name', 'site_id'),)
    id = Column(Integer, primary_key=True)
    name = Column(LowerCaseString(64), nullable=False)
    description = Column(String(255))
    site_id = Column(Integer, ForeignKey('site.id'))
    site = relationship("Site")
    alias_id = Column(Integer, ForeignKey('device.id'))
    alias = relationship("Device")
    devicetype_id = Column(Integer, ForeignKey("device_type.id"))
    devicetype = relationship("DeviceType")

    def __repr__(self):
        return self.name
```

Then I get this in the log:

```
2015-06-30 13:27:40,489:WARNING:flask_appbuilder.models.filters:Filter type not supported for column: name
2015-06-30 13:27:40,490:WARNING:flask_appbuilder.models.filters:Filter type not supported for column: name
2015-06-30 13:27:40,491:ERROR:flask_appbuilder.forms:Column name Type not supported
2015-06-30 13:27:40,491:ERROR:flask_appbuilder.forms:Column name Type not supported
2015-06-30 13:27:40,492:ERROR:flask_appbuilder.forms:Column name Type not supported
```

And this traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/views.py", line 361, in list
    widgets=widgets)
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 155, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 19, in block "body"
    {% block content %}
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 7, in block "content"
    {% block list_search scoped %}
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 8, in block "list_search"
    {% call lib.accordion_tag("accordion1",_("Search"), False) %}
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/lib.html", line 228, in template
    {{ caller() }}
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 9, in template
    {{ widgets.get('search')()|safe }}
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/widgets.py", line 107, in __call__
    label_columns[col] = as_unicode(self.template_args['form'][col].label.text)
  File "/usr/lib/python2.7/site-packages/wtforms/form.py", line 65, in __getitem__
    return self._fields[name]
KeyError: 'name'
```

Is there anything else I can/should do?

Thanks!

**Comment by dpgaspar** [comment]
I've pushed an example for this issue: https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/issue_186

It's the current best way to use SQLA TypeDecorators, still does not work with search form (i'll take a look at that) but everything else can be easily modified to map the custom type with WTForms.

**Comment by ItWazzntMe** [comment]
Thank you. I'll get it a shot!

Awesome project by the way. Thanks!

**Comment by dpgaspar** [comment]
Based on the pushed example, there is still a simpler but a bit hackish way, on views you can do it like this:

``` python
import sqlalchemy as sa
from flask.ext.appbuilder.models.sqla.interface import SQLAInterface
from flask.ext.appbuilder import ModelView
from flask.ext.appbuilder.fieldwidgets import BS3TextFieldWidget
from flask.ext.babelpkg import gettext
from flask.ext.appbuilder.models.sqla.filters import BaseFilter
from flask.ext.babelpkg import lazy_gettext
from app import appbuilder, db
from wtforms.fields import TextField
from .models import Device, Site, DeviceType, LowerCaseString


class MySQLAInterface(SQLAInterface):
    def is_string(self, col_name):
        try:
            return (isinstance(self.list_columns[col_name].type, sa.types.String) or
                    isinstance(self.list_columns[col_name].type, LowerCaseString))
        except:
            return False

class SiteModelView(ModelView):
    datamodel = SQLAInterface(Site)


class DeviceTypeModelView(ModelView):
    datamodel = SQLAInterface(DeviceType)


class DeviceModelView(ModelView):
    datamodel = MySQLAInterface(Device)
    
db.create_all()

appbuilder.add_view(SiteModelView, "Site", icon="fa-folder-open-o", category="Management", category_icon='fa-envelope')
appbuilder.add_view(DeviceTypeModelView, "DeviceType", icon="fa-folder-open-o", category="Management", category_icon='fa-envelope')
appbuilder.add_view(DeviceModelView, "Devices", icon="fa-folder-open-o", category="Management", category_icon='fa-envelope')


```

**Comment by ItWazzntMe** [comment]
Ah, that is a pretty easy approach, and it works. for me.

While we're on the subject of TypeDecorators, I'm also trying to implement this:
```python
class MACAddress(types.TypeDecorator):
    impl = types.CHAR

    def process_bind_param(self, value, dialect):
        return value.lower().replace('-', '').replace(':', '')

    def process_result_value(self, value, dialect):
        if value == "":
            return ""
        return ':'.join(value[i:i+2] for i in range(0, 12, 2))

class Nic(Model):
    __table_args__ = (UniqueConstraint('device_id', 'nictype_id'),)
    id = Column(Integer, primary_key=True)
    device_id = Column(Integer, ForeignKey('device.id'))
    device = relationship("Device")
    nictype_id = Column(Integer, ForeignKey('nic_type.id'))
    nictype = relationship("NicType")
    macaddress = Column(MACAddress(12), unique=True, nullable=True)
    usedhcp = Column(Boolean, default=True)
    ipaddresses = relationship('IpAddress', secondary=assoc_ip_addresses_nic, backref='nic')

    def __repr__(self):
        return ':'.join(self.macaddress[i:i+2] for i in range(0, 12, 2))
```

Basically I want to store the MAC address with the smallest size field necessary, but be able to display  and input it using optional delimiters. With the code above display of the field works as expected, but when I try to input data, I get a validation error saying that my string is more than 12 characters.

I also want to do a similar thing with IPv4 Addresses--store them as integers, but be able to work with them in octal/text form.

What's the best way to handle these types of fields where I want to pre-and-post process the data for input and display?

**Comment by dpgaspar** [comment]
You can create you own WTF form and associate it to your ModelView using add_form or edit_form. Create your own validations also. This will overcome the field length validation.

**Comment by ItWazzntMe** [comment]
I'm trying to create my own WTF forms, but I'm getting stuck on how to create the form so that related objects show up as select fields. For example, how do I create the form so that nictype in my example code shows up as a selectable list?

**Comment by ItWazzntMe** [comment]
Okay. After studying the code for a lot longer, I found a method that works out for me, though it is based on the hackish example you gave earlier.

```python
from wtforms.validators import MacAddress

class MySQLAInterface(SQLAInterface):
    def is_string(self, col_name):
        try:
            return (isinstance(self.list_columns[col_name].type, sa.types.String) or
                    isinstance(self.list_columns[col_name].type, LowerCaseString) or
                    isinstance(self.list_columns[col_name].type, MACAddress))
        except:
            return False
    def get_max_length(self, col_name):
        try:
            if isinstance(self.list_columns[col_name].type, MACAddress):
                return 17
            else:
                return super(MySQLAInterface, self).get_max_length(col_name)
        except:
                return -1

class NicView(ModelView):
    datamodel = MySQLAInterface(Nic)
    label_columns = {'nictype': "NIC Type",
                     'macaddress': "MAC Address",
                     'usedhcp': "Generate DHCP",
                     'ipaddresses': 'IP Addresses'}
    add_columns = ['device', 'nictype', 'macaddress', 'usedhcp']
    edit_columns = ['device', 'nictype', 'macaddress', 'usedhcp']
    list_columns = ['nictype', 'macaddress', 'usedhcp', 'ipaddresses']
    show_columns = ['device', 'nictype', 'macaddress', 'usedhcp', 'ipaddresses']
    validators_columns = { 'macaddress': [ MacAddress() ] }
```

**Comment by mmichaels01** [comment]
I know this issue is very dated at this point, but has any thing changed regarding approach for this type of issue since the last post?

I'm trying to solve a similar problem using UUID columns.

**Comment by dpgaspar** [comment]
Well looks like that support for this is coming soon, thanks to @jgao54 take a look at: #694
