### ISSUE TITLE
test failures

### ISSUE THREAD

**Issue by jnahmias** [dpgaspar/Flask-AppBuilder#1876]
Hello,
I am working on packaging FAB for the Debian GNU/Linux distribution. As part of the build process, I am running the testsuite directly with nose using the sqlite backend and am seeing quite a few errors. I am seeing those same sorts of errors even when I run it using tox:

```
$ cd /dev/shm
$ rm -rf flask-appbuilder
$ git clone https://github.com/dpgaspar/flask-appbuilder/
Cloning into 'flask-appbuilder'...
remote: Enumerating objects: 32498, done.
remote: Counting objects: 100% (441/441), done.
remote: Compressing objects: 100% (277/277), done.
remote: Total 32498 (delta 249), reused 311 (delta 156), pack-reused 32057
Receiving objects: 100% (32498/32498), 41.86 MiB | 8.00 MiB/s, done.
Resolving deltas: 100% (21582/21582), done.
$ cd flask-appbuilder
$ tox -e api-sqlite
GLOB sdist-make: /dev/shm/flask-appbuilder/setup.py
api-sqlite create: /dev/shm/flask-appbuilder/.tox/api-sqlite
api-sqlite installdeps: -rrequirements.txt, -rrequirements-dev.txt
api-sqlite inst: /dev/shm/flask-appbuilder/.tox/.tmp/package/1/Flask-AppBuilder-4.1.2.zip
api-sqlite installed: apispec==3.3.2,appdirs==1.4.4,attrs==21.4.0,Babel==2.9.1,black==19.3b0,click==8.0.4,colorama==0.4.4,coverage==5.5,distlib==0.3.4,dnspython==2.2.1,email-validator==1.1.3,filelock==3.7.1,flake8==3.9.2,flake8-import-order==0.18.1,Flask==2.0.3,Flask-AppBuilder @ file:///dev/shm/flask-appbuilder/.tox/.tmp/package/1/Flask-AppBuilder-4.1.2.zip,Flask-Babel==2.0.0,Flask-JWT-Extended==4.3.1,Flask-Login==0.6.0,Flask-SQLAlchemy==2.5.1,Flask-WTF==0.15.1,freezegun==1.2.1,funcparserlib==0.3.6,greenlet==1.1.2,idna==3.3,itsdangerous==2.1.1,Jinja2==3.0.3,jmespath==0.9.5,jsonschema==3.2.0,MarkupSafe==2.1.1,marshmallow==3.15.0,marshmallow-enum==1.5.1,marshmallow-sqlalchemy==0.26.1,mccabe==0.6.1,mockldap==0.3.0.post1,mypy==0.910,mypy-extensions==0.4.3,nose==1.3.7,packaging==21.3,parameterized==0.8.1,pep517==0.12.0,pip-tools==6.2.0,platformdirs==2.5.2,pluggy==1.0.0,prison==0.2.1,py==1.11.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycodestyle==2.7.0,pyflakes==2.3.1,PyJWT==2.3.0,pyparsing==3.0.8,pyrsistent==0.18.1,python-dateutil==2.8.2,python-ldap==3.4.0,pytz==2021.1,PyYAML==5.4.1,six==1.16.0,SQLAlchemy==1.4.29,SQLAlchemy-Utils==0.37.8,toml==0.10.2,tomli==2.0.1,tox==3.24.3,typing-extensions==4.2.0,virtualenv==20.15.1,Werkzeug==2.0.3,WTForms==2.3.3
api-sqlite run-test-pre: PYTHONHASHSEED='2386552346'
api-sqlite run-test: commands[0] | nosetests --stop -v --with-coverage --cover-package=flask_appbuilder flask_appbuilder.tests '--ignore-files=test_mongoengine\.py'
test_create_admin (flask_appbuilder.tests.A_fixture.test_0_fixture.TestData) ... ok
test_create_ro_user (flask_appbuilder.tests.A_fixture.test_0_fixture.TestData) ... ok
test_data (flask_appbuilder.tests.A_fixture.test_0_fixture.TestData) ... ok
LDAP: test `_search_ldap` method ... ok
LDAP: test `_search_ldap` method (with AUTH_LDAP_SEARCH_FILTER) ... ok
LDAP: test `_search_ldap` method w/returned search referrals ... ok
LDAP: test login flow for - direct bind - registered user ... FAIL

======================================================================
FAIL: LDAP: test login flow for - direct bind - registered user
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/flask-appbuilder/flask_appbuilder/tests/security/test_auth_ldap.py", line 536, in test__direct_bind__registered
    self.assertOnlyDefaultUsers()
  File "/dev/shm/flask-appbuilder/flask_appbuilder/tests/security/test_auth_ldap.py", line 80, in assertOnlyDefaultUsers
    self.assertEqual(user_names, [USERNAME_ADMIN, USERNAME_READONLY])
AssertionError: Lists differ: [] != ['testadmin', 'readonly']

Second list contains 2 additional elements.
First extra element 0:
'testadmin'

- []
+ ['testadmin', 'readonly']
-------------------- >> begin captured logging << --------------------
flask_appbuilder.security.sqla.manager: INFO: Security DB not found Creating all Models from Base
flask_appbuilder.security.sqla.manager: INFO: Security DB Created
flask_appbuilder.security.sqla.manager: INFO: Inserted Role: Admin
flask_appbuilder.security.sqla.manager: INFO: Inserted Role: Public
flask_appbuilder.security.manager: WARNING: No user yet created, use flask fab command to do it.
flask_appbuilder.base: INFO: Registering class IndexView on menu 
flask_appbuilder.baseviews: INFO: Registering route / ('GET',)
flask_appbuilder.base: INFO: Registering class UtilView on menu 
flask_appbuilder.baseviews: INFO: Registering route /back ('GET',)
flask_appbuilder.base: INFO: Registering class LocaleView on menu 
flask_appbuilder.baseviews: INFO: Registering route /lang/<string:locale> ('GET',)
flask_appbuilder.base: INFO: Registering class SecurityApi on menu 
flask_appbuilder.api: INFO: Registering route /api/v1/security/login ['POST']
flask_appbuilder.api: INFO: Registering route /api/v1/security/refresh ['POST']
flask_appbuilder.base: INFO: Registering class ResetPasswordView on menu 
flask_appbuilder.baseviews: INFO: Registering route /resetpassword/form ['GET']
flask_appbuilder.baseviews: INFO: Registering route /resetpassword/form ['POST']
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can this form post on ResetPasswordView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can this form post on ResetPasswordView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can this form get on ResetPasswordView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can this form get on ResetPasswordView to role Admin
flask_appbuilder.base: INFO: Registering class ResetMyPasswordView on menu 
flask_appbuilder.baseviews: INFO: Registering route /resetmypassword/form ['GET']
flask_appbuilder.baseviews: INFO: Registering route /resetmypassword/form ['POST']
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can this form post on ResetMyPasswordView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can this form post on ResetMyPasswordView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can this form get on ResetMyPasswordView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can this form get on ResetMyPasswordView to role Admin
flask_appbuilder.base: INFO: Registering class UserInfoEditView on menu 
flask_appbuilder.baseviews: INFO: Registering route /userinfoeditview/form ['GET']
flask_appbuilder.baseviews: INFO: Registering route /userinfoeditview/form ['POST']
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can this form post on UserInfoEditView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can this form post on UserInfoEditView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can this form get on UserInfoEditView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can this form get on UserInfoEditView to role Admin
flask_appbuilder.base: INFO: Registering class AuthLDAPView on menu 
flask_appbuilder.baseviews: INFO: Registering route /login/ ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /logout/ ('GET',)
flask_appbuilder.base: INFO: Registering class UserLDAPModelView on menu List Users
flask_appbuilder.baseviews: INFO: Registering route /users/action/<string:name>/<pk> ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /users/action_post ['POST']
flask_appbuilder.baseviews: INFO: Registering route /users/add ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /users/api ['GET']
flask_appbuilder.baseviews: INFO: Registering route /users/api/column/add/<col_name> ['GET']
flask_appbuilder.baseviews: INFO: Registering route /users/api/column/edit/<col_name> ['GET']
flask_appbuilder.baseviews: INFO: Registering route /users/api/create ['POST']
flask_appbuilder.baseviews: INFO: Registering route /users/api/delete/<pk> ['DELETE']
flask_appbuilder.baseviews: INFO: Registering route /users/api/get/<pk> ['GET']
flask_appbuilder.baseviews: INFO: Registering route /users/api/read ['GET']
flask_appbuilder.baseviews: INFO: Registering route /users/api/readvalues ['GET']
flask_appbuilder.baseviews: INFO: Registering route /users/api/update/<pk> ['PUT']
flask_appbuilder.baseviews: INFO: Registering route /users/delete/<pk> ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /users/download/<string:filename> ('GET',)
flask_appbuilder.baseviews: INFO: Registering route /users/edit/<pk> ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /users/list/ ('GET',)
flask_appbuilder.baseviews: INFO: Registering route /users/show/<pk> ['GET']
flask_appbuilder.baseviews: INFO: Registering route /users/userinfo/ ('GET',)
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can delete on UserLDAPModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can delete on UserLDAPModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can edit on UserLDAPModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can edit on UserLDAPModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can show on UserLDAPModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can show on UserLDAPModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can download on UserLDAPModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can download on UserLDAPModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can list on UserLDAPModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can list on UserLDAPModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can add on UserLDAPModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can add on UserLDAPModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can userinfo on UserLDAPModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can userinfo on UserLDAPModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: userinfoedit on UserLDAPModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission userinfoedit on UserLDAPModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: menu access on List Users
flask_appbuilder.security.sqla.manager: INFO: Added Permission menu access on List Users to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: menu access on Security
flask_appbuilder.security.sqla.manager: INFO: Added Permission menu access on Security to role Admin
flask_appbuilder.base: INFO: Registering class RoleModelView on menu List Roles
flask_appbuilder.baseviews: INFO: Registering route /roles/action/<string:name>/<pk> ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /roles/action_post ['POST']
flask_appbuilder.baseviews: INFO: Registering route /roles/add ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /roles/api ['GET']
flask_appbuilder.baseviews: INFO: Registering route /roles/api/column/add/<col_name> ['GET']
flask_appbuilder.baseviews: INFO: Registering route /roles/api/column/edit/<col_name> ['GET']
flask_appbuilder.baseviews: INFO: Registering route /roles/api/create ['POST']
flask_appbuilder.baseviews: INFO: Registering route /roles/api/delete/<pk> ['DELETE']
flask_appbuilder.baseviews: INFO: Registering route /roles/api/get/<pk> ['GET']
flask_appbuilder.baseviews: INFO: Registering route /roles/api/read ['GET']
flask_appbuilder.baseviews: INFO: Registering route /roles/api/readvalues ['GET']
flask_appbuilder.baseviews: INFO: Registering route /roles/api/update/<pk> ['PUT']
flask_appbuilder.baseviews: INFO: Registering route /roles/delete/<pk> ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /roles/download/<string:filename> ('GET',)
flask_appbuilder.baseviews: INFO: Registering route /roles/edit/<pk> ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /roles/list/ ('GET',)
flask_appbuilder.baseviews: INFO: Registering route /roles/show/<pk> ['GET']
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can delete on RoleModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can delete on RoleModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can edit on RoleModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can edit on RoleModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can show on RoleModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can show on RoleModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can download on RoleModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can download on RoleModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can list on RoleModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can list on RoleModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can add on RoleModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can add on RoleModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: copyrole on RoleModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission copyrole on RoleModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: menu access on List Roles
flask_appbuilder.security.sqla.manager: INFO: Added Permission menu access on List Roles to role Admin
flask_appbuilder.base: INFO: Registering class UserStatsChartView on menu User's Statistics
flask_appbuilder.baseviews: INFO: Registering route /userstatschartview/chart/ ('GET',)
flask_appbuilder.baseviews: INFO: Registering route /userstatschartview/chart/<group_by> ('GET',)
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can chart on UserStatsChartView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can chart on UserStatsChartView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: menu access on User's Statistics
flask_appbuilder.security.sqla.manager: INFO: Added Permission menu access on User's Statistics to role Admin
flask_appbuilder.base: INFO: Registering class PermissionModelView on menu Base Permissions
flask_appbuilder.baseviews: INFO: Registering route /permissions/action/<string:name>/<pk> ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /permissions/action_post ['POST']
flask_appbuilder.baseviews: INFO: Registering route /permissions/add ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /permissions/api ['GET']
flask_appbuilder.baseviews: INFO: Registering route /permissions/api/column/add/<col_name> ['GET']
flask_appbuilder.baseviews: INFO: Registering route /permissions/api/column/edit/<col_name> ['GET']
flask_appbuilder.baseviews: INFO: Registering route /permissions/api/create ['POST']
flask_appbuilder.baseviews: INFO: Registering route /permissions/api/delete/<pk> ['DELETE']
flask_appbuilder.baseviews: INFO: Registering route /permissions/api/get/<pk> ['GET']
flask_appbuilder.baseviews: INFO: Registering route /permissions/api/read ['GET']
flask_appbuilder.baseviews: INFO: Registering route /permissions/api/readvalues ['GET']
flask_appbuilder.baseviews: INFO: Registering route /permissions/api/update/<pk> ['PUT']
flask_appbuilder.baseviews: INFO: Registering route /permissions/delete/<pk> ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /permissions/download/<string:filename> ('GET',)
flask_appbuilder.baseviews: INFO: Registering route /permissions/edit/<pk> ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /permissions/list/ ('GET',)
flask_appbuilder.baseviews: INFO: Registering route /permissions/show/<pk> ['GET']
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can list on PermissionModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can list on PermissionModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: menu access on Base Permissions
flask_appbuilder.security.sqla.manager: INFO: Added Permission menu access on Base Permissions to role Admin
flask_appbuilder.base: INFO: Registering class ViewMenuModelView on menu Views/Menus
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/action/<string:name>/<pk> ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/action_post ['POST']
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/add ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/api ['GET']
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/api/column/add/<col_name> ['GET']
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/api/column/edit/<col_name> ['GET']
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/api/create ['POST']
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/api/delete/<pk> ['DELETE']
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/api/get/<pk> ['GET']
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/api/read ['GET']
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/api/readvalues ['GET']
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/api/update/<pk> ['PUT']
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/delete/<pk> ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/download/<string:filename> ('GET',)
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/edit/<pk> ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/list/ ('GET',)
flask_appbuilder.baseviews: INFO: Registering route /viewmenus/show/<pk> ['GET']
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can list on ViewMenuModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can list on ViewMenuModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: menu access on Views/Menus
flask_appbuilder.security.sqla.manager: INFO: Added Permission menu access on Views/Menus to role Admin
flask_appbuilder.base: INFO: Registering class PermissionViewModelView on menu Permission on Views/Menus
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/action/<string:name>/<pk> ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/action_post ['POST']
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/add ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/api ['GET']
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/api/column/add/<col_name> ['GET']
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/api/column/edit/<col_name> ['GET']
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/api/create ['POST']
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/api/delete/<pk> ['DELETE']
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/api/get/<pk> ['GET']
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/api/read ['GET']
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/api/readvalues ['GET']
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/api/update/<pk> ['PUT']
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/delete/<pk> ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/download/<string:filename> ('GET',)
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/edit/<pk> ['GET', 'POST']
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/list/ ('GET',)
flask_appbuilder.baseviews: INFO: Registering route /permissionviews/show/<pk> ['GET']
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can list on PermissionViewModelView
flask_appbuilder.security.sqla.manager: INFO: Added Permission can list on PermissionViewModelView to role Admin
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: menu access on Permission on Views/Menus
flask_appbuilder.security.sqla.manager: INFO: Added Permission menu access on Permission on Views/Menus to role Admin
flask_appbuilder.base: INFO: Registering class MenuApi on menu 
flask_appbuilder.api: INFO: Registering route /api/v1/menu/ ['GET']
flask_appbuilder.security.sqla.manager: INFO: Created Permission View: can get on MenuApi
flask_appbuilder.security.sqla.manager: INFO: Added Permission can get on MenuApi to role Admin
--------------------- >> end captured logging << ---------------------

Name                                                                   Stmts   Miss  Cover
------------------------------------------------------------------------------------------
flask_appbuilder/__init__.py                                              11      0   100%
flask_appbuilder/_compat.py                                               34     13    62%
flask_appbuilder/actions.py                                               16      1    94%
flask_appbuilder/api/__init__.py                                         695    408    41%
flask_appbuilder/api/convert.py                                          140    111    21%
flask_appbuilder/api/manager.py                                           53     21    60%
flask_appbuilder/api/schemas.py                                           22     11    50%
flask_appbuilder/babel/__init__.py                                         0      0   100%
flask_appbuilder/babel/manager.py                                         44     16    64%
flask_appbuilder/babel/views.py                                           14      6    57%
flask_appbuilder/base.py                                                 278     82    71%
flask_appbuilder/basemanager.py                                            6      0   100%
flask_appbuilder/baseviews.py                                            541    241    55%
flask_appbuilder/charts/__init__.py                                        0      0   100%
flask_appbuilder/charts/jsontools.py                                       2      0   100%
flask_appbuilder/charts/views.py                                          88     34    61%
flask_appbuilder/charts/widgets.py                                         7      0   100%
flask_appbuilder/cli.py                                                  224    134    40%
flask_appbuilder/const.py                                                101      0   100%
flask_appbuilder/exceptions.py                                            19      3    84%
flask_appbuilder/fields.py                                               139    108    22%
flask_appbuilder/fieldwidgets.py                                         114     76    33%
flask_appbuilder/filemanager.py                                          151    110    27%
flask_appbuilder/filters.py                                              111     67    40%
flask_appbuilder/forms.py                                                110     12    89%
flask_appbuilder/hooks.py                                                 30     17    43%
flask_appbuilder/menu.py                                                 105     40    62%
flask_appbuilder/models/__init__.py                                        0      0   100%
flask_appbuilder/models/base.py                                          181     97    46%
flask_appbuilder/models/filters.py                                       147     72    51%
flask_appbuilder/models/generic/__init__.py                              258    173    33%
flask_appbuilder/models/generic/filters.py                                37      8    78%
flask_appbuilder/models/generic/interface.py                              52     33    37%
flask_appbuilder/models/group.py                                         180    122    32%
flask_appbuilder/models/mixins.py                                         45     12    73%
flask_appbuilder/models/mongoengine/__init__.py                            0      0   100%
flask_appbuilder/models/mongoengine/fields.py                             36     21    42%
flask_appbuilder/models/sqla/__init__.py                                  56     15    73%
flask_appbuilder/models/sqla/filters.py                                  167     93    44%
flask_appbuilder/models/sqla/interface.py                                577    357    38%
flask_appbuilder/security/__init__.py                                      0      0   100%
flask_appbuilder/security/api.py                                          43     24    44%
flask_appbuilder/security/decorators.py                                   82     47    43%
flask_appbuilder/security/forms.py                                        36      0   100%
flask_appbuilder/security/manager.py                                     941    575    39%
flask_appbuilder/security/registerviews.py                               138     94    32%
flask_appbuilder/security/schemas.py                                      20      6    70%
flask_appbuilder/security/sqla/__init__.py                                 0      0   100%
flask_appbuilder/security/sqla/apis/__init__.py                            5      0   100%
flask_appbuilder/security/sqla/apis/permission/__init__.py                 1      0   100%
flask_appbuilder/security/sqla/apis/permission/api.py                     15      0   100%
flask_appbuilder/security/sqla/apis/permission_view_menu/__init__.py       1      0   100%
flask_appbuilder/security/sqla/apis/permission_view_menu/api.py           13      0   100%
flask_appbuilder/security/sqla/apis/role/__init__.py                       1      0   100%
flask_appbuilder/security/sqla/apis/role/api.py                           56     22    61%
flask_appbuilder/security/sqla/apis/role/schema.py                         7      0   100%
flask_appbuilder/security/sqla/apis/user/__init__.py                       1      0   100%
flask_appbuilder/security/sqla/apis/user/api.py                           86     49    43%
flask_appbuilder/security/sqla/apis/user/schema.py                        29      0   100%
flask_appbuilder/security/sqla/apis/user/validator.py                     19     12    37%
flask_appbuilder/security/sqla/apis/view_menu/__init__.py                  1      0   100%
flask_appbuilder/security/sqla/apis/view_menu/api.py                      14      0   100%
flask_appbuilder/security/sqla/manager.py                                379    207    45%
flask_appbuilder/security/sqla/models.py                                  97      9    91%
flask_appbuilder/security/views.py                                       366    181    51%
flask_appbuilder/upload.py                                               101     68    33%
flask_appbuilder/urltools.py                                              63     49    22%
flask_appbuilder/utils/__init__.py                                         0      0   100%
flask_appbuilder/utils/base.py                                            44     28    36%
flask_appbuilder/validators.py                                            39     21    46%
flask_appbuilder/views.py                                                481    330    31%
flask_appbuilder/widgets.py                                               72     24    67%
------------------------------------------------------------------------------------------
TOTAL                                                                   7942   4260    46%
----------------------------------------------------------------------
Ran 7 tests in 6.069s

FAILED (failures=1)
ERROR: InvocationError for command /dev/shm/flask-appbuilder/.tox/api-sqlite/bin/nosetests --stop -v --with-coverage --cover-package=flask_appbuilder flask_appbuilder.tests '--ignore-files=test_mongoengine\.py' (exited with code 1)
_____________________________________________________________________________________________________ summary _____________________________________________________________________________________________________
ERROR:   api-sqlite: commands failed
```

Any ideas what's going on here? Is there a different way I should be calling/running the tests?

**Comment by jnahmias** [comment]
Okay, after doing some digging, I've come up with the following patch:
```patch
$ git diff
diff --git a/tox.ini b/tox.ini
index 4a3fa5b0..c1e705e8 100644
--- a/tox.ini
+++ b/tox.ini
@@ -13,9 +13,13 @@ deps =
 
 [testenv:api-sqlite]
 setenv =
-    SQLALCHEMY_DATABASE_URI = sqlite:///
+    SQLALCHEMY_DATABASE_URI = sqlite:///{temp_dir}/fab-test.db
+deps =
+    -rrequirements.txt
+    -rrequirements-dev.txt
+    -rrequirements-extra.txt
 commands =
-    nosetests --stop -v --with-coverage --cover-package=flask_appbuilder flask_appbuilder.tests --ignore-files="test_mongoengine\.py"
+    nosetests --logging-level=WARNING --verbose --ignore-files="test_mongoengine\.py" flask_appbuilder.tests
 
 [testenv:mysql]
 setenv =
```

That gets me quite a bit further:
```
Ran 302 tests in 306.392s
FAILED (errors=16, failures=36)
```

Any assistance would be appreciated!

**Comment by dpgaspar** [comment]
This is the preferred way of running tests: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/CONTRIBUTING.rst#run-a-single-test
