### ISSUE TITLE
Need to include inputs in existing templates from the ModelView class.

### ISSUE THREAD

**Issue by XiangYang95** [dpgaspar/Flask-AppBuilder#1893]
### Environment

Flask-Appbuilder version:3.4.4

### Describe the expected results

I wanted to modify the edit template such that I can include my own inputs. But the existing functions/methods don't allow that. So instead I did the below instead of the conventional edit_template = 'xx.html'.

```python
class SQLDepoModelView(ModelView):
    @expose("/edit")
    @has_access
    def edit(self):
        keywords = [keyword_obj.keyword for keyword_obj in db.session.query(sql_depo_keyword_helper).all()]
        return self.render_template('edit_template.html', keywords=keywords)
```

### Describe the actual results

I'll get a "jinja2.exceptions.UndefinedError: 'widgets' is undefined" instead.

```pytb
* Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
C:\ProgramData\Anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py:873: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
2022-07-19 13:07:17,207:INFO:flask_appbuilder.base:Registering class IndexView on menu
2022-07-19 13:07:17,207:INFO:flask_appbuilder.baseviews:Registering route / ('GET',)
2022-07-19 13:07:17,223:INFO:flask_appbuilder.base:Registering class UtilView on menu
2022-07-19 13:07:17,223:INFO:flask_appbuilder.baseviews:Registering route /back ('GET',)
2022-07-19 13:07:17,238:INFO:flask_appbuilder.base:Registering class LocaleView on menu
2022-07-19 13:07:17,238:INFO:flask_appbuilder.baseviews:Registering route /lang/<string:locale> ('GET',)
2022-07-19 13:07:17,238:INFO:flask_appbuilder.base:Registering class SecurityApi on menu
2022-07-19 13:07:17,238:INFO:flask_appbuilder.api:Registering route /api/v1/security/login ['POST']
2022-07-19 13:07:17,238:INFO:flask_appbuilder.api:Registering route /api/v1/security/refresh ['POST']
2022-07-19 13:07:17,254:INFO:flask_appbuilder.base:Registering class ResetPasswordView on menu
2022-07-19 13:07:17,254:INFO:flask_appbuilder.baseviews:Registering route /resetpassword/form ['GET']
2022-07-19 13:07:17,254:INFO:flask_appbuilder.baseviews:Registering route /resetpassword/form ['POST']
2022-07-19 13:07:17,285:INFO:flask_appbuilder.base:Registering class ResetMyPasswordView on menu
2022-07-19 13:07:17,287:INFO:flask_appbuilder.baseviews:Registering route /resetmypassword/form ['GET']
2022-07-19 13:07:17,287:INFO:flask_appbuilder.baseviews:Registering route /resetmypassword/form ['POST']
2022-07-19 13:07:17,303:INFO:flask_appbuilder.base:Registering class UserInfoEditView on menu
2022-07-19 13:07:17,303:INFO:flask_appbuilder.baseviews:Registering route /userinfoeditview/form ['GET']
2022-07-19 13:07:17,303:INFO:flask_appbuilder.baseviews:Registering route /userinfoeditview/form ['POST']
2022-07-19 13:07:17,319:INFO:flask_appbuilder.base:Registering class AuthDBView on menu
2022-07-19 13:07:17,319:INFO:flask_appbuilder.baseviews:Registering route /login/ ['GET', 'POST']
2022-07-19 13:07:17,319:INFO:flask_appbuilder.baseviews:Registering route /logout/ ('GET',)
2022-07-19 13:07:17,335:INFO:flask_appbuilder.base:Registering class UserDBModelView on menu List Users
2022-07-19 13:07:17,335:INFO:flask_appbuilder.baseviews:Registering route /users/action/<string:name>/<pk> ['GET', 'POST']
2022-07-19 13:07:17,335:INFO:flask_appbuilder.baseviews:Registering route /users/action_post ['POST']
2022-07-19 13:07:17,335:INFO:flask_appbuilder.baseviews:Registering route /users/add ['GET', 'POST']
2022-07-19 13:07:17,335:INFO:flask_appbuilder.baseviews:Registering route /users/api ['GET']
2022-07-19 13:07:17,335:INFO:flask_appbuilder.baseviews:Registering route /users/api/column/add/<col_name> ['GET']
2022-07-19 13:07:17,335:INFO:flask_appbuilder.baseviews:Registering route /users/api/column/edit/<col_name> ['GET']
2022-07-19 13:07:17,335:INFO:flask_appbuilder.baseviews:Registering route /users/api/create ['POST']
2022-07-19 13:07:17,335:INFO:flask_appbuilder.baseviews:Registering route /users/api/delete/<pk> ['DELETE']
2022-07-19 13:07:17,350:INFO:flask_appbuilder.baseviews:Registering route /users/api/get/<pk> ['GET']
2022-07-19 13:07:17,350:INFO:flask_appbuilder.baseviews:Registering route /users/api/read ['GET']
2022-07-19 13:07:17,350:INFO:flask_appbuilder.baseviews:Registering route /users/api/readvalues ['GET']
2022-07-19 13:07:17,350:INFO:flask_appbuilder.baseviews:Registering route /users/api/update/<pk> ['PUT']
2022-07-19 13:07:17,350:INFO:flask_appbuilder.baseviews:Registering route /users/delete/<pk> ['GET', 'POST']
2022-07-19 13:07:17,350:INFO:flask_appbuilder.baseviews:Registering route /users/download/<string:filename> ('GET',)
2022-07-19 13:07:17,350:INFO:flask_appbuilder.baseviews:Registering route /users/edit/<pk> ['GET', 'POST']
2022-07-19 13:07:17,350:INFO:flask_appbuilder.baseviews:Registering route /users/list/ ('GET',)
2022-07-19 13:07:17,366:INFO:flask_appbuilder.baseviews:Registering route /users/show/<pk> ['GET']
2022-07-19 13:07:17,366:INFO:flask_appbuilder.baseviews:Registering route /users/userinfo/ ('GET',)
2022-07-19 13:07:17,414:INFO:flask_appbuilder.base:Registering class RoleModelView on menu List Roles
2022-07-19 13:07:17,414:INFO:flask_appbuilder.baseviews:Registering route /roles/action/<string:name>/<pk> ['GET', 'POST']
2022-07-19 13:07:17,466:INFO:flask_appbuilder.baseviews:Registering route /roles/action_post ['POST']
2022-07-19 13:07:17,482:INFO:flask_appbuilder.baseviews:Registering route /roles/add ['GET', 'POST']
2022-07-19 13:07:17,482:INFO:flask_appbuilder.baseviews:Registering route /roles/api ['GET']
2022-07-19 13:07:17,482:INFO:flask_appbuilder.baseviews:Registering route /roles/api/column/add/<col_name> ['GET']
2022-07-19 13:07:17,482:INFO:flask_appbuilder.baseviews:Registering route /roles/api/column/edit/<col_name> ['GET']
2022-07-19 13:07:17,482:INFO:flask_appbuilder.baseviews:Registering route /roles/api/create ['POST']
2022-07-19 13:07:17,482:INFO:flask_appbuilder.baseviews:Registering route /roles/api/delete/<pk> ['DELETE']
2022-07-19 13:07:17,482:INFO:flask_appbuilder.baseviews:Registering route /roles/api/get/<pk> ['GET']
2022-07-19 13:07:17,482:INFO:flask_appbuilder.baseviews:Registering route /roles/api/read ['GET']
2022-07-19 13:07:17,482:INFO:flask_appbuilder.baseviews:Registering route /roles/api/readvalues ['GET']
2022-07-19 13:07:17,482:INFO:flask_appbuilder.baseviews:Registering route /roles/api/update/<pk> ['PUT']
2022-07-19 13:07:17,482:INFO:flask_appbuilder.baseviews:Registering route /roles/delete/<pk> ['GET', 'POST']
2022-07-19 13:07:17,482:INFO:flask_appbuilder.baseviews:Registering route /roles/download/<string:filename> ('GET',)
2022-07-19 13:07:17,482:INFO:flask_appbuilder.baseviews:Registering route /roles/edit/<pk> ['GET', 'POST']
2022-07-19 13:07:17,498:INFO:flask_appbuilder.baseviews:Registering route /roles/list/ ('GET',)
2022-07-19 13:07:17,591:INFO:flask_appbuilder.baseviews:Registering route /roles/show/<pk> ['GET']
2022-07-19 13:07:17,668:INFO:flask_appbuilder.base:Registering class UserStatsChartView on menu User's Statistics
2022-07-19 13:07:17,668:INFO:flask_appbuilder.baseviews:Registering route /userstatschartview/chart/ ('GET',)
2022-07-19 13:07:17,684:INFO:flask_appbuilder.baseviews:Registering route /userstatschartview/chart/<group_by> ('GET',)
2022-07-19 13:07:17,731:INFO:flask_appbuilder.base:Registering class PermissionModelView on menu Base Permissions
2022-07-19 13:07:17,731:INFO:flask_appbuilder.baseviews:Registering route /permissions/action/<string:name>/<pk> ['GET', 'POST']
2022-07-19 13:07:17,746:INFO:flask_appbuilder.baseviews:Registering route /permissions/action_post ['POST']
2022-07-19 13:07:17,746:INFO:flask_appbuilder.baseviews:Registering route /permissions/add ['GET', 'POST']
2022-07-19 13:07:17,746:INFO:flask_appbuilder.baseviews:Registering route /permissions/api ['GET']
2022-07-19 13:07:17,746:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/column/add/<col_name> ['GET']
2022-07-19 13:07:17,762:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/column/edit/<col_name> ['GET']
2022-07-19 13:07:17,825:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/create ['POST']
2022-07-19 13:07:17,825:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/delete/<pk> ['DELETE']
2022-07-19 13:07:17,825:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/get/<pk> ['GET']
2022-07-19 13:07:17,825:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/read ['GET']
2022-07-19 13:07:17,825:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/readvalues ['GET']
2022-07-19 13:07:17,825:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/update/<pk> ['PUT']
2022-07-19 13:07:17,825:INFO:flask_appbuilder.baseviews:Registering route /permissions/delete/<pk> ['GET', 'POST']
2022-07-19 13:07:17,825:INFO:flask_appbuilder.baseviews:Registering route /permissions/download/<string:filename> ('GET',)
2022-07-19 13:07:17,825:INFO:flask_appbuilder.baseviews:Registering route /permissions/edit/<pk> ['GET', 'POST']
2022-07-19 13:07:17,825:INFO:flask_appbuilder.baseviews:Registering route /permissions/list/ ('GET',)
2022-07-19 13:07:17,825:INFO:flask_appbuilder.baseviews:Registering route /permissions/show/<pk> ['GET']
2022-07-19 13:07:17,871:INFO:flask_appbuilder.base:Registering class ViewMenuModelView on menu Views/Menus
2022-07-19 13:07:17,903:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/action/<string:name>/<pk> ['GET', 'POST']
2022-07-19 13:07:17,903:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/action_post ['POST']
2022-07-19 13:07:17,903:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/add ['GET', 'POST']
2022-07-19 13:07:17,903:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api ['GET']
2022-07-19 13:07:17,903:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/column/add/<col_name> ['GET']
2022-07-19 13:07:17,903:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/column/edit/<col_name> ['GET']
2022-07-19 13:07:17,918:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/create ['POST']
2022-07-19 13:07:17,983:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/delete/<pk> ['DELETE']
2022-07-19 13:07:17,983:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/get/<pk> ['GET']
2022-07-19 13:07:17,983:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/read ['GET']
2022-07-19 13:07:17,996:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/readvalues ['GET']
2022-07-19 13:07:17,996:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/update/<pk> ['PUT']
2022-07-19 13:07:17,996:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/delete/<pk> ['GET', 'POST']
2022-07-19 13:07:17,996:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/download/<string:filename> ('GET',)
2022-07-19 13:07:18,012:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/edit/<pk> ['GET', 'POST']
2022-07-19 13:07:18,090:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/list/ ('GET',)
2022-07-19 13:07:18,090:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/show/<pk> ['GET']
2022-07-19 13:07:18,137:INFO:flask_appbuilder.base:Registering class PermissionViewModelView on menu Permission on Views/Menus
2022-07-19 13:07:18,137:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/action/<string:name>/<pk> ['GET', 'POST']
2022-07-19 13:07:18,168:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/action_post ['POST']
2022-07-19 13:07:18,168:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/add ['GET', 'POST']
2022-07-19 13:07:18,168:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api ['GET']
2022-07-19 13:07:18,168:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/column/add/<col_name> ['GET']
2022-07-19 13:07:18,168:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/column/edit/<col_name> ['GET']
2022-07-19 13:07:18,168:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/create ['POST']
2022-07-19 13:07:18,184:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/delete/<pk> ['DELETE']
2022-07-19 13:07:18,200:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/get/<pk> ['GET']
2022-07-19 13:07:18,200:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/read ['GET']
2022-07-19 13:07:18,200:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/readvalues ['GET']
2022-07-19 13:07:18,200:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/update/<pk> ['PUT']
2022-07-19 13:07:18,200:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/delete/<pk> ['GET', 'POST']
2022-07-19 13:07:18,200:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/download/<string:filename> ('GET',)
2022-07-19 13:07:18,200:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/edit/<pk> ['GET', 'POST']
2022-07-19 13:07:18,200:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/list/ ('GET',)
2022-07-19 13:07:18,200:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/show/<pk> ['GET']
2022-07-19 13:07:18,262:INFO:flask_appbuilder.base:Registering class MenuApi on menu
2022-07-19 13:07:18,305:INFO:flask_appbuilder.api:Registering route /api/v1/menu/ ['GET']
2022-07-19 13:07:18,570:INFO:flask_appbuilder.base:Registering class SQLDepoModelView on menu All SQLs
2022-07-19 13:07:18,570:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/action/<string:name>/<pk> ['GET', 'POST']
2022-07-19 13:07:18,586:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/action_post ['POST']
2022-07-19 13:07:18,593:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/add ['GET', 'POST']
2022-07-19 13:07:18,631:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/api ['GET']
2022-07-19 13:07:18,631:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/api/column/add/<col_name> ['GET']
2022-07-19 13:07:18,631:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/api/column/edit/<col_name> ['GET']
2022-07-19 13:07:18,631:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/api/create ['POST']
2022-07-19 13:07:18,631:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/api/delete/<pk> ['DELETE']
2022-07-19 13:07:18,631:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/api/get/<pk> ['GET']
2022-07-19 13:07:18,647:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/api/read ['GET']
2022-07-19 13:07:18,647:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/api/readvalues ['GET']
2022-07-19 13:07:18,662:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/api/update/<pk> ['PUT']
2022-07-19 13:07:18,662:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/delete/<pk> ['GET', 'POST']
2022-07-19 13:07:18,662:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/download/<string:filename> ('GET',)
2022-07-19 13:07:18,662:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/edit ('GET',)
2022-07-19 13:07:18,662:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/list/ ('GET',)
2022-07-19 13:07:18,662:INFO:flask_appbuilder.baseviews:Registering route /sqldepomodelview/show/<pk> ['GET']
2022-07-19 13:07:18,712:INFO:flask_appbuilder.base:Registering class KeywordView on menu Keyword
2022-07-19 13:07:18,724:INFO:flask_appbuilder.baseviews:Registering route /keywordview/action/<string:name>/<pk> ['GET', 'POST']
2022-07-19 13:07:18,724:INFO:flask_appbuilder.baseviews:Registering route /keywordview/action_post ['POST']
2022-07-19 13:07:18,724:INFO:flask_appbuilder.baseviews:Registering route /keywordview/add ['GET', 'POST']
2022-07-19 13:07:18,724:INFO:flask_appbuilder.baseviews:Registering route /keywordview/api ['GET']
2022-07-19 13:07:18,724:INFO:flask_appbuilder.baseviews:Registering route /keywordview/api/column/add/<col_name> ['GET']
2022-07-19 13:07:18,724:INFO:flask_appbuilder.baseviews:Registering route /keywordview/api/column/edit/<col_name> ['GET']
2022-07-19 13:07:18,724:INFO:flask_appbuilder.baseviews:Registering route /keywordview/api/create ['POST']
2022-07-19 13:07:18,724:INFO:flask_appbuilder.baseviews:Registering route /keywordview/api/delete/<pk> ['DELETE']
2022-07-19 13:07:18,724:INFO:flask_appbuilder.baseviews:Registering route /keywordview/api/get/<pk> ['GET']
2022-07-19 13:07:18,724:INFO:flask_appbuilder.baseviews:Registering route /keywordview/api/read ['GET']
2022-07-19 13:07:18,740:INFO:flask_appbuilder.baseviews:Registering route /keywordview/api/readvalues ['GET']
2022-07-19 13:07:18,740:INFO:flask_appbuilder.baseviews:Registering route /keywordview/api/update/<pk> ['PUT']
2022-07-19 13:07:18,740:INFO:flask_appbuilder.baseviews:Registering route /keywordview/delete/<pk> ['GET', 'POST']
2022-07-19 13:07:18,758:INFO:flask_appbuilder.baseviews:Registering route /keywordview/download/<string:filename> ('GET',)
2022-07-19 13:07:18,849:INFO:flask_appbuilder.baseviews:Registering route /keywordview/edit/<pk> ['GET', 'POST']
2022-07-19 13:07:18,849:INFO:flask_appbuilder.baseviews:Registering route /keywordview/list/ ('GET',)
2022-07-19 13:07:18,849:INFO:flask_appbuilder.baseviews:Registering route /keywordview/show/<pk> ['GET']
2022-07-19 13:07:18,952:INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-07-19 13:07:21,836:ERROR:app:Exception on /sqldepomodelview/edit [GET]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\flask_appbuilder\security\decorators.py", line 148, in wraps
    return f(self, *args, **kwargs)
  File "C:\MY CRM\PycharmProjects\sql_depository_app\sql_depo_app\app\views.py", line 31, in edit
    return self.render_template('edit_template.html', keywords=keywords)
  File "C:\ProgramData\Anaconda3\lib\flask_appbuilder\baseviews.py", line 288, in render_template
    template, **dict(list(kwargs.items()) + list(self.extra_args.items()))
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\MY CRM\PycharmProjects\sql_depository_app\sql_depo_app\app\templates\edit_template.html", line 1, in top-level template code
    {% extends "appbuilder/general/model/edit.html" %}
  File "C:\ProgramData\Anaconda3\lib\flask_appbuilder\templates\appbuilder\general\model\edit.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "C:\ProgramData\Anaconda3\lib\flask_appbuilder\templates\appbuilder\base.html", line 1, in top-level template code
    {% extends base_template %}
  File "C:\MY CRM\PycharmProjects\sql_depository_app\sql_depo_app\app\templates\base_template.html", line 1, in top-level template code
    {% extends 'appbuilder/baselayout.html' %}
  File "C:\ProgramData\Anaconda3\lib\flask_appbuilder\templates\appbuilder\baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "C:\ProgramData\Anaconda3\lib\flask_appbuilder\templates\appbuilder\init.html", line 37, in top-level template code
    {% block body %}
  File "C:\ProgramData\Anaconda3\lib\flask_appbuilder\templates\appbuilder\baselayout.html", line 19, in block 'body'
    {% block content %}
  File "C:\ProgramData\Anaconda3\lib\flask_appbuilder\templates\appbuilder\general\model\edit.html", line 23, in block 'content'
    {% block edit_form %}
  File "C:\MY CRM\PycharmProjects\sql_depository_app\sql_depo_app\app\templates\edit_template.html", line 4, in block 'edit_form'
    {{ super() }}
  File "C:\ProgramData\Anaconda3\lib\flask_appbuilder\templates\appbuilder\general\model\edit.html", line 25, in block 'edit_form'
    {{ widgets.get('edit')(form_action=form_action)|safe }}
  File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'widgets' is undefined
2022-07-19 13:07:21,853:INFO:werkzeug:127.0.0.1 - - [19/Jul/2022 13:07:21] "GET /sqldepomodelview/edit?pk=1 HTTP/1.1" 500 -
```

### Steps to reproduce
After setting up the model.py and view.py and any other preparations, I ran "flask run" in the command prompt

**Comment by ThomasP0815** [comment]
If you inherit from ModelView, you have to do it like that.
```
  @expose("/edit/<pk>", methods=["GET", "POST"])
  @has_access
  def edit(self, pk):
      keywords = [keyword_obj.keyword for keyword_obj in db.session.query(sql_depo_keyword_helper).all()]
      pk = self._deserialize_pk_if_composite(pk)
      widgets = self._edit(pk)
      if not widgets:
          return self.post_edit_redirect()
      else:
          return self.render_template(
              edit_template.html,
              title=self.edit_title,
              widgets=widgets,
              related_views=self._related_views,
              keywords=keywords
          )

```

**Comment by XiangYang95** [comment]
@ThomasP0815 thank you so much for answering my question!
