### ISSUE TITLE
TypeError: unhashable type: '_LazyString'

### ISSUE THREAD

**Issue by pchernik** [dpgaspar/Flask-AppBuilder#202]
(Using Python3)

I've created the Skeleton app using "fabmanager create-app" and everything worked fine with sqlite3.

Now I am trying to use mysql as database backend, with the following config.py URIs (I tried using both pymysql and mysqlconnector):

    SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://flask:flask@srmsbox01/flask'

and

    SQLALCHEMY_DATABASE_URI = 'mysql+mysqlconnector://flask:flask@srmsbox01/flask'

fabmanager create-admin was successful.

I ran python3 run.py and application started up w/o problems. Upon trying to connect via web browser, I get the following error:

```
2015-08-05 21:07:22,806:INFO:werkzeug:10.10.34.218 - - [05/Aug/2015 21:07:22] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask_appbuilder/views.py", line 26, in index
    appbuilder=self.appbuilder)
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask_appbuilder/baseviews.py", line 156, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask_appbuilder/templates/appbuilder/index.html", line 1, in top-level template code
    {% extends "appbuilder/base.html" %}
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 8, in block "body"
    {% block navbar %}
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 10, in block "navbar"
    {% include 'appbuilder/navbar.html' %}
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask_appbuilder/templates/appbuilder/navbar.html", line 29, in top-level template code
    {% include 'appbuilder/navbar_menu.html' %}
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask_appbuilder/templates/appbuilder/navbar_menu.html", line 18, in top-level template code
    {{_(item1.label)}}<b class="caret"></b></a>
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/jinja2/ext.py", line 132, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/jinja2/ext.py", line 138, in gettext
    rv = __context.call(func, __string)
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/site-packages/flask_babelpkg/__init__.py", line 117, in <lambda>
    lambda x: get_translations().ugettext(x),
  File "/apps/u02/srm_tp.rhel6/local/lib/python3.4/gettext.py", line 332, in gettext
    tmsg = self._catalog.get(message, missing)
TypeError: unhashable type: '_LazyString'
```

Any ideas / suggestions are greatly appreciated.

**Comment by pchernik** [comment]
I've cleared browser cookies and cache (Chrome) and the issue went away.

**Comment by jsbueno** [comment]
It is 2016-03 now, creatign a fresh app in Python 3.4, with default config leads to the same error as soon as the language is changed.

**Comment by wgzhao** [comment]
+1

**Comment by rocky1001** [comment]
I've encountered exact the same problem today, with Python 3.5.0 env.

**Comment by dpgaspar** [comment]
Look! theres a light at the end of the tunnel!

**Comment by rocky1001** [comment]
@dpgaspar That's really a GOOD news, thanks a lot!

**Comment by dpgaspar** [comment]
Release 1.8.0 upgrade and enjoy!
