### ISSUE TITLE
ModuleNotFoundError: No module named 'config'

### ISSUE THREAD

**Issue by coopzr** [dpgaspar/Flask-AppBuilder#2058]
### Environment

Flask-Appbuilder version:
3.4.5

pip freeze output:
apispec==3.3.2
attrs==22.2.0
Babel==2.11.0
click==7.1.2
colorama==0.4.5
dataclasses==0.8
defusedxml==0.7.1
dnspython==2.2.1
email-validator==1.3.1
Flask==1.1.4
Flask-AppBuilder==3.4.5
Flask-Babel==2.0.0
Flask-JWT-Extended==3.25.1
Flask-Login==0.4.1
Flask-OpenID==1.3.0
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.14.3
greenlet==2.0.2
idna==3.4
importlib-metadata==4.8.3
itsdangerous==1.1.0
Jinja2==2.11.3
jsonschema==3.2.0
MarkupSafe==2.0.1
marshmallow==3.14.1
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.26.1
prison==0.2.1
PyJWT==1.7.1
pyrsistent==0.18.0
python-dateutil==2.8.2
python3-openid==3.2.0
pytz==2023.3
PyYAML==6.0
six==1.16.0
SQLAlchemy==1.4.48
SQLAlchemy-Utils==0.41.1
typing_extensions==4.1.1
Werkzeug==1.0.1
WTForms==2.3.3
zipp==3.6.0

### Describe the expected results

It should create the admin
```python
(venv) C:\Users\coope\PycharmProjects\flaskProject\first_app>flask fab create-admin
Username [admin]: 
User first name [admin]:
User last name [user]:
Email [admin@fab.org]:
Password:
Repeat for confirmation:
Usage: flask fab create-admin [OPTIONS]

Error: While importing "app", an ImportError was raised:
```

### Describe the actual results

There is no module named 'config'

### Steps to reproduce
Follow the [documentation](https://flask-appbuilder.readthedocs.io/en/latest/installation.html)
```pytb
venv) C:\Users\coope\PycharmProjects\flaskProject>flask fab create-app
Your new app name: first_app
Your engine type, SQLAlchemy or MongoEngine (SQLAlchemy, MongoEngine) [SQLAlchemy]:
Downloaded the skeleton app, good coding!

(venv) C:\Users\coope\PycharmProjects\flaskProject>cd  first_app

(venv) C:\Users\coope\PycharmProjects\flaskProject\first_app>set FLASK_APP=app

(venv) C:\Users\coope\PycharmProjects\flaskProject\first_app>flask fab create-admin
Username [admin]: 
User first name [admin]:
User last name [user]:
Email [admin@fab.org]:
Password:
Repeat for confirmation:
Usage: flask fab create-admin [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "C:\Users\coope\PycharmProjects\flaskProject\venv\lib\site-packages\werkzeug\utils.py", line 568, in import_string
    __import__(import_name)
ModuleNotFoundError: No module named 'config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\coope\PycharmProjects\flaskProject\venv\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "C:\Users\coope\PycharmProjects\flaskProject\first_app\app\__init__.py", line 14, in <module>
    app.config.from_object("config")
  File "C:\Users\coope\PycharmProjects\flaskProject\venv\lib\site-packages\flask\config.py", line 174, in from_object
    obj = import_string(obj)
  File "C:\Users\coope\PycharmProjects\flaskProject\venv\lib\site-packages\werkzeug\utils.py", line 585, in import_string
    ImportStringError, ImportStringError(import_name, e), sys.exc_info()[2]
  File "C:\Users\coope\PycharmProjects\flaskProject\venv\lib\site-packages\werkzeug\_compat.py", line 147, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\coope\PycharmProjects\flaskProject\venv\lib\site-packages\werkzeug\utils.py", line 568, in import_string
    __import__(import_name)
werkzeug.utils.ImportStringError: import_string() failed for 'config'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' not found.

Original exception:

ModuleNotFoundError: No module named 'config'
```

**Comment by coopzr** [comment]
Relevant:
#2056 

I fixed it by renaming "config.py.tcl" to "config.py".

This was changed last month: https://github.com/dpgaspar/Flask-AppBuilder-Skeleton/commit/e0ff4a887cd8311f0a6754663c9293cf82341d4e

**Comment by dpgaspar** [comment]
thank for opening the issue, you should use the latest FAB version also

**Comment by coopzr** [comment]
I believe this is still broken. Why is the config file named config.py.tpl instead of config.py?
