### ISSUE TITLE
sqlalchemy.exc.TimeoutError  connection timed out, timeout 900

### ISSUE THREAD

**Issue by echochio-tw** [dpgaspar/Flask-AppBuilder#2077]
Some time will get error 
`Traceback (most recent call last):
  File "/home/flask/app/message/env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/flask/app/message/env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/flask/app/message/env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/flask/app/message/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/flask/app/message/env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/flask/app/message/env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/views.py", line 536, in nationmethod
    a = db.session.query(Member).filter_by(user = u,signature = s).first()
  File "/home/flask/app/message/env/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3375, in first
    ret = list(self[0:1])
  File "/home/flask/app/message/env/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3149, in __getitem__
    return list(res)
  File "/home/flask/app/message/env/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3481, in __iter__
    return self._execute_and_instances(context)
  File "/home/flask/app/message/env/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3503, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/home/flask/app/message/env/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3518, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/home/flask/app/message/env/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3496, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/flask/app/message/env/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
    execution_options=execution_options,
  File "/home/flask/app/message/env/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "/home/flask/app/message/env/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/flask/app/message/env/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2311, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/flask/app/message/env/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "/home/flask/app/message/env/lib64/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/flask/app/message/env/lib64/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/flask/app/message/env/lib64/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/flask/app/message/env/lib64/python3.6/site-packages/sqlalchemy/pool/impl.py", line 132, in _do_get
    code="3o7r",
sqlalchemy.exc.TimeoutError: QueuePool limit of size 10 overflow 5 reached, connection timed out, timeout 900 (Background on this error at: http://sqlalche.me/e/3o7r)
`

Mysql restart and  Flask-AppBuilder restart  will be fine

How to fix this ？

**Comment by echochio-tw** [comment]
`SQLALCHEMY_ENGINE_OPTIONS = {
    "poolclass": QueuePool,
    "pool_pre_ping": True,
    "pool_recycle": 800,
    'pool_timeout': 900,
    'pool_size': 30,
    'max_overflow': 20,
}
`
 can close case
