### ISSUE TITLE
issue with flask-appbuilder installation `flask fab create-app`

### ISSUE THREAD

**Issue by agxc** [dpgaspar/Flask-AppBuilder#2122]
### Environment

Flask-Appbuilder version:
pip show Flask-AppBuilder
Name: Flask-AppBuilder
Version: 4.3.7

pip freeze output:
apispec==6.3.0
attrs==23.1.0
Babel==2.12.1
blinker==1.6.2
click==8.1.7
colorama==0.4.6
Deprecated==1.2.14
dnspython==2.4.2
email-validator==1.3.1
Flask==2.3.3
Flask-AppBuilder==4.3.7
Flask-Babel==2.0.0
Flask-JWT-Extended==4.5.2
Flask-Limiter==3.5.0
Flask-Login==0.6.2
Flask-SQLAlchemy==2.5.1
Flask-WTF==1.2.0
greenlet==2.0.2
idna==3.4
importlib-resources==6.1.0
itsdangerous==2.1.2
Jinja2==3.1.2
jsonschema==4.19.1
jsonschema-specifications==2023.7.1
limits==3.6.0
markdown-it-py==3.0.0
MarkupSafe==2.1.3
marshmallow==3.20.1
marshmallow-sqlalchemy==0.26.1
mdurl==0.1.2
ordered-set==4.1.0
packaging==23.2
prison==0.2.1
Pygments==2.16.1
PyJWT==2.8.0
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
referencing==0.30.2
rich==13.6.0
rpds-py==0.10.3
six==1.16.0
SQLAlchemy==1.4.49
SQLAlchemy-Utils==0.41.1
typing_extensions==4.8.0
Werkzeug==3.0.0
wrapt==1.15.0
WTForms==3.0.1
### Describe the expected results
I tried to use `flask fab create-app` to start the template as suggested in the documentation:
https://flask-appbuilder.readthedocs.io/en/latest/installation.html

Tell us what should happen:
I ran the code 
$ flask fab create-app

```python
Paste a minimal example that causes the problem.
```
flask fab create-app not working as expected

### Describe the actual results

Tell us what happens instead.

```pytb
Paste the full traceback if there was an exception.
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\codelib\virtualenv\flask-app-data-viwer\venv\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "D:\codelib\virtualenv\flask-app-data-viwer\venv\Lib\site-packages\flask\cli.py", line 1064, in main
    cli.main()
  File "D:\codelib\virtualenv\flask-app-data-viwer\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\codelib\virtualenv\flask-app-data-viwer\venv\Lib\site-packages\click\core.py", line 1682, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\codelib\virtualenv\flask-app-data-viwer\venv\Lib\site-packages\click\core.py", line 1729, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\codelib\virtualenv\flask-app-data-viwer\venv\Lib\site-packages\flask\cli.py", line 566, in get_command
    self._load_plugin_commands()
  File "D:\codelib\virtualenv\flask-app-data-viwer\venv\Lib\site-packages\flask\cli.py", line 561, in _load_plugin_commands
    self.add_command(ep.load(), ep.name)
                     ^^^^^^^^^
  File "C:\Users\gcao\AppData\Local\Programs\Python\Python311\Lib\importlib\metadata\__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gcao\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\codelib\virtualenv\flask-app-data-viwer\venv\Lib\site-packages\flask_appbuilder\__init__.py", line 5, in <module>
    from .api import ModelRestApi  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\codelib\virtualenv\flask-app-data-viwer\venv\Lib\site-packages\flask_appbuilder\api\__init__.py", line 78, in <module>
    from ..security.decorators import permission_name, protect
  File "D:\codelib\virtualenv\flask-app-data-viwer\venv\Lib\site-packages\flask_appbuilder\security\decorators.py", line 24, in <module>
    from flask_login import current_user
  File "D:\codelib\virtualenv\flask-app-data-viwer\venv\Lib\site-packages\flask_login\__init__.py", line 12, in <module>
    from .login_manager import LoginManager
  File "D:\codelib\virtualenv\flask-app-data-viwer\venv\Lib\site-packages\flask_login\login_manager.py", line 33, in <module>
    from .utils import _create_identifier
  File "D:\codelib\virtualenv\flask-app-data-viwer\venv\Lib\site-packages\flask_login\utils.py", line 14, in <module>
    from werkzeug.urls import url_decode
ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (D:\codelib\virtualenv\flask-app-data-viwer\venv\Lib\site-packages\werkzeug\urls.py)
(venv) 

### Steps to reproduce
```
python -m venv venv
pip install Flask-AppBuilder
flask fab create-app
```

**Comment by agxc** [comment]
Issue resolved by change `werkzeug` version in the requirements.txt

werkzeug==2.3.7
