### ISSUE TITLE
Issue: Cannot define schema when customising security models

### ISSUE THREAD

**Issue by agxc** [dpgaspar/Flask-AppBuilder#2125]
### Environment
python 3.11.4

Flask-Appbuilder version:
Flask-AppBuilder==4.3.7
SQL Server 2016

### Describe the expected results

Our organisation requires storing security related tables such as the `ab_*` tables automatically created by FAB in a designated schema (e.g. SecurityGroup). 

So we expect tables to be saved in `SecurityGroup.ab_role, SecurityGroup.ab_permission_view` etc. Due to this reason, we cannot use flask_appbuilder. 

However, we struggle to modify the underlying schema for the table due to its currently structure when we try to customise security tables following the document in the link here: 

https://flask-appbuilder.readthedocs.io/en/latest/security.html#your-custom-security

```python
# app/sec_models.py

from flask_appbuilder.security.sqla.models import Permission, ViewMenu, Role, PermissionView, User, RegisterUser, Model
from sqlalchemy import Column, Integer, ForeignKey, Sequence, String, DateTime, Boolean, Table, UniqueConstraint
from sqlalchemy.ext.declarative import declared_attr

SCHEMA = 'SecurityGroup'


class CustomPermission(Permission):
    __tablename__   = "ab_permission"
    __table_args__  = {'schema': SCHEMA, 'extend_existing': True}


assoc_permissionview_role = Table(
    f"{SCHEMA}.ab_permission_view_role",
    Model.metadata,
    Column("id", Integer, Sequence("ab_permission_view_role_id_seq"), primary_key=True),
    Column("permission_view_id", Integer, f"{SCHEMA}.ab_permission_view.id"),
    Column("role_id", Integer, f"{SCHEMA}.ab_role.id"),
    UniqueConstraint("permission_view_id", "role_id")
)

# other code to add SCHEMA prefix to tables
```

### Describe the actual results

when I run `db.create_all()` via the `python manage.py recreate_db` command, I expect those security related `ab_*` tables automatically created within the `SecurityGroup` schema.

However, in SQLAlchemy, when a class inherits from another ORM class and doesn't define its own table, it is treated as a single table inheritance. In this model, SQLAlchemy expects both classes to operate on the same table. If the subclass tries to define or modify table details like __table_args__ without defining its own table, it raises the error provided above. 

However, I cannot  let the default behaviour to create a set of empty tables since I cannot overwrite the default behaviour when it comes to creating new tables. 

```pytb
Traceback (most recent call last):
  File "D:\codelib\virtualenv\flask-app-viewer\manage.py", line 5, in <module>
    from app import create_app, db,  data
  File "D:\codelib\virtualenv\flask-app-viewer\app\__init__.py", line 19, in <module>
    from .sec import MySecurityManager
  File "D:\codelib\virtualenv\flask-app-viewer\app\sec.py", line 3, in <module>
    from .sec_models import (
  File "D:\codelib\virtualenv\flask-app-viewer\app\sec_models.py", line 27, in <module>
    class CustomPermission(Permission):
  File "C:\Users\gcao\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_sqlalchemy\model.py", line 67, in __init__
    super(NameMetaMixin, cls).__init__(name, bases, d)
  File "C:\Users\gcao\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_sqlalchemy\model.py", line 121, in __init__
    super(BindMetaMixin, cls).__init__(name, bases, d)
  File "C:\Users\gcao\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\decl_api.py", line 76, in __init__
    _as_declarative(reg, cls, dict_)
  File "C:\Users\gcao\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 126, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gcao\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 183, in setup_mapping
    return cfg_cls(registry, cls_, dict_, table, mapper_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gcao\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 333, in __init__
    self._setup_inheritance(mapper_kw)
  File "C:\Users\gcao\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 935, in _setup_inheritance
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Can't place __table_args__ on an inherited class with no table.
```

### Steps to reproduce
Follow the link below to step custom-security. Try to extend the schema setting to the table as shown below:

# sec_model.py
class CustomPermission(Permission):
    __tablename__   = "ab_permission"
    __table_args__  = {'schema': SCHEMA, 'extend_existing': True}

# sec.py
from .sec_models import CustomPermission 
from flask_appbuilder.security.sqla.manager import SecurityManager

class MySecurityManager(SecurityManager):
  
    permission_model = CustomPermission
    # Add changes to other models

https://flask-appbuilder.readthedocs.io/en/latest/security.html#your-custom-security

**Comment by agxc** [comment]
We've identified a workaround by setting a default schema and restrict it to other users. The database is only used for the app.
