### ISSUE TITLE
Fabmanager and appbuilder both throw type error on Python 3.4.3 / windows 7

### ISSUE THREAD

**Issue by colost8rams** [dpgaspar/Flask-AppBuilder#220]
whenever I try to run fabmanager or any of the examples, appbuilder throws a typeerror with the following hideous looking traceback:

    Traceback (most recent call last):
      File "C:\Code\Projects\Flask-AppBuilder-Skeleton-master\run.py", line 1, in <module>
        from app import app
      File "C:\Code\Projects\Flask-AppBuilder-Skeleton-master\app\__init__.py", line 3, in <module>
        from flask.ext.appbuilder import SQLA, AppBuilder
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
     File "C:\Python34\lib\site-packages\flask\exthook.py", line 62, in load_module
        __import__(realname)
      File "C:\Python34\lib\site-packages\flask_appbuilder\__init__.py", line 5, in <module>
        from .base import AppBuilder
      File "C:\Python34\lib\site-packages\flask_appbuilder\base.py", line 4, in <module>
        from .views import IndexView, UtilView
      File "C:\Python34\lib\site-packages\flask_appbuilder\views.py", line 6, in <module>
        from .baseviews import BaseView, BaseCRUDView, BaseFormView, expose, expose_api
      File "C:\Python34\lib\site-packages\flask_appbuilder\baseviews.py", line 3, in <module>
        from .forms import GeneralModelConverter
      File "C:\Python34\lib\site-packages\flask_appbuilder\forms.py", line 15, in <module>
        from .upload import (BS3FileUploadFieldWidget,
      File "C:\Python34\lib\site-packages\flask_appbuilder\upload.py", line 6, in <module>
        from flask.ext.babelpkg import gettext
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
      File "C:\Python34\lib\site-packages\flask\exthook.py", line 62, in load_module
        __import__(realname)
      File "C:\Python34\lib\site-packages\flask_babelpkg\__init__.py", line 21, in <module>
        from babel import dates, numbers, support, Locale
      File "C:\Python34\lib\site-packages\babel\dates.py", line 28, in <module>
        from babel.util import UTC, LOCALTZ
      File "C:\Python34\lib\site-packages\babel\util.py", line 278, in <module>
        from babel import localtime
      File "C:\Python34\lib\site-packages\babel\localtime\__init__.py", line 21, in <module>
        from babel.localtime._win32 import _get_localzone
      File "C:\Python34\lib\site-packages\babel\localtime\_win32.py", line 18, in <module>
        tz_names = get_global('windows_zone_mapping')
      File "C:\Python34\lib\site-packages\babel\core.py", line 58, in get_global
        _global_data = pickle.load(fileobj)
    TypeError: an integer is required (got type str)
    [Finished in 0.8s with exit code 1]
    [shell_cmd: python -u "C:\Code\Projects\Flask-AppBuilder-Skeleton-master\run.py"]
    [dir: C:\Code\Projects\Flask-AppBuilder-Skeleton-master]

The above was from running the skeleton, but I get the same traceback just trying to run `fabmanager create-app --help` in Powershell.  I am running a fresh install of Python 3.4.3 under windows 7. is this a known issue?

**Comment by michalfita** [comment]
It seems the babel package loads some binary data using unpickler... however as far as I know this is not platform independent. So if you're using the version of Python under Windows with which the Babel hasn't been tested, then this could be - unfortunately for you - a problem.

Is it your fresh installation of Python? If not try to update Babel package.

**Comment by colost8rams** [comment]
it seems to be babel.  I have tried fresh installs of both python 3.3 (which according to pypi, babel should support) and python 3.4 using the most up to date version of babel.  I have opened a ticket on the babel page.

**Comment by colost8rams** [comment]
OK, I have tracked down the issue in babel.  It is an incompatibility issue between pickle objects made in python 2 being loaded in python 3.  Here's the babel issue: https://github.com/mitsuhiko/babel/issues/174
and the corresponding python issue: http://bugs.python.org/issue13505

a quick workaround is to install the github branch of babel 2.0.  so after installing flask-appbuilder, I `pip uninstall babel` and then `pip install git+https://github.com/mitsuhiko/babel.git@2.0` and ... so far so good.  seems the global_data on the pypi distribution was pickled in python 2 whereas the one on the github branch was pickled with python 3.

**Comment by dpgaspar** [comment]
Thanks everyone!
