### ISSUE TITLE
Don't work docs

### ISSUE THREAD

**Issue by bekishev04** [dpgaspar/Flask-AppBuilder#2283]
I send a request to `/api/v1/_openapi `and get 500.

Trace:

```
ERROR:flask_appbuilder.api:'str' object has no attribute 'update'
Traceback (most recent call last):
  File "/Users/matvei/Desktop/Work/Lexie/turbocash-backend/venv/lib/python3.10/site-packages/flask_appbuilder/api/__init__.py", line 111, in wraps
    return f(self, *args, **kwargs)
  File "/Users/matvei/Desktop/Work/Lexie/turbocash-backend/venv/lib/python3.10/site-packages/flask_appbuilder/api/manager.py", line 60, in get
    base_api.add_api_spec(api_spec)
  File "/Users/matvei/Desktop/Work/Lexie/turbocash-backend/venv/lib/python3.10/site-packages/flask_appbuilder/api/__init__.py", line 574, in add_api_spec
    self.operation_helper(
  File "/Users/matvei/Desktop/Work/Lexie/turbocash-backend/venv/lib/python3.10/site-packages/flask_appbuilder/api/__init__.py", line 683, in operation_helper
    operation_spec.update(override_method_spec.get(method.lower(), {}))
AttributeError: 'str' object has no attribute 'update'
127.0.0.1 - - [31/Oct/2024 20:07:31] "GET /api/v1/_openapi HTTP/1.1" 500 490 0.289405

```

For some reason, in the line `operation_spec.update(override_method_spec.get(method.lower(), {}))` the type string "None" is coming. 
File /flask_appbuilder/api/__init__.py " line 683

Python 3.10
Flask-AppBuilder          4.5.1

**Comment by Yoyasp** [comment]
I'm pretty sure that one of your openapi doc strings is misformatted or the `openapi_spec_methods attribute` is, without the code we cannot help you.
What you could try to identify the incorrect docstring is run your code in a debugger and catch the exception to see which docstring is the culprit.

**Comment by bekishev04** [comment]
> I'm pretty sure that one of your openapi doc strings is misformatted or the `openapi_spec_methods attribute` is, without the code we cannot help you. What you could try to identify the incorrect docstring is run your code in a debugger and catch the exception to see which docstring is the culprit.

You are right, in the project that I launched, there are many places where docstrings are not filled in. But why should all documentation fall because of it? Especially without specifying a specific reason and a line of code?  In my opinion, either this should work without some endpoints, or identify problems.

**Comment by Yoyasp** [comment]
In my own projects i have some endpoints that are not documented aswell, this doesnt give this error.
Your code is failing on the `.update()` function which is expecting `operation_spec` to not be a string.
This code only gets executed if there is a doc string. Therefor my assumption is that you have a doc string, but it is malformed in some way.

**Comment by bekishev04** [comment]
Yes, you're right, but this is clearly not what I expect from a framework when someone makes a mistake in one character, and the entire documentation crashes, even without a link to the error.
