### ISSUE TITLE
if current_user.is_authenticated(): TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#235]
HI All,
Something has changed in my installation and now none of my appbuilder apps run. They all have the following error as soon as I hit the url, before the login screen is displayed. Can anyone tell me what is wrong?
Thanks!

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Python27\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\lib\site-packages\flask_appbuilder\views.py", line 27, in index
    appbuilder=self.appbuilder)
  File "C:\Python27\lib\site-packages\flask_appbuilder\baseviews.py", line 156, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "C:\Python27\lib\site-packages\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "C:\Python27\lib\site-packages\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask_appbuilder\templates\appbuilder\index.html", line 1, in top-level template code
    {% extends "appbuilder/base.html" %}
  File "C:\Python27\lib\site-packages\flask_appbuilder\templates\appbuilder\base.html", line 1, in top-level template code
    {% extends base_template %}
  File "C:\Python27\lib\site-packages\flask_appbuilder\templates\appbuilder\baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "C:\Python27\lib\site-packages\flask_appbuilder\templates\appbuilder\init.html", line 46, in top-level template code
    {% block body %}
  File "C:\Python27\lib\site-packages\flask_appbuilder\templates\appbuilder\baselayout.html", line 8, in block "body"
    {% block navbar %}
  File "C:\Python27\lib\site-packages\flask_appbuilder\templates\appbuilder\baselayout.html", line 10, in block "navbar"
    {% include 'appbuilder/navbar.html' %}
  File "C:\Python27\lib\site-packages\flask_appbuilder\templates\appbuilder\navbar.html", line 29, in top-level template code
    {% include 'appbuilder/navbar_menu.html' %}
  File "C:\Python27\lib\site-packages\flask_appbuilder\templates\appbuilder\navbar_menu.html", line 11, in top-level template code
    {% if item1 | is_menu_visible %}
  File "C:\Python27\lib\site-packages\flask_appbuilder\filters.py", line 118, in is_menu_visible
    return self.security_manager.has_access("menu_access", item.name)
  File "C:\Python27\lib\site-packages\flask_appbuilder\security\manager.py", line 709, in has_access
    if current_user.is_authenticated():
TypeError: 'bool' object is not callable

**Comment by dpgaspar** [comment]
please uninstall flask-login and install it again pinned to version 0.2.11. flask-login has changed...

If you need any further help on this, please reopen the issue.

**Comment by AustinJim** [comment]
Thanks Daniel. That got me past this issue but I've run into another. I'm wondering if I need to completely reinstall Flask from an older version. If so, can you tell me which version? My current problem is this:

File "C:\Python27\lib\site-packages\flask\app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Python27\lib\site-packages\flask\app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "C:\Python27\lib\site-packages\flask\app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "C:\Python27\lib\site-packages\flask\app.py", line 1478, in full_dispatch_request
response = self.make_response(rv)
File "C:\Python27\lib\site-packages\flask\app.py", line 1566, in make_response
raise ValueError('View function did not return a response')
ValueError: View function did not return a response

Thanks!

**Comment by valVk** [comment]
now it's not method but property

you can use it as `current_user.is_authenticated`

**Comment by Patrickctyyx** [comment]
Thanks valVk! Problem solved!

**Comment by fordguo** [comment]
the last flask-login is 0.4.1 and when will update to latest?
