### ISSUE TITLE
Help needed adding new users automatically with LDAP authentication.

### ISSUE THREAD

**Issue by MrKriss** [dpgaspar/Flask-AppBuilder#273]
By following the process outlined in #158 ,(i.e. creating an admin user with credentials that are the same as one which can be looked up via LDAP), I have managed to get LDAP authentication working for an admin Role, though in the docs it suggests that other users will be automatically added to the user table in the database and this does not seem to happen "out of the box". I was wondering if there's something that I've missed. Here is what I have tried so far:

## Using Setting in the Config File 

In the config I tried setting the following:

```
AUTH_ROLE_PUBLIC = 'Public'
AUTH_USER_REGISTRATION = True
```

Though then encountered the error:

```
>>> python run.py
2015-11-09 15:46:29,759:INFO:flask_appbuilder.security.sqla.manager:Security DB not found Creating all Models from Base
2015-11-09 15:46:30,914:INFO:flask_appbuilder.security.sqla.manager:Security DB Created
2015-11-09 15:46:31,017:INFO:flask_appbuilder.security.sqla.manager:Inserted Role: Admin
2015-11-09 15:46:31,141:INFO:flask_appbuilder.security.sqla.manager:Inserted Role: Public
2015-11-09 15:46:31,144:WARNING:flask_appbuilder.security.manager:No user yet created, use fabmanager command to do it.
2015-11-09 15:46:31,147:INFO:flask_appbuilder.base:Registering class IndexView on menu
2015-11-09 15:46:31,272:INFO:flask_appbuilder.base:Registering class UtilView on menu
2015-11-09 15:46:31,392:INFO:flask_appbuilder.base:Registering class LocaleView on menu
2015-11-09 15:46:31,529:INFO:flask_appbuilder.base:Registering class NoneType on menu
Was unable to import app Error: 'NoneType' object has no attribute 'appbuilder'
```

On tracing this back it seems there is no register user view for LDPA defined by default, and this causes the following line to return 'None' 
https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/manager.py#L391

Do I need to define my own register user view for LDAP?

**Comment by dpgaspar** [comment]
Have you tried to login using a valid LDAP user?

LDAP does not have a specific view like the other auth methods, it will register automatically all the users using LDAP properties, after validating it's credential (of course).

**Comment by MrKriss** [comment]
From the logs it appeared that credentials for valid users were found when querying the LDAP server, but the procedure failed after that due to usernames not appearing in the database on the flask app builder side. I am connecting using a proxy user to the LDAP server that then has read access to look up individual credentials. Could this be why the database is not updated on the flask app builder side?

**Comment by dpgaspar** [comment]
Your logs have this error:

      Was unable to import app Error: 'NoneType' object has no attribute 'appbuilder'

If you run::

    $ python run.py

what errors do you have? Is your app up and running?

**Comment by dpgaspar** [comment]
Were you able to solve this?

**Comment by mtrbean** [comment]
We are also running into the same problem once we have LDAP enabled with `AUTH_USER_REGISTRATION = True`. 

> LDAP does not have a specific view like the other auth methods, it will register automatically all the users using LDAP properties, after validating it's credential (of course).

From reading the [code](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/manager.py#L603), this is only true if `AUTH_USER_REGISTRATION` is set to True. But turning this option on will trigger the [error](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/manager.py#L391) that @MrKriss reported.

**Comment by mogthesprog** [comment]
Yeah just to confirm, i'm seeing the same error as @MrKriss when trying to solve the same ldap auth problem with caravel. 

```
Traceback (most recent call last):
  File "/bin/caravel", line 15, in <module>
    import caravel
  File "/usr/lib/python2.7/site-packages/caravel/__init__.py", line 43, in <module>
    security_manager_class=app.config.get("CUSTOM_SECURITY_MANAGER"))
  File "/usr/lib64/python2.7/site-packages/flask_appbuilder/base.py", line 130, in __init__
    self.init_app(app, session)
  File "/usr/lib64/python2.7/site-packages/flask_appbuilder/base.py", line 156, in init_app
    self._add_admin_views()
  File "/usr/lib64/python2.7/site-packages/flask_appbuilder/base.py", line 253, in _add_admin_views
    self.sm.register_views()
  File "/usr/lib64/python2.7/site-packages/flask_appbuilder/security/sqla/manager.py", line 69, in register_views
    super(SecurityManager, self).register_views()
  File "/usr/lib64/python2.7/site-packages/flask_appbuilder/security/manager.py", line 391, in register_views
    self.appbuilder.add_view_no_menu(self.registeruser_view)
  File "/usr/lib64/python2.7/site-packages/flask_appbuilder/base.py", line 412, in add_view_no_menu
    baseview.appbuilder = self
AttributeError: 'NoneType' object has no attribute 'appbuilder'
```

**Comment by mtrbean** [comment]
I managed to work around this issue by monkey patching:

```
from flask.ext.appbuilder import AppBuilder

_orig_add_view_no_menu = AppBuilder.add_view_no_menu

def add_view_no_menu_check(self, baseview, endpoint=None, static_folder=None):
    if baseview is not None:
        return _orig_add_view_no_menu(self, baseview, endpoint, static_folder)
AppBuilder.add_view_no_menu = add_view_no_menu_check
```
