### ISSUE TITLE
Cannot add my own Forms - view_menu error? 

### ISSUE THREAD

**Issue by bwilkinsSG** [dpgaspar/Flask-AppBuilder#315]
My code may be completely off, as I've been changing everything trying to get it to work.

Essentially I need to create a page that will allow me to upload a .csv file that will populate a table. I will then add this data to my database. However, I cannot get my forms to work at all!

Some relevant code-

views.py
```
class addclass(SimpleFormView):
    form_title = 'Sample Upload'
    form = UploadedSampleForm

    @has_access
    def form_get(self, form):
        return self.render_template('samples.html')

    @has_access
    def form_post(self, form):
        # Check which 'submit' button was called to validate the correct form
        if 'addclass' in request.form and form.validate_on_submit():

            return self.render_template('samples.html', form=form)

        if 'upload' in request.form and form.validate_on_submit():

            # overwrite the sampleform by populating it with values read from file
            upsamform = PopulateFormFromFile()

            return self.render_template('samples.html', form=form)

        else:
            return self.render_template('samples.html')

def PopulateFormFromFile():

    upsamform = UploadedSampleForm()

    #grab .csv from fileselect and read data
    csvupload = request.files['csvup']
    stream = io.StringIO(csvupload.stream.read().decode("UTF8"))
    reader = csv.reader(stream, delimiter=',')

    # pop off any blank fields already in student info
    while len(upsamform.samples) > 0:
        upsamform.samples.pop_entry()
    for row in reader:
        # populate lists with data from .csv
        sampleform = SampleForm()
        sampleform.custsample_id = row[0]
        sampleform.type_sample = row[1]
        sampleform.analysis_type = row[2]
        sampleform.conc_sample = row[3]

        upsamform.samples.append_entry(sampleform)

    return upsamform

@appbuilder.app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html', base_template=appbuilder.base_template, appbuilder=appbuilder), 404


appbuilder.add_view(addclass, "Add Samples", category="Add Samples")
appbuilder.add_view(GroupMasterView, "Customers", icon="fa-folder-open-o", category="Data Tracking")
appbuilder.add_separator("Data Tracking")
appbuilder.add_view(GroupGeneralView, "Manage Customers", icon="fa-folder-open-o", category="Data Tracking")
appbuilder.add_view(ContactGeneralView, "List Samples", icon="fa-envelope", category="Data Tracking")
appbuilder.security_cleanup()
```

samples.html
```
{% extends "appbuilder/base.html" %}
{% block content %}
{% if fileform %}
        <div align="center">
            <p>Add class from file:</p>

            <form action="" method="post" enctype="multipart/form-data" name="fileform">
                {{ fileform.hidden_tag() }}
                <p><input type="file" name="csvup" value="csvup"></p>
                <p><input type="submit" name="upload" value="Upload"></p>
            </form>
        </div>
        <hr>
        {% endif %}
        <div align="center">
            <form action="" method="post" name="sampleform">
                {{ upsamform.hidden_tag() }}
                Customer: {{ upsamform.company }}<br>
                Extracted by: {{ upsamform.extract }}<br>
                <br>
                <div>
                    <table>
                        <tr>
                            <th> Customer Sample ID </th>
                            <th> Sample Type </th>
                            <th> Analysis Type </th>
                            <th> Concentration/Cell# </th>
                        </tr>
                        {% for sample in upsamform.samples %}
                        <tr>
                            <td>{{ sample.custsample_id }}</td>
                            <td>{{ sample.type_sample }}</td>
                            <td>{{ sample.analysis_type }}</td>
                            <td>{{ sample.conc_sample }}</td>

                        </tr>
                        {% endfor %}
                    </table>
                </div>
                <p><input type="submit" name="addclass" value="Add Class"></p>
            </form>
        </div>
{% endblock %}
```

forms.py
```
from flask_wtf import Form
from wtforms.validators import DataRequired
from wtforms import StringField, SelectField, FieldList, FormField
from flask_appbuilder.forms import DynamicForm
from flask_appbuilder.fieldwidgets import BS3TextFieldWidget, Select2Widget

class FileUploadForm(DynamicForm):
    pass


class SampleForm(DynamicForm):
    custsample_id = StringField('Customer Sample ID', validators=[DataRequired()], widget=BS3TextFieldWidget())
    type_sample = StringField('Sample Type', validators=[DataRequired()], widget=BS3TextFieldWidget())
    analysis_type = StringField('Analysis Type', validators=[DataRequired()],
widget=BS3TextFieldWidget())
    conc_sample = StringField('Concentration/Cell#', validators=[DataRequired()], widget=BS3TextFieldWidget())




class UploadedSampleForm(DynamicForm):
    company = SelectField('companyname',
                      choices=[(1, "Cust1"), (2, "Cust2"), (3, "Cust3"), (4, "Cust4"), (5, "Cust5")],
                      coerce=str)

    extract = SelectField('techextract',
                          choices=[(1, "BW"), (2, "DV"), (3, "WN"), (4, "YS"), (5, "CH")],
                          coerce=str)

    samples = FieldList(FormField(SampleForm), min_entries=5)  # show at least 5 blank fields by default
```

**Comment by bwilkinsSG** [comment]
traceback is as follows!

```
Traceback (most recent call last):
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask_appbuilder/views.py", line 27, in index
    appbuilder=self.appbuilder)
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 157, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Volumes/BWILKINS/SGdatastore/app/templates/index.html", line 1, in top-level template code
    {% extends "appbuilder/base.html" %}
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 8, in block "body"
    {% block navbar %}
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 10, in block "navbar"
    {% include 'appbuilder/navbar.html' %}
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/navbar.html", line 29, in top-level template code
    {% include 'appbuilder/navbar_menu.html' %}
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/navbar_menu.html", line 11, in top-level template code
    {% if item1 | is_menu_visible %}
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask_appbuilder/filters.py", line 118, in is_menu_visible
    return self.security_manager.has_access("menu_access", item.name)
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 714, in has_access
    return self._has_view_access(g.user, permission_name, view_name)
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 705, in _has_view_access
    if (view_name == permission.view_menu.name) and (permission_name == permission.permission.name):
  File "/Users/bwilkins/.virtualenvs/sgeneticsdb/lib/python2.7/site-packages/bson/dbref.py", line 85, in __getattr__
    raise AttributeError(key)
AttributeError: view_menu
```

**Comment by dpgaspar** [comment]
Sorry, not much time to look at your code on detail... Have you seen this: http://flask-appbuilder.readthedocs.io/en/latest/quickfiles.html#model-views-with-files-and-images

You can use a 'special' type of Column name FileColumn. Then you can catch the pre_add or pre_update, to do what ever you want.

Is this a possibility for you use case?

**Comment by KibodWapon** [comment]
hi all i'v solved this issue  by dropping the user role permission collections  in mongo db.
then recreate the db  C:\Python37\Scripts\fabmanager.exe      create-admin。
The role db has broken!

**Comment by KibodWapon** [comment]
finally i got steps to trigger this bug:
1.add an action abc to your view
2.run your webapp----  action's permission will insert into your db
3.remove you aciton abc code from view
4. run you webapp

`2020-03-15 12:03:50,130:DEBUG:flask_appbuilder.security.manager:State transitions: {'add': {}, 'del_role_pvm': set(), 'del_views': set(), 'del_perms': set()}
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\bson\dbref.py", line 83, in __getattr__
    return self.__kwargs[key]
KeyError: 'view_menu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/win7_d/other_project/Host17098401336/HostcrackerWeb_dev/run.py", line 1, in <module>
    from app import app
  File "F:\win7_d\other_project\Host17098401336\HostcrackerWeb_dev\app\__init__.py", line 17, in <module>
    from app import views
  File "F:\win7_d\other_project\Host17098401336\HostcrackerWeb_dev\app\views.py", line 382, in <module>
    appbuilder.security_cleanup()
  File "F:\win7_d\other_project\Host17098401336\HostcrackerWeb_dev\flask_appbuilder\base.py", line 539, in security_cleanup
    self.sm.security_cleanup(self.baseviews, self.menu)
  File "F:\win7_d\other_project\Host17098401336\HostcrackerWeb_dev\flask_appbuilder\security\manager.py", line 1245, in security_cleanup
    self.security_converge(baseviews, menus)
  File "F:\win7_d\other_project\Host17098401336\HostcrackerWeb_dev\flask_appbuilder\security\manager.py", line 1392, in security_converge
    (pvm.view_menu.name, pvm.permission.name)
  File "C:\Python37\lib\site-packages\bson\dbref.py", line 85, in __getattr__
    raise AttributeError(key)
AttributeError: view_menu
`
