### ISSUE TITLE
Initialisation using the app factory pattern, requires request context

### ISSUE THREAD

**Issue by MichaelPereira** [dpgaspar/Flask-AppBuilder#367]
Hi,

I've run into a problem while migrating our internal flask app to use appbuilder, which is related to #25:
When using the [flask app factory pattern](http://flask.pocoo.org/docs/0.11/patterns/appfactories/) in the following way:
- the appbuilder variable is a global variable declared (but not initialized) the following way:

``` python
from flask.ext.appbuilder import AppBuilder
from app.index import MyIndexView

appbuilder = AppBuilder(indexview=MyIndexView)
```
- the appbuilder initialize the application in a `build_app()` method that looks like somewhat like this:

``` python
from app.config import LocalConfig
from app.db import db
from app.application_builder import appbuilder

def build_app(with_routes=True, config=None):
    app = Flask(__name__)
    app.config.from_object(LocalConfig)
    db.init_app(app)
    appbuilder.init_app(app, db.session)
```

When initialized in a docker container, the uwsgi app fails to load with the following error:

```
Traceback (most recent call last):
  File "/src/app/uwsgi.py", line 3, in <module>
    app = build_app()
  File "./app/application.py", line 45, in build_app
    appbuilder.init_app(app, db.session)
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/base.py", line 151, in init_app
    self.sm = self.security_manager_class(self)
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/security/sqla/manager.py", line 39, in __init__
    super(SecurityManager, self).__init__(appbuilder)
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/security/manager.py", line 166, in __init__
    app.config.setdefault('AUTH_ROLE_ADMIN', 'Admin')
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/dist-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.
2016-08-10T19:13:28.140910748Z 
This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
unable to load app 0 (mountpoint='') (callable not found or import error)
```

Then if I change the `build_app()` method to initialize appbuilder in the app context: 

``` python
from app.config import LocalConfig
from app.db import db
from app.application_builder import appbuilder

def build_app(with_routes=True, config=None):
    app = Flask(__name__)
    app.config.from_object(LocalConfig)
    db.init_app(app)
    with app.app_context():
        appbuilder.init_app(app, db.session)
```

The application now fails with the following stack trace that seems to indicate that the appbuilder needs to be initialized in a request context instead of an app context because it tries to load locale settings to know what language to use to display the application.

```
Traceback (most recent call last):
  File "/src/app/uwsgi.py", line 3, in <module>
    app = build_app()
  File "./app/application.py", line 44, in build_app
    appbuilder.init_app(app, db.session)
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/base.py", line 156, in init_app
    self._add_admin_views()
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/base.py", line 253, in _add_admin_views
    self.sm.register_views()
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/security/sqla/manager.py", line 69, in register_views
    super(SecurityManager, self).register_views()
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/security/manager.py", line 429, in register_views
    category_label=_('Security'))
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/base.py", line 342, in add_view
    baseview = self._check_and_init(baseview)
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/base.py", line 294, in _check_and_init
    baseview = baseview()
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/views.py", line 438, in __init__
    super(ModelView, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/baseviews.py", line 624, in __init__
    super(BaseCRUDView, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/baseviews.py", line 395, in __init__
    self._init_properties()
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/baseviews.py", line 675, in _init_properties
    super(BaseCRUDView, self)._init_properties()
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/baseviews.py", line 423, in _init_properties
    self._gen_labels_columns(list_cols)
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/baseviews.py", line 405, in _gen_labels_columns
    if not self.label_columns.get(col):
  File "/usr/local/lib/python2.7/dist-packages/flask_babel/speaklater.py", line 21, in __len__
    return len(text_type(self))
  File "/usr/local/lib/python2.7/dist-packages/flask_babel/speaklater.py", line 18, in __str__
    return text_type(self._func(*self._args, **self._kwargs))
  File "/usr/local/lib/python2.7/dist-packages/flask_babel/__init__.py", line 539, in gettext
    t = get_translations()
  File "/usr/local/lib/python2.7/dist-packages/flask_babel/__init__.py", line 216, in get_translations
    catalog = support.Translations.load(dirname, [get_locale()])
  File "/usr/local/lib/python2.7/dist-packages/flask_babel/__init__.py", line 244, in get_locale
    rv = babel.locale_selector_func()
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/babel/manager.py", line 38, in get_locale
    locale = session.get('locale')
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/dist-packages/flask/globals.py", line 37, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.
2016-08-10T19:23:53.442901068Z 
This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
unable to load app 0 (mountpoint='') (callable not found or import error)
```

And now if I change the `build_app()` method to use a request context:

``` python
from app.config import LocalConfig
from app.db import db
from app.application_builder import appbuilder

def build_app(with_routes=True, config=None):
    app = Flask(__name__)
    app.config.from_object(LocalConfig)
    db.init_app(app)
    with app.test_request_context('/'):
        appbuilder.init_app(app, db.session)
```

The application initialize correctly.

Another way to avoid the problem is to not use the `init_app()` method and initialize the appbuilder this way:

``` python
from app.config import LocalConfig
from app.db import db
from app.application_builder import appbuilder
from flask.ext.appbuilder import AppBuilder,

def build_app(with_routes=True, config=None):
    app = Flask(__name__)
    app.config.from_object(LocalConfig)
    db.init_app(app)
    appbuilder = AppBuilder(app, db.session)
```

This means that there is a difference between using the [constructor](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/base.py#L92) and the [`init_app()`](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/base.py#L132) which I cannot see from the source code myself. Why would one way try to get the locale information and need a request context and not the other one?

Thanks for your help

**Comment by MichaelPereira** [comment]
Update:

Using the request context with `with app.test_request_context('/'):` completely breaks the views registration, so it's not a viable solution.
