### ISSUE TITLE
error calling /api for a RestCRUDView

### ISSUE THREAD

**Issue by Bengreen** [dpgaspar/Flask-AppBuilder#383]
When i try to call /api for RestCRUDView it fails because it cannot find .show.

```
2016-09-23 20:23:11,963:INFO:werkzeug:10.0.0.2 - - [23/Sep/2016 20:23:11] "GET /location_view/api/read HTTP/1.1" 200 -
2016-09-23 20:25:10,825:INFO:werkzeug:10.0.0.2 - - [23/Sep/2016 20:25:10] "GET /location_view/api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 52, in wraps
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/views.py", line 169, in api
    modelview_urls = self._get_modelview_urls()
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/views.py", line 157, in _get_modelview_urls
    modelview_urls['show'] = url_for(view_name + ".show", pk="")
  File "/usr/lib/python2.7/site-packages/flask/helpers.py", line 332, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1811, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/helpers.py", line 322, in url_for
    force_external=external)
  File "/usr/lib/python2.7/site-packages/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'location_view.show' with values ['pk']. Did you mean 'location_view.api' instead?
```

This implies I must have implementations for .show , etc which doesn't make sense for RestCRUDView which deliberately does not have them.

**Comment by Bengreen** [comment]
ALSO related to this is there a mechanism through which it is easy to extend the /api method to add more information?
I am thinking here that i would like to add more describing fields
