### ISSUE TITLE
LDAP issue logging into Superset (no attribute 'login_count')

### ISSUE THREAD

**Issue by dsimmie** [dpgaspar/Flask-AppBuilder#432]
I can't login to Superset with a user that is not registered in the DB. It is failing in the user registration code of fab.

My config entries:

```
AUTH_TYPE = 2
AUTH_LDAP_SERVER = "ldap://x.x.x.x"
AUTH_LDAP_SEARCH = "OU=someusers,OU=another,DC=somedomain,DC=com"
AUTH_LDAP_UID_FIELD = "userPrincipalName"
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = 'alpha'
```

I can get my AD details using the python-ldap library much like the code does in manager.py. The following code run against MSFT AD works fine:

```
import ldap
con =  ldap.initialize(AUTH_LDAP_SERVER)
con.bind_s("auser@somedomain.com", "pass")
con.search_s(AUTH_LDAP_SEARCH,ldap.SCOPE_SUBTREE,"userPrincipalName=auser@somedomain.com", ['givenName', 'sn', 'mail'])
```

But when I try to login I get following message:

Error:

```
2017-02-17 14:52:31,642:ERROR:flask_appbuilder.security.sqla.manager:Error adding new user to database. Can't flush None value found in collection User.roles
[2017-02-17 14:52:31,642] ERROR in app: Exception on /login/ [POST]
Traceback (most recent call last):
  File "/home/centos/anaconda2/envs/science2/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/centos/anaconda2/envs/science2/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/centos/anaconda2/envs/science2/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/centos/anaconda2/envs/science2/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/centos/anaconda2/envs/science2/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/centos/anaconda2/envs/science2/lib/python2.7/site-packages/flask_appbuilder/security/views.py", line 398, in login
    user = self.appbuilder.sm.auth_user_ldap(form.username.data, form.password.data)
  File "/home/centos/anaconda2/envs/science2/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 631, in auth_user_ldap
    self.update_user_auth_stat(user)
  File "/home/centos/anaconda2/envs/science2/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 488, in update_user_auth_stat
    if not user.login_count:
AttributeError: 'bool' object has no attribute 'login_count'
Exception on /login/ [POST]
```

I don't know why the user object is a bool.

* OS: Centos 7
* Flask appbuilder version 1.8.1

**Comment by rumbin** [comment]
I encountered the same problem which I filed in more detail at [https://github.com/airbnb/superset/issues/2190](https://github.com/airbnb/superset/issues/2190).

In summary, this issues exists in my case, when a combination of python 3.4 and pyldap is used.
In contrast, python 2.7 with python-ldap works flawlessly in this respect.
However, I would prefer to be able to run superset with python 3.4 for various other reasons…

**Comment by NeilHanlon** [comment]
For what it's worth, I was also having this issue, but it was being caused by a duplicate email entry... my admin user had the same email I was trying to login with. I don't think this is a problem with pyldap and python3.4, since that's the exact same setup I'm using.

**Comment by rumbin** [comment]
@NeilHanlon thanls for the hint. Unfortunately, this is not the reason in my case. However, while digging deeper, I found that there is a unique contstraint on the _email_ column in th _ab_user_ table.

@dsimmie I initially used the same way of configuring the auth method, i.e., `AUTH_TYPE = 2` in my config, which works flawlessly in my python 2.7 setup.
I now replaced that with 
```
from flask_appbuilder.security.manager import AUTH_OID, \
                                          AUTH_REMOTE_USER, \
                                          AUTH_DB, AUTH_LDAP, \
                                          AUTH_OAUTH, \
                                          AUTH_OAUTH
AUTH_TYPE = AUTH_LDAP
```
as recommended by the [docs ](http://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-methods).

Now I can log in with a new user, however, the new entry in the _ab_user_ table only shows a correct _username_, while the fileds for _first_name_, _last_name_ and _email_ are hex-encoded. I.e., my first name is stored as `\x5068696c697070`.

That is to say: It seems that I _nearly_ found a solution.

BTW: The new config still works flawlessly in my python 2.7 venv.

**Comment by juthikashenoy** [comment]
I am trying to integrate supersets with LDAP and running into this error - after login 
  File "/home/jshenoy/venv/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jshenoy/venv/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/jshenoy/venv/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jshenoy/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jshenoy/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jshenoy/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jshenoy/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jshenoy/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jshenoy/venv/lib/python2.7/site-packages/flask_appbuilder/security/views.py", line 402, in login
    user = self.appbuilder.sm.auth_user_ldap(form.username.data, form.password.data)
  File "/home/jshenoy/venv/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 622, in auth_user_ldap
    raise Exception("No ldap library for python.")
Exception: No ldap library for python.
Any Suggestions ?

**Comment by NeilHanlon** [comment]
Pip install ldap3

**Comment by tooptoop4** [comment]
has anyone solved this?
