### ISSUE TITLE
AngularJS front end

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#475]
Hi All,
I'm missing something fundamental and I'm hoping it will be obvious to you. I'm trying to write an AngularJS front end to the rest services. I've based it on the list_angularjs.html page in the quickhowto2 example. The angular controller and service are calling the rest service fine and getting back the typical FAB json object.
I've tried to simplify it as much as possible to show the problem.

**Angular Service**
```
 function readHeaders() {
      ApiService.read($scope.H_modelview_name,
                            $scope.H_base_url_read,
                            $scope.H_filter,
                            $scope.H_order_column,
                            $scope.H_order_direction,
                            $scope.H_page,
                            $scope.H_page_size)
    .then(function( data ) {
        $scope.H_data = data;
        console.log("$scope.H_data");
        console.log($scope.H_data);

  }
```

**HTML**
```

<div  ng-app="FAB" >
    <div ng-controller="SimpleTestCtrl" base="{{api_url}}">
        <div ng-repeat="obj in H_data.result">
              {{obj.Description}}
        </div>
    </div>
</div>
```
The problem is when the ng-repeat hits the reference to obj.Description it throws the error "UndefinedError: 'obj' is undefined".

This error is thrown in the Python, not javascript.
I do know that H_data.results IS being iterated over because if I simply put an X in the div it is displayed 40 times, which is the number of records in the rest results.

What am I missing?

Thanks!

**Comment by dpgaspar** [comment]
Could you post the full error trace from the server?

**Comment by AustinJim** [comment]
Hi Daniel, thanks for the reply.
The full stack trace is below. 
Thanks!
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Python27\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jicenhower\Google Drive\TXABCD\Permanent\Voting App\CarShow\app\views.py", line 212, in jsonexp
    active_filters=active_filters)
  File "C:\Python27\lib\site-packages\flask_appbuilder\baseviews.py", line 158, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "C:\Python27\lib\site-packages\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "C:\Python27\lib\site-packages\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jicenhower\Google Drive\TXABCD\Permanent\Voting App\CarShow\app\templates\list_angulajs.html", line 23, in top-level template code
    {{obj.Description}}
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 408, in getattr
    return getattr(obj, attribute)
UndefinedError: 'obj' is undefined

```

**Comment by AustinJim** [comment]
Well, I made some progress understand what is happening. The "dynamic" directive is setting the element's html to the result of the expression passed to the dynamic directive. So the following:
      `   <ul ng-repeat="header in H_data.result" dynamic="header['Description']"/>`
produces one of these for every record in H_Data.result, which is what I need:
```
<ul ng-repeat="header in H_data.result" dynamic="header['Description']" class="ng-scope ng-isolate-scope">
<span class="ng-scope">MGB/MGC – (Chrome Bumper( ’62 -‘74)  </span>
</ul>
```
Now my challenge is iterating over a DIFFERENT but related rest result to insert  a subset of the 2nd collection as <li> elements within each the <h1>.

I could also return all data as the result of a single rest call and output a H1 every time the description changes. I'm not sure which one is feasible with this combination of FAB and Angular.

And suggestions would be appreciated. 

Thanks

**Comment by dpgaspar** [comment]
Hi @AustinJim 

Not much experience with Angular really, made some experiments using FAB some time ago.

Remember, you can always write your own REST API endpoints side by side with FAB, to implement specific parts of your app.
