### ISSUE TITLE
related_views not defined, How to properly relate views?

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#485]
Here is my sample models and views, but when running Fabmanager, i have a ModelView not defined should it be in quotes? 

What am i missing?

here is the tracelog and code below

2017-06-13 08:10:33,572:INFO:flask_appbuilder.base:Registering class PermissionViewModelView on menu Permission on Views/Menus
```
Traceback (most recent call last):
  File "/home/afidegnum/PycharmProjects/myfab/app/__init__.py", line 31, in <module>
    from app import views, models
  File "/home/afidegnum/PycharmProjects/myfab/app/__init__.py", line 31, in <module>
    from app import views, models
  File "/home/afidegnum/PycharmProjects/myfab/app/views.py", line 13, in <module>
    class NewsView(ModelView):
  File "/home/afidegnum/PycharmProjects/myfab/app/views.py", line 18, in NewsView
    related_views = [MediaView]
NameError: name 'MediaView' is not defined
```

=============== models.py===========================
```
class News(Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(50), unique=True, nullable=False)
    body = Column(Text(50), unique=True, nullable=False)
    posted_date = Column(Date, default=today, nullable=False)

class Media(Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(50), unique=True, nullable=False)
    path = Column(String(250), unique=True, nullable=False)
    photo = Column(ImageColumn(thumbnail_size=(30, 30, True), size=(300, 300, True)))
    posted = Column(Date, default=today, nullable=False)
    publications = relationship("Publication")
    publications_id = Column(Integer, ForeignKey('publication.id'), nullable=False)
    news = relationship("News")
    news_id = Column(Integer, ForeignKey('news.id'), nullable=False)
    activities = relationship("Activity")
    activities_id = Column(Integer, ForeignKey('activity.id'), nullable=False)
    messages = relationship("Message")
    messages_id = Column(Integer, ForeignKey('message.id'), nullable=False)

    def photo_img(self):
        im = ImageManager()
        if self.photo:
            return Markup('<a href="' + url_for('MediaModelView.show', pk=str(self.id)) + \
                          '" class="thumbnail"><img src="' + im.get_url(self.photo) + \
                          '" alt="Photo" class="img-rounded img-responsive"></a>')
        else:
            return Markup('<a href="' + url_for('MediaModelView.show', pk=str(self.id)) + \
                          '" class="thumbnail"><img src="//:0" alt="Photo" class="img-responsive"></a>')

    def photo_img_thumbnail(self):
        im = ImageManager()
        if self.photo:
            return Markup('<a href="' + url_for('MediaModelView.show', pk=str(self.id)) + \
                          '" class="thumbnail"><img src="' + im.get_url_thumbnail(self.photo) + \
                          '" alt="Photo" class="img-rounded img-responsive"></a>')
        else:
            return Markup('<a href="' + url_for('MediaModelView.show', pk=str(self.id)) + \
                          '" class="thumbnail"><img src="//:0" alt="Photo" class="img-responsive"></a>')
```

=====================views.py===============================

[class NewsView(ModelView):
    datamodel = SQLAInterface(News)

    list_columns = ['name','posted_date']
    label_columns = {'name':'News Title', 'posted_date':'Posted On'}
    related_views = [MediaView]
    list_widget = ListThumbnail

class MediaView(ModelView):

    datamodel = SQLAInterface(Media)
    list_widget = ListThumbnail
    list_columns = ['name', 'photo', 'posted']

db.create_all()

appbuilder.add_view(NewsView, "News", icon="fa-folder-open-o", category="Admin")
appbuilder.add_view(MediaView, "News", icon="fa-folder-open-o", category="Admin")](url)

**Comment by afidegnum** [comment]
Additional info, i m using Python 2.7.12 on Ubuntu 16, 
DB Engine: Sqlite

**Comment by afidegnum** [comment]
I needed to shift MediaView class to the top!

**Comment by dpgaspar** [comment]
Thats it!
