### ISSUE TITLE
Dynamic Form has no attribute on master/detail view

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#488]
Hi, I m trying to set up a master/detail view on [This code on my repository ](https://github.com/afidegnum/myfab/blob/master/app/views.py#L10-L25)

this supposed to lead to a sinlge field to upload a photo but as the view appears, i have an error of `AttributeError: 'DynamicForm' object has no attribute 'news'`
Below is a traceback of the error. 

Can you please give a hint on how to fix this issue?

```
2017-06-14 05:27:03,561:INFO:werkzeug:127.0.0.1 - - [14/Jun/2017 05:27:03] "POST /mediaview/add?_flt_0_news=1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask_appbuilder/views.py", line 480, in add
    widget = self._add()
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 904, in _add
    self._fill_form_exclude_cols(exclude_cols, form)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 1007, in _fill_form_exclude_cols
    field = getattr(form, filter_key)
AttributeError: 'DynamicForm' object has no attribute 'news'

```

**Comment by dpgaspar** [comment]
Hi @afidegnum,

FAB will try to internally remove the 'news' field for Media form, on your NewsView, this is caused by the related_views "magic". Add it to the MediaView form fields (add, edit), is this feasible?

**Comment by afidegnum** [comment]
HI, i have made an update on the code, however i have 3 issues,

I wanted to have a master/detail edit form in such a way, a user can add content on set from the master page as this code

https://github.com/afidegnum/myfab/blob/master/app/views.py#L42-L52

but first i have an error of `Was unable to import app Error: 'Media.photo' `

i also tried to subclass Publication to `class PublicationView(ListMasterWidget):`  and had an error of 

`Was unable to import app Error: 'PublicationView' object has no attribute 'get_uninit_inner_views'
`
i also tried to change to `class PublicationView(MasterDetailView):`
i had a Media import error, 

can you please advise on that?

**Comment by dpgaspar** [comment]
I've cloned you're repo and see no errors, can you be more specific?

**Comment by afidegnum** [comment]
I have fixed it,.
