### ISSUE TITLE
ImageManager().generate_name()   takes 3 arguments. whats the 3rd argument?

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#501]
this is what i have come so far with modelview, but what is the missing 3rd argument do i suppose to add? 

```
class MyMediaView(ModelView):
    datamodel = SQLAInterface(Media)
    add_template = 'media_add.html'
    static_folder = 'static/appbuilder'

    @expose('/upload',  methods=['POST'])
    def upload_img(self):
        im = ImageManager()
        files = request.files['files']
        if files and im.is_file_allowed(files.filename):

            newname = im.generate_name(files.filename)
            mpath = config.IMG_UPLOAD_FOLDER + '/' + newname
            newname = im.save_image(newname, mpath)
        print newname
        return newname
```

**Comment by dpgaspar** [comment]
generate_name, takes an obj that is a WTF field, and request.files. It will actually not use obj.

you can call it using generate_name(None, files)

https://github.com/dpgaspar/Flask-AppBuilder/blob/af095ac4094d068fa2dd467bd01fa8b95d697fc1/flask_appbuilder/upload.py#L145

https://github.com/dpgaspar/Flask-AppBuilder/blob/af095ac4094d068fa2dd467bd01fa8b95d697fc1/flask_appbuilder/upload.py#L145

By default it will do this:

````
def uuid_namegen(file_data):
    return str(uuid.uuid1()) + '_sep_' + file_data.filename
```

You can define your own function and instantiate ImageManager with it. take a look at the constructor:

https://github.com/dpgaspar/Flask-AppBuilder/blob/af095ac4094d068fa2dd467bd01fa8b95d697fc1/flask_appbuilder/filemanager.py#L89

**Comment by afidegnum** [comment]
please can you look into this? 

```

    @expose('/upload',  methods=['POST'])
    def upload_img(self):
        im = ImageManager()
        files = request.files['files']
        if files and im.is_file_allowed(files.filename):
            sname = str(files)
            newname = im.generate_name(None, files)
            mpath = config.IMG_UPLOAD_FOLDER + '/' + newname
            newname = im.save_image(newname, mpath)
            print newname


```
```
2017-06-17 03:46:51,916:INFO:werkzeug:127.0.0.1 - - [17/Jun/2017 03:46:51] "POST /mymediaview/upload HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/afidegnum/PycharmProjects/myfab/app/views.py", line 48, in upload_img
    newname = im.save_image(newname, mpath)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask_appbuilder/filemanager.py", line 217, in save_image
    if image.mode not in ('RGB', 'RGBA'):
AttributeError: 'unicode' object has no attribute 'mode'

```
