### ISSUE TITLE
AttributeError: '_io.BytesIO' object has no attribute 'size'

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#505]
hi, here is my new code to upload images but no matter what i tried images are not saved. it returns this error, 

```

class MyMediaView(ModelView):
    datamodel = SQLAInterface(Media)
    add_template = 'media_add.html'
    static_folder = 'static/appbuilder'

    @expose('/upload',  methods=['POST'])
    def upload_img(self):
        im = ImageManager()
        files = request.files['files']
        if request.method == 'POST':
            sname = str(files)
            imgsize = im.resize(files, (200, 100, True))
            newname = im.generate_name(None, files)
            mpath = config.IMG_UPLOAD_FOLDER + newname
            im.save_image(imgsize, mpath)
```

```
2017-06-18 09:56:50,227:INFO:werkzeug:127.0.0.1 - - [18/Jun/2017 09:56:50] "POST /mymediaview/upload HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/afidegnum/PycharmProjects/myfab/app/views.py", line 172, in upload_img
    imgsize = im.resize(files, (200, 100, True))
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/flask_appbuilder/filemanager.py", line 206, in resize
    if image.size[0] > width or image.size[1] > height:
  File "/home/afidegnum/myfab/lib/python2.7/site-packages/werkzeug/datastructures.py", line 2723, in __getattr__
    return getattr(self.stream, name)
AttributeError: '_io.BytesIO' object has no attribute 'size'
```

**Comment by MichaelPereira** [comment]
Hi Kokou,

I don't think this type of questions are relevant to Flask-AppBuilder, you would get better help sharing it on https://stackoverflow.com/
