### ISSUE TITLE
cannot add own views: permission instance does not have view_menu attribute

### ISSUE THREAD

**Issue by mtllr** [dpgaspar/Flask-AppBuilder#525]
Hi, 

I have troubles adding my own views although I followed the tutorial for an implementation with mongodb.

I have created my views incrementally and commented out the old unwanted views thoroughly. It seems the permissions got corrupted. For instance when I dump the first and last elements of my permissions, their types are: 
- element 1: PermissionView
- element last: bson Dbref 

My stacktrace indicates an AttributeError. Consistent with the fact that some permission items are dbref instances.

I have no idea how a bson dbref got into the permission view. I suspect it could be because I commented some views out and the view permissions were not updated properly. 

However the db was not important so I deleted it and started with a new one after I ran fabmanager create-admin, but got the same error. This makes me think that there is a permission view that does not return the right type somewhere.

My FAB Version is: 1.9.1

My permissions look like this:

mongoengine.base.datastructures.BaseList([can this form post on ResetPasswordView, can this form get on ResetPasswordView, can this form post on ResetMyPasswordView, can this form get on ResetMyPasswordView, can this form post on UserInfoEditView, can this form get on UserInfoEditView, can edit on UserDBModelView, can userinfo on UserDBModelView, can delete on UserDBModelView, can download on UserDBModelView, can list on UserDBModelView, can add on UserDBModelView, can show on UserDBModelView, resetmypassword on UserDBModelView, resetpasswords on UserDBModelView, userinfoedit on UserDBModelView, menu access on List Users, menu access on Security, can edit on RoleModelView, can delete on RoleModelView, can download on RoleModelView, can list on RoleModelView, can add on RoleModelView, can show on RoleModelView, Copy Role on RoleModelView, menu access on List Roles, can chart on UserStatsChartView, menu access on User's Statistics, can list on PermissionModelView, menu access on Base Permissions, can list on ViewMenuModelView, menu access on Views/Menus, can list on PermissionViewModelView, menu access on Permission on Views/Menus, DBRef('permission_view', ObjectId('59535399d49dd510850fa1db')), DBRef('permission_view', ObjectId('595353a2d49dd51088a2c718')), DBRef('permission_view', ObjectId('595353d5d49dd5108ca0cf35')), DBRef('permission_view', ObjectId('595353e0d49dd51091f9e92c')), DBRef('permission_view', ObjectId('595353e1d49dd5109457161a')), DBRef('permission_view', ObjectId('59535400d49dd5109c98184c'))  ])

My stacktrace looks like this:
Traceback (most recent call last):
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask_appbuilder/views.py", line 478, in list
    widgets=widgets)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 158, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 19, in block "body"
    {% block content %}
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 13, in block "content"
    {% block list_list scoped %}
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 15, in block "list_list"
    {{ widgets.get('list')()|safe }}
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask_appbuilder/widgets.py", line 34, in __call__
    return template.render(args)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/list.html", line 2, in top-level template code
    {% extends 'appbuilder/general/widgets/base_list.html' %}
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/base_list.html", line 3, in top-level template code
    {% set can_add = "can_add" | is_item_visible(modelview_name) %}
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask_appbuilder/filters.py", line 122, in is_item_visible
    return self.security_manager.has_access(permission, item)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 768, in has_access
    return self._has_view_access(g.user, permission_name, view_name)
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 759, in _has_view_access
    if (view_name == permission.view_menu.name) and (permission_name == permission.permission.name):
  File "/Users/martinteller/.flow/lib/python2.7/site-packages/bson/dbref.py", line 85, in __getattr__
    raise AttributeError(key)
AttributeError: view_menu

**Comment by mtllr** [comment]
Never mind, I found the bug: 
I reused a class name that I had not properly commented out from the tutorial code...
