### ISSUE TITLE
SQL injection 

### ISSUE THREAD

**Issue by JherekCorn** [dpgaspar/Flask-AppBuilder#544]
allowing string concatenation instead of parameterize-ing input

when using superset:  Interface.py line 70 the call
```
query = query.order_by(order_column + ' ' + order_direction)
```
https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/models/sqla/interface.py#L70

when passing a single quote
```
http://127.0.0.1/dashboardmodelview/list/?_oc_DashboardModelView='
```
The following stack trace occurs
```
Sorry, something went wrong

500 - Internal Server Error

Stacktrace

         Traceback (most recent call last):
  File "/opt/superset/.env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/superset/.env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/superset/.env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/superset/.env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/superset/.env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/superset/.env/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/opt/superset/.env/lib/python2.7/site-packages/flask_appbuilder/views.py", line 450, in list
    widgets = self._list()
  File "/opt/superset/.env/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 870, in _list
    page_size=page_size)
  File "/opt/superset/.env/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 786, in _get_list_widget
    count, lst = self.datamodel.query(joined_filters, order_column, order_direction, page=page, page_size=page_size)
  File "/opt/superset/.env/lib/python2.7/site-packages/flask_appbuilder/models/sqla/interface.py", line 103, in query
    order_direction=order_direction)
  File "/opt/superset/.env/lib/python2.7/site-packages/flask_appbuilder/models/sqla/interface.py", line 67, in _get_base_query
    query = query.order_by(order_column + ' ' + order_direction)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by dpgaspar** [comment]
Right you are...

Going to fix it ASAP.

**Comment by dpgaspar** [comment]
Ok, 1.9.2 is out to correct this issue

**Comment by JherekCorn** [comment]
@dpgaspar It appears you have replaced one type of string concat with another.
the new version still results in sql injection.

I know this isn't order by but is an example of a secure and insecure parameterized query (the % is replaced by a , )

This is INSECURE
```
c.execute("SELECT * FROM foo WHERE bar = %s AND baz = %s" % (param1, param2))
```
this is SECURE
```
c.execute("SELECT * FROM foo WHERE bar = %s AND baz = %s", (param1, param2))
```

Results of sql injection

```
dashboardmodelview/list/?_oc_DashboardModelView='&_od_DashboardModelView=asc
```
```
sqlalchemy.exc.ProgrammingError 
ProgrammingError: (psycopg2.ProgrammingError) unterminated quoted string at or near "' asc LIMIT 
500" LINE 2: FROM dashboards ORDER BY ' asc ^ [SQL: "SELECT dashboards.created_on AS 
dashboards_created_on, dashboards.changed_on AS dashboards_changed_on, dashboards.id AS 
dashboards_id, dashboards.dashboard_title AS dashboards_dashboard_title, dashboards.position_json 
AS dashboards_position_json, dashboards.description AS dashboards_description, dashboards.css AS 
dashboards_css, dashboards.json_metadata AS dashboards_json_metadata, dashboards.slug AS 
dashboards_slug, dashboards.changed_by_fk AS dashboards_changed_by_fk, dashboards.created_by_fk 
AS dashboards_created_by_fk \nFROM dashboards ORDER BY ' asc \n LIMIT %(param_1)s"] [parameters: 
{'param_1': 500}] 

```

**Comment by dpgaspar** [comment]
Could you please run some test on PR #549.

Thanks!

**Comment by JherekCorn** [comment]
The testing looks good, thank you for your great support of a great product!

**Comment by dpgaspar** [comment]
Thank you very much for your expertise and taking the time to report and follow up.
