### ISSUE TITLE
Python 3.4+ compatibility issue

### ISSUE THREAD

**Issue by myliyifei** [dpgaspar/Flask-AppBuilder#581]
I found this issue was about Python 3.4+ compatibility which moves reduce function to "functools" module, can you fix that?

[https://stackoverflow.com/questions/8689184/nameerror-name-reduce-is-not-defined-in-python](url)

builtins.NameError
NameError: name 'reduce' is not defined

Traceback (most recent call last)
File "C:\Users\myliyifei\VENV\flask-appbuilder\lib\site-packages\flask\app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Users\myliyifei\VENV\flask-appbuilder\lib\site-packages\flask\app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "C:\Users\myliyifei\VENV\flask-appbuilder\lib\site-packages\flask\app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\myliyifei\VENV\flask-appbuilder\lib\site-packages\flask\_compat.py", line 33, in reraise
raise value
File "C:\Users\myliyifei\VENV\flask-appbuilder\lib\site-packages\flask\app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\myliyifei\VENV\flask-appbuilder\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\myliyifei\VENV\flask-appbuilder\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\myliyifei\VENV\flask-appbuilder\lib\site-packages\flask\_compat.py", line 33, in reraise
raise value
File "C:\Users\myliyifei\VENV\flask-appbuilder\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\myliyifei\VENV\flask-appbuilder\lib\site-packages\flask\app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\Users\myliyifei\VENV\flask-appbuilder\lib\site-packages\flask_appbuilder\security\decorators.py", line 26, in wraps
return f(self, *args, **kwargs)
File "C:\Users\myliyifei\VENV\flask-appbuilder\lib\site-packages\flask_appbuilder\charts\views.py", line 196, in chart
order_direction='asc')
File "C:\Users\myliyifei\VENV\flask-appbuilder\lib\site-packages\flask_appbuilder\charts\views.py", line 175, in _get_chart_widget
value_columns = group.to_json(group.apply(lst, sort=order_column == ''), self.label_columns)
File "C:\Users\myliyifei\VENV\flask-appbuilder\lib\site-packages\flask_appbuilder\models\group.py", line 317, in apply
for (grouped, items) in groupby(data, key=self.attrgetter(*self.group_bys_cols)):
File "C:\Users\myliyifei\VENV\flask-appbuilder\lib\site-packages\flask_appbuilder\models\group.py", line 184, in g
return self.resolve_attr(obj, attr)
File "C:\Users\myliyifei\VENV\flask-appbuilder\lib\site-packages\flask_appbuilder\models\group.py", line 193, in resolve_attr
return reduce(getattr, attr.split('.'), obj)
NameError: name 'reduce' is not defined

**Comment by limjcst** [comment]
[flask_appbuilder/models/base.py](/dpgaspar/Flask-AppBuilder/blob/release/v1.9.4/flask_appbuilder/models/base.py) has already imported reduce from functools. But [flask_appbuilder/models/group.py](/dpgaspar/Flask-AppBuilder/blob/release/v1.9.4/flask_appbuilder/models/group.py) forgets.

**Comment by WouterVH** [comment]
flask_appbuilder/base.py also not fixed.

**Comment by FrankWangAU** [comment]
Python3.5, I am facing the same issue
[2018-08-12 06:10:47,472] {base.py:33} ERROR - name 'reduce' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask_appbuilder/base.py", line 31, in dynamic_class_import
    return reduce(getattr, tmp[1:], package)
NameError: name 'reduce' is not defined

I have manually add following import into flask_appbuilder/base.py 
from functools import reduce

Any plan to address issue or is there any other workaround?
