### ISSUE TITLE
Why python testdata.py fails?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#586]
$ python testdata.py

```
Traceback (most recent call last):
  File "testdata.py", line 30, in <module>
    c.name = get_random_name(names_list, random.randrange(2, 6))
  File "testdata.py", line 8, in get_random_name
    return " ".join(name_lst)
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by afidegnum** [comment]
I think you need to decode the bytestring before using it, what are you using as bytestring?
