### ISSUE TITLE
AttributeError: 'module' object has no attribute 'initialize'

### ISSUE THREAD

**Issue by homepy** [dpgaspar/Flask-AppBuilder#598]
Version 1.8.1
I Google for times by still don't know why...
Lack of any dependency?

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/flask_appbuilder/security/manager.py", line 604, in auth_user_ldap
    con = ldap.initialize(self.auth_ldap_server)
AttributeError: 'module' object has no attribute 'initialize'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.4/site-packages/flask_appbuilder/security/views.py", line 398, in login
    user = self.appbuilder.sm.auth_user_ldap(form.username.data, form.password.data)
  File "/usr/lib/python3.4/site-packages/flask_appbuilder/security/manager.py", line 634, in auth_user_ldap
    except ldap.LDAPError as e:
AttributeError: 'module' object has no attribute 'LDAPError'
```

**Comment by afidegnum** [comment]
did you name a module conflicting an existing one? 
did you install FAB on a virtual machine and calling it from another python environment?
check those first,

**Comment by homepy** [comment]
> did you name a module conflicting an existing one?
I didn't write any code indeed, it is used by the [superset 0.18.2](https://github.com/apache/incubator-superset/tree/0.18.2)
How to find conflicte module?


did you install FAB on a virtual machine and calling it from another python environment?
No any virtual machine.
I install and run it on python34...

**Comment by hamidmahmoodnbs** [comment]
@homepy I am facing the same issue. Did you get this issue resolved?
