### ISSUE TITLE
fabmanager babel-extract pulls nothing

### ISSUE THREAD

**Issue by Cody-Steelman** [dpgaspar/Flask-AppBuilder#630]
I have the folders set up as lined out in the documentation, and ran commands to build folders for the languages, but when running babel-extract the files remain empty and this error occurs.  how would this be fixed, I noticed i can go and enter in each string manually on the files, and it will translate, so It can be worked around, just would be more convenient to extract as intended.

Traceback (most recent call last):
  File "/home/cody-steelman/SchemaManager/env/bin/pybabel", line 11, in <module>
    sys.exit(main())
  File "/home/cody-steelman/SchemaManager/env/local/lib/python2.7/site-packages/babel/messages/frontend.py", line 908, in main
    return CommandLineInterface().run(sys.argv)
  File "/home/cody-steelman/SchemaManager/env/local/lib/python2.7/site-packages/babel/messages/frontend.py", line 832, in run
    return cmdinst.run()
  File "/home/cody-steelman/SchemaManager/env/local/lib/python2.7/site-packages/babel/messages/frontend.py", line 467, in run
    for filename, lineno, message, comments, context in extracted:
  File "/home/cody-steelman/SchemaManager/env/local/lib/python2.7/site-packages/babel/messages/extract.py", line 157, in extract_from_dir
    dirpath=absname,
  File "/home/cody-steelman/SchemaManager/env/local/lib/python2.7/site-packages/babel/messages/extract.py", line 212, in check_and_call_extract_file
    strip_comment_tags=strip_comment_tags
  File "/home/cody-steelman/SchemaManager/env/local/lib/python2.7/site-packages/babel/messages/extract.py", line 241, in extract_from_file
    strip_comment_tags))
  File "/home/cody-steelman/SchemaManager/env/local/lib/python2.7/site-packages/babel/messages/extract.py", line 322, in extract
    for lineno, funcname, messages, comments in results:
  File "/home/cody-steelman/SchemaManager/env/local/lib/python2.7/site-packages/babel/messages/extract.py", line 407, in extract_python
    future_flags = parse_future_flags(fileobj, encoding)
  File "/home/cody-steelman/SchemaManager/env/local/lib/python2.7/site-packages/babel/util.py", line 115, in parse_future_flags
    flags |= getattr(__future__, name).compiler_flag
AttributeError: 'module' object has no attribute 'print_function")'

**Comment by Cody-Steelman** [comment]
Solved this, the virtual environment cant be in the same directory as the rest of the project.
