### ISSUE TITLE
Save a photo in AWS S3

### ISSUE THREAD

**Issue by jreg2k** [dpgaspar/Flask-AppBuilder#650]
Hello,

Is there a way to store and retrieve images and photos in  AWS S3 ?

Regards.

James

**Comment by jreg2k** [comment]
Hello,
I am trying to use depot 
http://depot.readthedocs.io/

http://depot.readthedocs.io/en/latest/database.html#attaching-to-models

to store images in S3 but I've got this error : 
`
2017-11-29 23:48:51,381:INFO:werkzeug:127.0.0.1 - - [29/Nov/2017 23:48:51] "GET /documentmodelview/add HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask_appbuilder/views.py", line 511, in add
    widgets=widget)
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 158, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/add.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 19, in block "body"
    {% block content %}
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/add.html", line 7, in block "content"
    {% block add_form %}
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/add.html", line 8, in block "add_form"
    {{ widgets.get('add')(form_action=form_action)|safe }}
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask_appbuilder/widgets.py", line 34, in __call__
    return template.render(args)
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/form.html", line 45, in top-level template code
    {{ lib.render_field(field, begin_sep_label, end_sep_label, begin_sep_field, end_sep_field) }}
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/jinja2/runtime.py", line 553, in _invoke
    rv = self._func(*arguments)
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/lib.html", line 195, in template
    {{ field.label.text }}
  File "/home/james/Web/Flask/Sites/FlaskAppBuilder/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'None' has no attribute 'label'
`
Any  help will be appreciated.

James

**Comment by azulkipli** [comment]
Maybe you can use boto3
boto3.readthedocs.io

**Comment by dpgaspar** [comment]
This kind of backend storage for uploads is not supported, how are you trying to achieve this?

Have you tried to use something like FUSE? this could work, since you will be mounting S3 as an FS.

**Comment by jreg2k** [comment]
Thanks for your answers. The solution I choose is to use à file gateway server. This server exports à nfs storage directly plugged in the sélected S3 bucket. It's easy to setup and very useful.

https://aws.amazon.com/documentation/storage-gateway/

**Comment by dpgaspar** [comment]
Nice
