### ISSUE TITLE
UserDBModelView related_views throws UndefinedError: None has no element 0

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#710]
Using the original template from FAB, i extended the UserDBModeView so i can have a related views of galleries. [as you can see Here](https://github.com/afidegnum/escort/blob/master/app/sec_views.py#L21) 

but when clicked on show user, i have the following error. 
```
`2018-02-13 22:41:33,718:INFO:werkzeug:127.0.0.1 - - [13/Feb/2018 22:41:33] "GET /users/show/1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask_appbuilder/security/views.py", line 262, in show
    related_views=self._related_views)
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 160, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/afidegnum/fab/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/afidegnum/fab/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/show.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 19, in block "body"
    {% block content %}
  File "/home/afidegnum/fab/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/show.html", line 20, in block "content"
    {{ widgets.get('related_views')[loop.index - 1](pk = pk)|safe }}
UndefinedError: None has no element 0
```

There is no error appearing when clicking on the edit view. the related_views displays correctly. can you please assist in this bug?

**Comment by afidegnum** [comment]
any insight ?

**Comment by dpgaspar** [comment]
I have not tested it:

Add to the Galery Model:
````

ab_user = relationship("User")
````

Feel free to reopen if that does not work
