### ISSUE TITLE
'Blueprint' object has no attribute 'json_encoder'

### ISSUE THREAD

**Issue by birdflyinhigh** [dpgaspar/Flask-AppBuilder#741]
I just installed flask-appbuilder as instructed by the tuturial video, when i use command " 
fabmanager run, and open browser , it shows this : 
`AttributeError
AttributeError: 'Blueprint' object has no attribute 'json_encoder'

Traceback (most recent call last)
File "/home/python/.virtualenvs/flask_appbuilder/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "/home/python/.virtualenvs/flask_appbuilder/lib/python2.7/site-packages/flask/app.py", line 1978, in wsgi_app
ctx.push()
File "/home/python/.virtualenvs/flask_appbuilder/lib/python2.7/site-packages/flask/ctx.py", line 332, in push
self.session = self.app.open_session(self.request)
File "/home/python/.virtualenvs/flask_appbuilder/lib/python2.7/site-packages/flask/app.py", line 912, in open_session
return self.session_interface.open_session(self, request)
File "/home/python/.virtualenvs/flask_appbuilder/lib/python2.7/site-packages/flask/sessions.py", line 324, in open_session
s = self.get_signing_serializer(app)
File "/home/python/.virtualenvs/flask_appbuilder/lib/python2.7/site-packages/flask/sessions.py", line 321, in get_signing_serializer
signer_kwargs=signer_kwargs)
File "/home/python/.virtualenvs/flask_appbuilder/lib/python2.7/site-packages/itsdangerous.py", line 519, in __init__
self.is_text_serializer = is_text_serializer(serializer)
File "/home/python/.virtualenvs/flask_appbuilder/lib/python2.7/site-packages/itsdangerous.py", line 69, in is_text_serializer
return isinstance(serializer.dumps({}), text_type)
File "/home/python/.virtualenvs/flask_appbuilder/lib/python2.7/site-packages/flask/sessions.py", line 85, in dumps
return json.dumps(_tag(value), separators=(',', ':'))
File "/home/python/.virtualenvs/flask_appbuilder/lib/python2.7/site-packages/flask/json/__init__.py", line 177, in dumps
_dump_arg_defaults(kwargs)
File "/home/python/.virtualenvs/flask_appbuilder/lib/python2.7/site-packages/flask/json/__init__.py", line 98, in _dump_arg_defaults
bp.json_encoder if bp and bp.json_encoder
AttributeError: 'Blueprint' object has no attribute 'json_encoder'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.`

anyone can help?

**Comment by dpgaspar** [comment]
Yes, I've noticed this yesterday. 

Could you please downgrade Flask to something in between:
Flask>=0.10.0,<0.12.2

**Comment by dpgaspar** [comment]
This problem was solved by Flask, the release of 0.12.4 solved the problem

**Comment by ryan413** [comment]
I just had this issue with flask 1.0.2, had to downgrade to 0.12.4 before it would go away.
