### ISSUE TITLE
LDAP Auth on 1.3.0

### ISSUE THREAD

**Issue by ben-github** [dpgaspar/Flask-AppBuilder#79]
I'm trying to get 1.3.0 working to add migration documentation on the multi-roles. I just did a fresh checkout but I'm getting an error whenever I use LDAP as my authentication method.

My config looks like
```
AUTH_TYPE = AUTH_LDAP
AUTH_USER_REGISTRATION = True
AUTH_LDAP_SERVER = "ldap://localhost"
AUTH_LDAP_SEARCH = "ou=people,dc=example,dc=com"
```

when I run python run.py I get:

```
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "/data/VDS/flask-appbuilder/app/__init__.py", line 15, in <module>
    appbuilder = AppBuilder(app, db.session)
  File "/usr/lib/python2.7/dist-packages/flask_appbuilder/base.py", line 89, in __init__
    self.init_app(app, session)
  File "/usr/lib/python2.7/dist-packages/flask_appbuilder/base.py", line 109, in init_app
    self._add_admin_views()
  File "/usr/lib/python2.7/dist-packages/flask_appbuilder/base.py", line 201, in _add_admin_views
    self.sm.register_views()
  File "/usr/lib/python2.7/dist-packages/flask_appbuilder/security/manager.py", line 254, in register_views
    category_label=_('Security'))
  File "/usr/lib/python2.7/dist-packages/flask_appbuilder/base.py", line 269, in add_view
    baseview = self._check_and_init(baseview)
  File "/usr/lib/python2.7/dist-packages/flask_appbuilder/base.py", line 221, in _check_and_init
    if baseview.datamodel.session is None:
AttributeError: 'NoneType' object has no attribute 'session'
```

I've done a little testing and it works fine with AUTH_DB as the authentication method.

Thanks,

**Comment by dpgaspar** [comment]
Thanks! i'll take a look ASAP, please update 1.3.0, i've done some changes on docs, CSS and JS.

Notice: that i've kept the role column on the user's model, so the migration is much simpler, we just have to migrate the exiting role to roles. This is not "clean" but will hopefully have little impact on migration procedures, no need to create and drop FK's.

**Comment by dpgaspar** [comment]
Solved and pushed. But not tested....

**Comment by ben-github** [comment]
Tested, and fixed it. Thanks!
