### ISSUE TITLE
Cannot edit roles on 1.3.0

### ISSUE THREAD

**Issue by ben-github** [dpgaspar/Flask-AppBuilder#82]
I've installed 1.3.0 and am testing multirole. When I try to edit a role (url: http://localhost:8000/roles/edit/1)

I get the following error: (Also same error on show role (http://localhost:8000/roles/show/1)

```
2015-01-13 13:48:37,754:INFO:werkzeug:192.168.0.172 - - [13/Jan/2015 13:48:37] "GET /roles/edit/1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/share/pyshared/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/share/pyshared/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/share/pyshared/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/share/pyshared/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/share/pyshared/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/share/pyshared/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/share/pyshared/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/pyshared/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/pyshared/flask_appbuilder/security/decorators.py", line 27, in wraps
    return f(self, *args, **kwargs)
  File "/usr/share/pyshared/flask_appbuilder/views.py", line 311, in edit
    widgets = self._edit(pk)
  File "/usr/share/pyshared/flask_appbuilder/baseviews.py", line 797, in _edit
    orders=orders, pages=pages, page_sizes=page_sizes, widgets=widgets)
  File "/usr/share/pyshared/flask_appbuilder/baseviews.py", line 618, in _get_related_views_widgets
    view.__class__.__name__)))
  File "/usr/share/pyshared/flask_appbuilder/baseviews.py", line 580, in _get_related_view_widget
    fk = related_view.datamodel.get_related_fk(self.datamodel.obj)
  File "/usr/share/pyshared/flask_appbuilder/models/sqla/interface.py", line 397, in get_related_fk
    fk=related_fk(self,model)
  File "/usr/share/pyshared/flask_appbuilder/models/sqla/interface.py", line 395, in related_fk
    if matchmodel == SQLAobject.get_model_relation(col_name):
AttributeError: 'SQLAInterface' object has no attribute 'get_model_relation'
```

Thanks,

**Comment by dpgaspar** [comment]
Thanks, still very buggy 1.3.0. i will solve it, and let you know.

**Comment by ben-github** [comment]
No worries. Let me know if there is something for me to test / help with on this issue. That's all the issues I've seen so far with 1.3.0.

**Comment by dpgaspar** [comment]
I get no errors, please update the branch

**Comment by ben-github** [comment]
Sorry, my bad. This was caused by a commit I made earlier to my local version for some testing and that change got broken in the update to 1.3.0. I've removed it and I'm now on a pure 1.3.0 and don't have this problem. Sorry for the noise.
