### ISSUE TITLE
factoryapp example does not work

### ISSUE THREAD

**Issue by shizidushu** [dpgaspar/Flask-AppBuilder#872]
### Environment
linux mint 19
python 3.6.7

```
Babel==2.6.0
Click==7.0
colorama==0.4.1
defusedxml==0.5.0
Flask==1.0.2
Flask-AppBuilder==1.12.2
Flask-Babel==0.12.2
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.0
pkg-resources==0.0.0
python-dateutil==2.7.5
python3-openid==3.1.0
pytz==2018.7
six==1.12.0
SQLAlchemy==1.2.15
Werkzeug==0.14.1
WTForms==2.2.1
```

### Describe the expected results

no error

### Describe the actual results

```python
python3 testdata.py
```

```pytb
2018-12-16 18:11:09,008:INFO:flask_appbuilder.base:Registering class GroupModelView on menu List Groups
2018-12-16 18:11:09,008:INFO:flask_appbuilder.base:Registering class ContactModelView on menu List Contacts
2018-12-16 18:11:09,009:INFO:flask_appbuilder.base:Registering class ContactChartView on menu Contacts Chart
2018-12-16 18:11:09,010:INFO:flask_appbuilder.base:Registering class ContactTimeChartView on menu Contacts Birth Chart
Traceback (most recent call last):
  File "/home/simon/projects/flask-appbuilder/factoryapp/venv/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 999, in __call__
    return self.registry[key]
KeyError: 140273219880768

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testdata.py", line 15, in <module>
    db.session.add(ContactGroup(name='Friends'))
  File "/home/simon/projects/flask-appbuilder/factoryapp/venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/simon/projects/flask-appbuilder/factoryapp/venv/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 1001, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/simon/projects/flask-appbuilder/factoryapp/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 3010, in __call__
    return self.class_(**local_kw)
  File "/home/simon/projects/flask-appbuilder/factoryapp/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 141, in __init__
    self.app = app = db.get_app()
  File "/home/simon/projects/flask-appbuilder/factoryapp/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 912, in get_app
    'No application found. Either work inside a view function or push'
RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simon/projects/flask-appbuilder/factoryapp/venv/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 999, in __call__
    return self.registry[key]
KeyError: 140273219880768

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testdata.py", line 20, in <module>
    db.session.rollback()
  File "/home/simon/projects/flask-appbuilder/factoryapp/venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/simon/projects/flask-appbuilder/factoryapp/venv/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 1001, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/simon/projects/flask-appbuilder/factoryapp/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 3010, in __call__
    return self.class_(**local_kw)
  File "/home/simon/projects/flask-appbuilder/factoryapp/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 141, in __init__
    self.app = app = db.get_app()
  File "/home/simon/projects/flask-appbuilder/factoryapp/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 912, in get_app
    'No application found. Either work inside a view function or push'
RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.
```

### Steps to reproduce
follow the readme. https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/factoryapp

**Comment by dpgaspar** [comment]
Thank you for reporting this, It's fixed on master now

**Comment by cippall** [comment]
Hi,

Can we check if the factoryapp example works correctly?

I get ### **Error: Could not import ""app".** when running these lines
```
set FLASK_APP="app:create_app('config')"
flask fab create-admin
Username [admin]:
User first name [admin]:
User last name [user]:
Email [admin@fab.org]:
Password:
Repeat for confirmation:
Usage: flask fab create-admin [OPTIONS]

Error: Could not import ""app".
```

**Comment by dpgaspar** [comment]
Hi,

Are you running this from the root of the factoryapp example? can you send the output from `ls -l`

**Comment by cippall** [comment]
It's running form the root example folderI. 'm running this on Windows, this is the output for DIR:

```
23-May-19  06:06 AM    <DIR>          .
23-May-19  06:06 AM    <DIR>          ..
23-May-19  05:33 AM    <DIR>          app
22-May-19  10:08 PM    <DIR>          babel
19-May-19  10:57 AM             1,918 config.py
19-May-19  10:57 AM             1,918 config2.py
19-May-19  10:57 AM           228,852 NAMES.DIC
19-May-19  10:57 AM               451 README.rst
19-May-19  10:57 AM             1,655 testdata.py
               5 File(s)        234,794 bytes
               4 Dir(s)  215,055,613,952 bytes free
```

**Comment by gouline** [comment]
This `Error: Could not import ""app".` still happens with most examples, including "factoryapp" and "react-rest-api", unless there's a step missing in documentation.
