### ISSUE TITLE
builtins.TypeError TypeError: Object of type 'User' is not JSON serializable

### ISSUE THREAD

**Issue by shizidushu** [dpgaspar/Flask-AppBuilder#880]
### Environment
```
alembic==1.0.5
astroid==2.1.0
autopep8==1.4.3
Babel==2.6.0
Click==7.0
colorama==0.4.1
defusedxml==0.5.0
Flask==1.0.2
Flask-AppBuilder==1.12.2
Flask-Babel==0.12.2
Flask-JWT-Extended==3.14.0
Flask-Login==0.4.1
Flask-Migrate==2.3.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
humanize==0.5.1
isort==4.3.4
itsdangerous==1.1.0
Jinja2==2.10
lazy-object-proxy==1.3.1
Mako==1.0.7
MarkupSafe==1.1.0
mccabe==0.6.1
Pillow==5.3.0
pkg-resources==0.0.0
pycodestyle==2.4.0
PyJWT==1.7.1
pylint==2.2.2
python-dateutil==2.7.5
python-editor==1.0.3
python3-openid==3.1.0
pytz==2018.7
six==1.12.0
SQLAlchemy==1.2.15
typed-ast==1.1.1
Werkzeug==0.14.1
wrapt==1.10.11
WTForms==2.2.1
```

### Describe the expected results

Here is the example
```python
# model
class Paper(Model, AuditMixin):
    id = Column(Integer, primary_key=True)
    name = name = Column(String(50), nullable=False, unique = True)

    def __repr__(self):
        return self.name

# view

class PaperModelView(ModelView):
      datamodel = SQLAInterface(Paper)
      list_columns = ['name','created_by', 'changed_by', 'created_on', 'changed_on']

appbuilder.add_view(PaperModelView, "Paper", category="test")
```

### Describe the actual results

Add a column and visit `http://0.0.0.0:8080/papermodelview/api/read`, it says `builtins.TypeError TypeError: Object of type 'User' is not JSON serializable`

```pytb
Traceback (most recent call last):
  File "/home/simon/projects/flask-bi/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/simon/projects/flask-bi/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/simon/projects/flask-bi/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/simon/projects/flask-bi/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/simon/projects/flask-bi/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/simon/projects/flask-bi/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/simon/projects/flask-bi/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/simon/projects/flask-bi/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/simon/projects/flask-bi/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/simon/projects/flask-bi/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/simon/projects/flask-bi/venv/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 52, in wraps
    return f(self, *args, **kwargs)
  File "/home/simon/projects/flask-bi/venv/lib/python3.6/site-packages/flask_appbuilder/views.py", line 229, in api_read
    result=result)
  File "/home/simon/projects/flask-bi/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "/home/simon/projects/flask-bi/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/home/simon/projects/flask-bi/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'User' is not JSON serializable
```

**Comment by robinedwards** [comment]
So I came across the same issue with a brand new app using the `AuditMixin` on one of my models which meant the model view was attempting the to serialize the `created_by` column from a `User` to JSON.

The SQLA `User` model already has a `to_json` method but the default json encoder wasnt using it. So a work around is to wire in a custom one like so:

```
class CustomJSONEncoder(JSONEncoder):

    def default(self, obj):
        if hasattr(obj, 'to_json') and callable(getattr(obj, 'to_json')):
            return obj.to_json()
        else:
            return JSONEncoder.default(self, obj)

app.json_encoder = CustomJSONEncoder
```

I guess this needs integrating into FAB some how?
