### ISSUE TITLE
related views does not work on inherited models with relationships

### ISSUE THREAD

**Issue by kurtforrester** [dpgaspar/Flask-AppBuilder#881]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment
<details>
```python
Flask-Appbuilder version:
Flask-AppBuilder==1.12.2
pip freeze output:
alabaster==0.7.10
alembic==1.0.5
amqp==2.3.2
anaconda-client==1.7.2
anaconda-navigator==1.9.4
anaconda-project==0.8.2
asn1crypto==0.24.0
astroid==1.6.1
astropy==2.0.3
attrs==17.4.0
Babel==2.5.3
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.0
billiard==3.5.0.5
bitarray==0.8.1
bkcharts==0.2
blaze==0.11.3
bleach==2.1.2
bokeh==0.12.13
boto==2.48.0
boto3==1.4.7
botocore==1.7.48
Bottleneck==1.2.1
cairocffi==0.9.0
CairoSVG==2.2.1
cchardet==2.1.4
celery==4.2.1
certifi==2018.11.29
cffi==1.11.4
chardet==3.0.4
click==6.7
cloudpickle==0.5.2
clyent==1.2.2
colorama==0.3.9
conda==4.5.11
conda-build==3.4.1
conda-verify==2.0.0
contextlib2==0.5.5
cryptography==2.1.4
cssselect2==0.2.1
cycler==0.10.0
Cython==0.27.3
cytoolz==0.9.0
dask==0.16.1
datashape==0.5.4
decorator==4.2.1
defusedxml==0.5.0
distributed==1.20.2
Django==2.1.1
docutils==0.14
entrypoints==0.2.3
et-xmlfile==1.0.1
Faker==1.0.0
fastcache==1.0.2
filelock==2.0.13
Flask==0.12.4
Flask-AppBuilder==1.12.2
Flask-Babel==0.12.2
Flask-Caching==1.4.0
Flask-Compress==1.4.0
Flask-Cors==3.0.3
Flask-Login==0.4.1
Flask-Migrate==2.3.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
flower==0.9.2
future==0.16.0
geographiclib==1.49
geopy==1.18.1
gevent==1.2.2
glob2==0.6
gmpy2==2.0.8
greenlet==0.4.12
gunicorn==19.9.0
h5py==2.7.1
heapdict==1.0.0
html5lib==1.0.1
humanize==0.5.1
idna==2.6
ijson==2.3
imageio==2.2.0
imagesize==0.7.1
ipykernel==4.8.0
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.1.1
isodate==0.6.0
isort==4.2.15
itsdangerous==0.24
jdcal==1.3
jedi==0.11.1
jeepney==0.3.1
Jinja2==2.10
jmespath==0.9.3
jsonlines==1.2.0
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.31.5
jupyterlab-launcher==0.10.2
keyring==13.0.0
kiwisolver==1.0.1
kombu==4.2.2
lazy-object-proxy==1.3.1
linear-tsv==1.1.0
llvmlite==0.24.0
locket==0.2.0
lxml==4.1.1
Mako==1.0.7
Markdown==3.0.1
MarkupSafe==1.0
matplotlib==3.0.1
mccabe==0.6.1
mistune==0.8.3
mkl-fft==1.0.4
mkl-random==1.0.1
mpmath==1.0.0
msgpack-python==0.5.1
multipledispatch==0.4.9
navigator-updater==0.1.0
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.1
nltk==3.2.5
nose==1.3.7
notebook==5.4.0
numba==0.39.0
numexpr==2.6.4
numpy==1.15.4
numpydoc==0.7.0
odo==0.5.1
olefile==0.45.1
openpyxl==2.4.10
packaging==16.8
pandas==0.23.4
pandocfilters==1.4.2
parsedatetime==2.4
parso==0.1.1
partd==0.3.8
path.py==10.5
pathlib2==2.3.0
patsy==0.5.0
pdfrw==0.4
pep8==1.7.1
periodictable==1.5.0
pexpect==4.3.1
pickleshare==0.7.4
Pillow==5.2.0
pkginfo==1.4.1
pluggy==0.6.0
ply==3.10
polyline==1.3.2
prompt-toolkit==1.0.15
psutil==5.4.3
ptyprocess==0.5.2
py==1.5.2
pycodestyle==2.3.1
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0.1
pydruid==0.5.0
pyflakes==1.6.0
Pygments==2.2.0
PyHive==0.6.1
pylint==1.8.2
pyodbc==4.0.22
pyOpenSSL==17.5.0
pyparsing==2.2.0
Pyphen==0.9.5
PySocks==1.6.7
pytest==3.3.2
python-dateutil==2.6.1
python-editor==1.0.3
python-geohash==0.8.5
python3-openid==3.1.0
pytz==2017.3
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==16.0.3
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.5.2
requests==2.18.4
rfc3986==1.2.0
rope==0.10.7
ruamel-yaml==0.15.35
s3transfer==0.1.13
scikit-image==0.13.1
scikit-learn==0.19.1
scipy==1.1.0
seaborn==0.8.1
SecretStorage==3.0.1
Send2Trash==1.4.2
simplegeneric==0.8.1
simplejson==3.16.0
singledispatch==3.4.0.3
six==1.11.0
snowballstemmer==1.2.1
sortedcollections==0.5.3
sortedcontainers==1.5.9
Sphinx==1.8.1
sphinxcontrib-websupport==1.0.1
spyder==3.3.2
spyder-kernels==0.2.4
SQLAlchemy==1.2.13
SQLAlchemy-Utils==0.33.9
sqlparse==0.2.4
statsmodels==0.9.0
sympy==1.1.1
tables==3.4.2
tableschema==1.3.0
tabulator==1.19.0
tblib==1.3.2
terminado==0.8.1
testpath==0.3.1
text-unidecode==1.2
thrift==0.11.0
tinycss2==0.6.1
toolz==0.9.0
tornado==4.5.3
traitlets==4.3.2
typing==3.6.2
unicodecsv==0.14.1
urllib3==1.22
vine==1.1.4
wcwidth==0.1.7
WeasyPrint==0.42.3
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.1.0
wrapt==1.10.11
WTForms==2.2.1
xarray==0.10.6
xlrd==1.1.0
XlsxWriter==1.1.2
xlwt==1.3.0
zict==0.1.3
```
</details>

### Describe the expected results
I have inherited model classes which contains relationships to other models. I should be able to use related views on both the primary class and the class which inherits the primary class.

```python3
from flask_appbuilder import Model
from sqlalchemy import Column, Integer, Unicode, ForeignKey, Table
from sqlalchemy.orm import relationship

association_table = Table('association', Model.metadata,
                          Column('left_id', Integer, ForeignKey('left.id')),
                          Column('right_id', Integer, ForeignKey('right.id'))
                          )


class Person(Model):

    __tablename__ = 'person'
    id = Column(Integer, primary_key=True)
    name = Column(Unicode(32), nullable=False)
    type_ = Column(Unicode(32), nullable=False, index=True)

    __mapper_args__ = {
        'polymorphic_identity': 'person',
        'polymorphic_on': type_
    }

    def __repr__(self):
        return "{0}".format(self.name)


class Parent(Person):
    __tablename__ = 'left'
    id = Column(Integer, ForeignKey('person.id'), primary_key=True)
    children = relationship(
        "Child",
        secondary=association_table,
        back_populates="parents")

    __mapper_args__ = {
        'polymorphic_identity': 'parent',
    }


class Child(Person):
    __tablename__ = 'right'
    id = Column(Integer, ForeignKey('person.id'), primary_key=True)
    parents = relationship(
        "Parent",
        secondary=association_table,
        back_populates="children")

    __mapper_args__ = {
        'polymorphic_identity': 'child',
    }


class Step(Child):
    __tablename__ = 'step'
    id = Column(Integer, ForeignKey('right.id'), primary_key=True)

    __mapper_args__ = {
        'polymorphic_identity': 'step',
    }

```
```python3
from flask_appbuilder.models.sqla.interface import SQLAInterface
from flask_appbuilder import ModelView, MasterDetailView
from app import appbuilder, db

from .models import Parent, Child, Step


class ParentModelView(ModelView):
    datamodel = SQLAInterface(Parent)
    list_columns = ['name', 'children']
    show_columns = list_columns
    edit_columns = list_columns

    edit_exclude_columns = ['type_']
    add_exclude_columns = edit_exclude_columns


class ChildModelView(ModelView):
    datamodel = SQLAInterface(Child)
    list_columns = ['name', 'parents']
    show_columns = list_columns
    edit_columns = list_columns

    edit_exclude_columns = ['type_']
    add_exclude_columns = edit_exclude_columns


class StepModelView(ModelView):
    datamodel = SQLAInterface(Step)
    list_columns = ['name', 'parents']
    show_columns = list_columns
    edit_columns = list_columns

    edit_exclude_columns = ['type_']
    add_exclude_columns = edit_exclude_columns


class ParentRelatedModelView(ModelView):
    datamodel = SQLAInterface(Parent)
    related_views = [ChildModelView]
    list_columns = ['name', 'children']
    show_columns = list_columns
    edit_columns = list_columns

    edit_exclude_columns = ['type_']
    add_exclude_columns = edit_exclude_columns

    show_template = 'appbuilder/general/model/show_cascade.html'
    edit_template = 'appbuilder/general/model/edit_cascade.html'


class ChildRelatedModelView(ModelView):
    datamodel = SQLAInterface(Child)
    related_views = [ParentModelView]
    list_columns = ['name', 'parents']
    show_columns = list_columns
    edit_columns = list_columns

    edit_exclude_columns = ['type_']
    add_exclude_columns = edit_exclude_columns

    show_template = 'appbuilder/general/model/show_cascade.html'
    edit_template = 'appbuilder/general/model/edit_cascade.html'


class StepRelatedModelView(ModelView):
    datamodel = SQLAInterface(Step)
    related_views = [ParentModelView]
    list_columns = ['name', 'parents']
    show_columns = list_columns
    edit_columns = list_columns

    edit_exclude_columns = ['type_']
    add_exclude_columns = edit_exclude_columns

    show_template = 'appbuilder/general/model/show_cascade.html'
    edit_template = 'appbuilder/general/model/edit_cascade.html'


class MasterGroupChildView(MasterDetailView):
    datamodel = SQLAInterface(Parent)
    related_views = [ChildModelView]

    list_columns = ['name']


db.create_all()


appbuilder.add_view(ParentModelView, "ParentModelView",
                    icon="fa-folder-open-o", category="Category",
                    category_icon='fa-envelope')
appbuilder.add_view(ChildModelView, "ChildModelView", icon="fa-folder-open-o",
                    category="Category", category_icon='fa-envelope')
appbuilder.add_view(StepModelView, "StepModelView", icon="fa-folder-open-o",
                    category="Category", category_icon='fa-envelope')
appbuilder.add_separator("Category")
appbuilder.add_view(ParentRelatedModelView, "ParentRelatedModelView",
                    icon="fa-cogs", category="Category",
                    category_icon='fa-envelope')
appbuilder.add_view(ChildRelatedModelView, "ChildRelatedModelView",
                    icon="fa-cogs", category="Category",
                    category_icon='fa-envelope')
appbuilder.add_view(StepRelatedModelView, "StepRelatedModelView",
                    icon="fa-cogs", category="Category",
                    category_icon='fa-envelope')
appbuilder.add_separator("Category")
appbuilder.add_view(MasterGroupChildView, "MasterGroupChildView",
                    icon="fa-cogs", category="Category",
                    category_icon='fa-envelope')
```

### Describe the actual results

When adding parents and children the app works as expected. When the Step class (which is inherited from Child) is employed there is an error.

```pytb
Traceback (most recent call last):
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask_appbuilder/views.py", line 495, in show
    related_views=self._related_views)
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask_appbuilder/baseviews.py", line 162, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/model/show_cascade.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 19, in block "body"
    {% block content %}
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/model/show_cascade.html", line 11, in block "content"
    {% block related_views %}
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/model/show_cascade.html", line 14, in block "related_views"
    {% call lib.accordion_tag(view.__class__.__name__,view.title, False) %}
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/lib.html", line 254, in template
    {{ caller() }}
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/home/kforrester/anaconda3/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/model/show_cascade.html", line 15, in template
    {{ widgets.get('related_views')[loop.index - 1](pk = pk)|safe }}
TypeError: 'NoneType' object is not callable
```

### Steps to reproduce
Add a parent
Add a child
Add a step

View a step will raise an error when using the related movel view.

**Comment by chrihartl** [comment]
Hi, I do have the same problem. Would be very much appreciated if this could be looked at! :-)
