### ISSUE TITLE
sqlalchemy.exc.CompileError  sqlalchemy.exc.CompileError: MSSQL requires an order_by when using an OFFSET or a non-simple LIMIT clause

### ISSUE THREAD

**Issue by shizidushu** [dpgaspar/Flask-AppBuilder#894]
### Environment
```
alembic==1.0.5
astroid==2.1.0
autopep8==1.4.3
Babel==2.6.0
certifi==2018.11.29
chardet==3.0.4
Click==7.0
colorama==0.4.1
defusedxml==0.5.0
Flask==1.0.2
Flask-AppBuilder==1.12.2
Flask-Babel==0.12.2
Flask-JWT-Extended==3.14.0
Flask-Login==0.4.1
Flask-Migrate==2.3.1
Flask-OAuthlib==0.9.5
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
gunicorn==19.9.0
humanize==0.5.1
idna==2.8
inflect==2.1.0
isort==4.3.4
itsdangerous==1.1.0
Jinja2==2.10
lazy-object-proxy==1.3.1
Mako==1.0.7
MarkupSafe==1.1.0
mccabe==0.6.1
oauthlib==2.1.0
Pillow==5.3.0
pkg-resources==0.0.0
psycopg2==2.7.6.1
pycodestyle==2.4.0
PyJWT==1.7.1
pylint==2.2.2
pymssql==2.1.4
pyodbc==4.0.25
python-dateutil==2.7.5
python-editor==1.0.3
python3-openid==3.1.0
pytz==2018.7
requests==2.21.0
requests-oauthlib==1.0.0
six==1.12.0
sqlacodegen==2.0.1
SQLAlchemy==1.2.16
typed-ast==1.1.1
urllib3==1.24.1
Werkzeug==0.14.1
wrapt==1.10.11
WTForms==2.2.1

```

### Describe the expected results
No error

### Describe the actual results

Tell us what happens instead.

```pytb
Traceback (most recent call last):
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/flask_appbuilder/views.py", line 475, in list
    widgets = self._list()
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/flask_appbuilder/baseviews.py", line 888, in _list
    page_size=page_size)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/flask_appbuilder/baseviews.py", line 798, in _get_list_widget
    count, lst = self.datamodel.query(joined_filters, order_column, order_direction, page=page, page_size=page_size)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/flask_appbuilder/models/sqla/interface.py", line 122, in query
    return count, query.all()
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2956, in all
    return list(self)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3112, in __iter__
    return self._execute_and_instances(context)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3137, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 974, in execute
    return meth(self, multiparams, params)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1084, in _execute_clauseelement
    else None,
  File "<string>", line 1, in <lambda>

  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 448, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 454, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/sqlalchemy/dialects/mssql/base.py", line 1441, in __init__
    super(MSSQLCompiler, self).__init__(*args, **kwargs)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 550, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 310, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 338, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 90, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/simon/git/flaskbi/venv/lib/python3.6/site-packages/sqlalchemy/dialects/mssql/base.py", line 1530, in visit_select
    "MSSQL requires an order_by when "
sqlalchemy.exc.CompileError: MSSQL requires an order_by when using an OFFSET or a non-simple LIMIT clause
```

### Steps to reproduce
I'm trying to generate CRUD for pre-existing table of a SQL SERVER.

Configure `SQLALCHEMY_BINDS` to my local mssql server.

```python
class TUser(Model):
    __bind_key__ = 'test_mssql'
    __tablename__ = 'T_Users'
    UserId = Column(Integer, primary_key=True)
    IsLock = Column(Boolean)
```

```python
class TUsersModelView(ModelView):
    datamodel = SQLAInterface(TUser)

appbuilder.add_view(TUsersModelView, 'TUser', category='test')
```
Go to the TUsersModelView page and click to see the page 2.

**Comment by Walderman** [comment]
Hi,
I had a similar problem, and adding base_order to my views solved it, so you could for example add:
base_order = ('UserId','desc')
to TUsersModelView.

**Comment by shizidushu** [comment]
@Walderman Thank you very much. It works.
