### ISSUE TITLE
Unable to extend the User model

### ISSUE THREAD

**Issue by deepanand209** [dpgaspar/Flask-AppBuilder#896]
### Environment

Flask-Appbuilder version: 1.12.2

### Describe the expected results

I tried running the example  from the repository
https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/extendsecurity

I wanted to learn how to extend the user model as done in the example above. I tried creating the data by running "python testdata.py"

### Describe the actual results

I get the error
Can't place __table_args__ on an inherited class with no table.

Trace as below:

C:\extendsecurity>python testdata.py
Traceback (most recent call last):
  File "testdata.py", line 3, in <module>
    from app import appbuilder, db
  File "C:\extendsecurity\app\__init__.py", line 6, in <module>
    from .sec import MySecurityManager
  File "C:\extendsecurity\app\sec.py", line 3, in <module>
    from .models import MyUser
  File "C:\extendsecurity\app\models.py", line 20, in <module>
    class MyUser(User):
  File "C:\ProgramData\Miniconda3\lib\site-packages\flask_sqlalchemy\model.py", line 67, in __init__
    super(NameMetaMixin, cls).__init__(name, bases, d)
  File "C:\ProgramData\Miniconda3\lib\site-packages\flask_sqlalchemy\model.py", line 121, in __init__
    super(BindMetaMixin, cls).__init__(name, bases, d)
  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\ext\declarative\api.py", line 64, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 88, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 103, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 133, in __init__
    self._setup_inheritance()
  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 442, in _setup_inheritance

    "Can't place __table_args__ on an inherited class "
sqlalchemy.exc.ArgumentError: Can't place __table_args__ on an inherited class with no table.
### Steps to reproduce

I ran the code as it is

**Comment by soundmaking** [comment]
Hello, just a guess, but did you run `fabmanager create-db` before testdata.py ?

This is a guess because when I did `$ python testdata.py` to test the thought, I hit a different error!

```
(flask-env) Samuels-Mac-mini:extendsecurity samuelfreeman$ python testdata.py 
Traceback (most recent call last):
  File "testdata.py", line 3, in <module>
    from app import appbuilder, db
  File "/Users/samuelfreeman/gitclones/Flask-AppBuilder/examples/extendsecurity/app/__init__.py", line 6, in <module>
    from .sec import MySecurityManager
  File "/Users/samuelfreeman/gitclones/Flask-AppBuilder/examples/extendsecurity/app/sec.py", line 3, in <module>
    from models import MyUser
ModuleNotFoundError: No module named 'models'
```

**Comment by deepanand209** [comment]
thanks for replying !

Yes, forgot to mention that I had to change the line to 
from .models import MyUser. 

After searching a bit, I found that the problem has been raised before:
 https://github.com/dpgaspar/Flask-AppBuilder/issues/873

and the solution is to add 

__table_name__ = 'ab_user' to the derived class.

I am closing this issue.

**Comment by gbrian** [comment]
Next one coming here!
In my case was adding: ` __tablename__ = 'ab_user'`
