### ISSUE TITLE
How to specify the dropdown list without using relationship/foreign key in ModelView?

### ISSUE THREAD

**Issue by shizidushu** [dpgaspar/Flask-AppBuilder#898]
I want to display dropdown list when add or edit the column. I do not want to use `relationship` / foreign key in `model` to do this because I don't want to create a new table in database.

For example, how to specify the choice for `UserType`, `{0: 'default', 1: 'temporary'}`?

```python
class TUser(Model):
    UserId = Column(Integer, primary_key=True)
    UserType = Column(Integer, nullable=False, default = 0)

class TUsersModelView(ModelView):
    datamodel = SQLAInterface(TUser)
```

**Comment by dpgaspar** [comment]
Take a look at enums on the examples

**Comment by shizidushu** [comment]
Just try the enums example.
In my case, I have a pre-existing table and there is a mssql `TINYINT` type column. I want to save integer to database and show it's name in browser.

I try to reproduce my problem using the `enums` example. For the gender column:
- save integer value to database
- show `Female` and `Male` to browser in dropdown list when edit or add.

I try to set values_callable parameter as the [sqlalchemy doc](https://docs.sqlalchemy.org/en/latest/core/type_basics.html?highlight=enum#sqlalchemy.types.Enum) describes. There is no success.

```python
import enum

class genderEnum(enum.Enum):
    Female = 1
    Male = 2

class Contact(Model):
    gender = Column(Enum(genderEnum, values_callable = lambda x: [e.value for e in x]))
```

The traceback:
```
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from app import app
  File "/home/simon/git/Flask-AppBuilder/examples/enums/app/__init__.py", line 28, in <module>
    from app import models, views
  File "/home/simon/git/Flask-AppBuilder/examples/enums/app/models.py", line 20, in <module>
    class Contact(Model):
  File "/home/simon/git/Flask-AppBuilder/examples/enums/app/models.py", line 29, in Contact
    gender = Column(Enum(genderEnum, values_callable = lambda x: [e.value for e in x]))
  File "/home/simon/git/Flask-AppBuilder/examples/enums/venv/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1343, in __init__
    self._enum_init(enums, kw)
  File "/home/simon/git/Flask-AppBuilder/examples/enums/venv/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1379, in _enum_init
    length = max(len(x) for x in self.enums)
  File "/home/simon/git/Flask-AppBuilder/examples/enums/venv/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1379, in <genexpr>
    length = max(len(x) for x in self.enums)
TypeError: object of type 'int' has no len()
```
