### ISSUE TITLE
NameError: name 'OverviewGroup' is not defined

### ISSUE THREAD

**Issue by flynn1973** [dpgaspar/Flask-AppBuilder#904]
while trying to build an app around an **_existing_** data model, i got a strange "not defined" error. i followed the simple example from the docs.

Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from app import app
  File "/root/flask/fab_test/app/__init__.py", line 31, in <module>
    from app import views
  File "/root/flask/fab_test/app/views.py", line 20, in <module>
    class OverviewGroup(ModelView):
  File "/root/flask/fab_test/app/views.py", line 21, in OverviewGroup
    datamodel = SQLAInterface(OverviewGroup)
NameError: name 'OverviewGroup' is not defined

__init.py__

````
import logging
from flask import Flask
from flask_appbuilder import SQLA, AppBuilder

"""
 Logging configuration
"""

logging.basicConfig(format='%(asctime)s:%(levelname)s:%(name)s:%(message)s')
logging.getLogger().setLevel(logging.DEBUG)

app = Flask(__name__)
app.config.from_object('config')
db = SQLA(app)
appbuilder = AppBuilder(app, db.session)


"""
from sqlalchemy.engine import Engine
from sqlalchemy import event

#Only include this for SQLLite constraints
@event.listens_for(Engine, "connect")
def set_sqlite_pragma(dbapi_connection, connection_record):
    # Will force sqllite contraint foreign keys
    cursor = dbapi_connection.cursor()
    cursor.execute("PRAGMA foreign_keys=ON")
    cursor.close()
"""

from app import views
from app import models

````

models.py

````
from flask_appbuilder import Model
from flask_appbuilder.models.mixins import AuditMixin, FileColumn, ImageColumn
from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, Table
from sqlalchemy.schema import FetchedValue
from sqlalchemy.orm import relationship
from flask_sqlalchemy import SQLAlchemy


"""

You can use the extra Flask-AppBuilder fields and Mixin's

AuditMixin will add automatic timestamp of created and modified by who


"""

class OverviewGroup(Model):
    NODE_ID = Column(Integer, primary_key=True, server_default=FetchedValue())
    NODE = Column(String(256, u'utf8_unicode_ci'))

    def __repr__(self):
        return self.name

class Overview(Model):
    NODE_ID = Column(Integer, primary_key=True, server_default=FetchedValue())
    NODE = Column(String(256, u'utf8_unicode_ci'))
    LOCATION = Column(String(256, u'utf8_unicode_ci'))
    IS_CLUSTER = Column(String(256, u'utf8_unicode_ci'))
    MAN_SYS_NAME = Column(String(256, u'utf8_unicode_ci'))
    HAS_CICS = Column(String(256, u'utf8_unicode_ci'))
    OS_LEVEL = Column(String(256, u'utf8_unicode_ci'))
    HAS_COBOL = Column(String(256, u'utf8_unicode_ci'))
    HAS_ORACLE = Column(String(256, u'utf8_unicode_ci'))
    MEM_VALUE = Column(String(256, u'utf8_unicode_ci'))
    HAS_TUXEDO = Column(String(256, u'utf8_unicode_ci'))
    STORAGE_VALUE = Column(String(256, u'utf8_unicode_ci'))
    IS_LPM = Column(String(256, u'utf8_unicode_ci'))
    HAS_SAP = Column(String(256, u'utf8_unicode_ci'))
    CPU_VALUE = Column(String(256, u'utf8_unicode_ci'))
    CLUSTER_RGS = Column(String(256, u'utf8_unicode_ci'))
    HA_LEVEL = Column(String(256, u'utf8_unicode_ci'))
    CLUSTER_NODES = Column(String(256, u'utf8_unicode_ci'))
    CLUSTER_NAME = Column(String(256, u'utf8_unicode_ci'))
    CPU_POOL = Column(String(256, u'utf8_unicode_ci'))
    AME_FACTOR = Column(String(256, u'utf8_unicode_ci'))
    SYS_PROFILE = Column(String(256, u'utf8_unicode_ci'))
    INFO_MAIL = Column(String(256, u'utf8_unicode_ci'))
    HOSTNAME = Column(String(256, u'utf8_unicode_ci'))
    OS_TYPE = Column(String(256, u'utf8_unicode_ci'))
    Java6_64 = Column(String(256, u'utf8_unicode_ci'))
    Java7_64 = Column(String(256, u'utf8_unicode_ci'))
    Java8_64 = Column(String(256, u'utf8_unicode_ci'))
    Java5_64 = Column(String(256, u'utf8_unicode_ci'))
    Java8 = Column(String(256, u'utf8_unicode_ci'))
    Java5 = Column(String(256, u'utf8_unicode_ci'))
    Java14 = Column(String(256, u'utf8_unicode_ci'))
    Java7 = Column(String(256, u'utf8_unicode_ci'))
    Java71 = Column(String(256, u'utf8_unicode_ci'))
    Java71_64 = Column(String(256, u'utf8_unicode_ci'))
    Java14_64 = Column(String(256, u'utf8_unicode_ci'))
    Java6 = Column(String(256, u'utf8_unicode_ci'))
    UPTIME = Column(String(256, u'utf8_unicode_ci'))
    IP = Column(String(256, u'utf8_unicode_ci'))
    IP_LONG = Column(String(256, u'utf8_unicode_ci'))
    CLUSTER_NODENAME = Column(String(256, u'utf8_unicode_ci'))
    RG_SERVICE_IP_LONG = Column(String(256, u'utf8_unicode_ci'))
    HAS_SNA = Column(String(256, u'utf8_unicode_ci'))

    def __repr__(self):
        return self.name

````

views.py

````
from flask import render_template
from flask_appbuilder.models.sqla.interface import SQLAInterface
from flask_appbuilder import ModelView
from app import appbuilder, db

"""
    Create your Views::


    class MyModelView(ModelView):
        datamodel = SQLAInterface(MyModel)


    Next, register your Views::


    appbuilder.add_view(MyModelView, "My View", icon="fa-folder-open-o", category="My Category", category_icon='fa-envelope')
"""

class OverviewGroup(ModelView):
    datamodel = SQLAInterface(OverviewGroup)
    related_views = [Overview]

"""
    Application wide 404 error handler
"""
@appbuilder.app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html', base_template=appbuilder.base_template, appbuilder=appbuilder), 404

appbuilder.add_view(OverviewGroup, "Overview", category="Views")

#db.create_all()

````

**Comment by dpgaspar** [comment]
Sorry for the delay @flynn1973 

You need to import OverviewGroup on views.py from your models
