### ISSUE TITLE
No way to catch assertions when sqlalchemy model validators fail

### ISSUE THREAD

**Issue by CameronNemo** [dpgaspar/Flask-AppBuilder#906]
### Environment

Flask-Appbuilder version: 1.12.2

pip freeze output:

```
alembic==1.0.7
Babel==2.6.0
Click==7.0
colorama==0.4.1
Flask==1.0.2
Flask-AppBuilder==1.12.2
Flask-Babel==0.12.2
Flask-Login==0.4.1
Flask-Migrate==2.3.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
itsdangerous==1.1.0
Jinja2==2.10
Mako==1.0.7
MarkupSafe==1.1.0
python-dateutil==2.7.5
python-editor==1.0.4
python-openid==2.2.5
pytz==2018.9
six==1.12.0
SQLAlchemy==1.2.17
Werkzeug==0.14.1
WTForms==2.2.1
```

### Describe the expected results

Rather than using a custom WTForm, I am attempting to use validators with my model like so:

```python
class MyClass(Model):
    id = Column(Integer, primary_key=True)
    email = Column(String(96))

    @validates('email')
    def validate_email(self, key, email):
        if email and not re.match("[^@]+@[^@]+\.[^@]+", email):
            raise AssertionError('Email provided was not a valid email')
        return email

    def __repr__(self):
        return self.name
```

Of course, I need to catch this exception and display it to the user when the validation fails. I am having a difficult time of identifying where I might be able to do this.

If you have any thoughts about how to accomplish the functionality I desire, please let me know.

### Describe the actual results

Traceback:

```pytb
Traceback (most recent call last):
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/flask_appbuilder/views.py", line 506, in add
    widget = self._add()
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 926, in _add
    form.populate_obj(item)
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/wtforms/form.py", line 96, in populate_obj
    field.populate_obj(obj, name)
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/wtforms/fields/core.py", line 330, in populate_obj
    setattr(obj, name, self.data)
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 261, in __set__
    instance_state(instance), instance_dict(instance), value, None
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 808, in set
    state, dict_, value, old, initiator
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 816, in fire_replace_event
    state, value, previous, initiator or self._replace_token
  File "/Users/cnorman/Documents/campusdb/venv/lib/python2.7/site-packages/sqlalchemy/orm/util.py", line 168, in set_
    return validator(state.obj(), key, value)
  File "/Users/cnorman/Documents/campusdb/app/models.py", line 51, in validate_email
    raise AssertionError('Email provided was not a valid email')
AssertionError: Email provided was not a valid email
```

### Steps to reproduce

Provide an invalid email.

**Comment by dpgaspar** [comment]
Hi @CameronNemo,

Why not use the WTForm field validation? You would need to override the add and edit methods on the ModelView class to catch it like that

**Comment by CameronNemo** [comment]
1. I am mostly happy with the form as is
2. I would like to use the validator for the model as it seems more direct
3. I would like to not repeat the validation in both of the model and the view

**Comment by dpgaspar** [comment]
Have you tried to override add/edit methods?

**Comment by CameronNemo** [comment]
Will give it a shot tomorrow!

**Comment by CameronNemo** [comment]
Closing this out as I have not been able to try your recommendations yet. I can just reopen if neither of your suggestions work out.
