### ISSUE TITLE
AttributeError: view_menu

### ISSUE THREAD

**Issue by raoden1** [dpgaspar/Flask-AppBuilder#930]
### Environment

Flask-Appbuilder version:

pip freeze output:
Babel==2.6.0
Click==7.0
colorama==0.4.1
defusedxml==0.5.0
Flask==1.0.2
Flask-AppBuilder==1.12.5
Flask-Babel==0.12.2
Flask-Login==0.4.1
flask-mongoengine==0.9.5
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.1
mongoengine==0.17.0
Pillow==5.4.1
PyJWT==1.7.1
pymongo==3.7.2
python-dateutil==2.8.0
python3-openid==3.1.0
pytz==2018.9
six==1.12.0
SQLAlchemy==1.3.1
Werkzeug==0.15.1
WTForms==2.2.1

### Describe the expected results
Adding action to ModelView if you forgot rename function name for example:
```
@action("rocketmam", "Call mummy",
            "Do you really want to call your mummy ?",
            "fa-rocket")
    def call_mummy(self, item):
        """
            do something with the item record
        """
        return redirect(self.get_redirect())
```
Then your application run once because of changes in files, trying to get to this view and to permision view you wil get error : `AttributeError : view_menu ` or to Settings-> Base Permission

I found in List Role is: 
![image](https://user-images.githubusercontent.com/8611369/54848916-d1824f80-4c9f-11e9-9b82-4682906b05da.png)
`
DBRef('permission_view', ObjectId('5c95378f13ec984af2f9b83b'))`

Then I edited this admin role and this record doesn't show on edit view of roles and saved again - and this info disappear form roles = Problem solved.
And everything working well.. but tooks time to find where is that bug, I have no idea why this is happend.
### EDIT
Logs: 
```
Traceback (most recent call last):
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/bson/dbref.py", line 83, in __getattr__
    return self.__kwargs[key]
KeyError: 'view_menu'

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/views.py", line 478, in list
    widgets=widgets)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/baseviews.py", line 161, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 19, in block "body"
    {% block content %}
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 13, in block "content"
    {% block list_list scoped %}
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 15, in block "list_list"
    {{ widgets.get('list')()|safe }}
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/widgets.py", line 34, in __call__
    return template.render(args)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/list_thumbnail.html", line 2, in top-level template code
    {% extends 'appbuilder/general/widgets/base_list.html' %}
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/base_list.html", line 7, in top-level template code
    {% set actions = actions | get_actions_on_list(modelview_name) %}
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/filters.py", line 29, in get_actions_on_list
    if self.is_item_visible(action.name, modelview_name) and action.multiple:
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/filters.py", line 122, in is_item_visible
    return self.security_manager.has_access(permission, item)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/security/manager.py", line 892, in has_access
    return self._has_view_access(g.user, permission_name, view_name)
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/flask_appbuilder/security/manager.py", line 883, in _has_view_access
    if (view_name == permission.view_menu.name) and (permission_name == permission.permission.name):
  File "/home/trololo/Downloads/sytemsem/core/venv/lib/python3.6/site-packages/bson/dbref.py", line 85, in __getattr__
    raise AttributeError(key)
AttributeError: view_menu
```

**Comment by dpgaspar** [comment]
Sorry, can't concentrate on the problem.

Rocketman calling mummy, do you really want to call your mummy?

Still laughing out here....

Some questions:

1 - Did he ever get's to call his mummy?
2 - Do you have logs from the call?

**Comment by raoden1** [comment]
Some answers:
1. Possible 
2. Yes, I edited my post.

**Comment by dpgaspar** [comment]
Sorry for the delay, have you found the problem yet?

**Comment by raoden1** [comment]
Not yet, problem is disappearing when you edit roles and save them again. If I'll find more time I'll look inside code.
