### ISSUE TITLE
base_template undefined issue

### ISSUE THREAD

**Issue by Ulixestoitaca** [dpgaspar/Flask-AppBuilder#937]
Hello,

I am getting this issue in case I click on administration links for example 'security --> list users'.

############################################################
Traceback (most recent call last):
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask_appbuilder\security\decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask_appbuilder\views.py", line 478, in list
    widgets=widgets)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask_appbuilder\baseviews.py", line 161, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask_appbuilder\templates\appbuilder\general\model\list.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask_appbuilder\templates\appbuilder\base.html", line 1, in top-level template code
    {% extends base_template %}
  File "C:\Users\ulixes\venv_fl_manager\linkedin\app\templates\mybase.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib with context %}
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask_appbuilder\templates\appbuilder\baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask_appbuilder\templates\appbuilder\init.html", line 46, in top-level template code
    {% block body %}
  File "C:\Users\ulixes\venv_fl_manager\linkedin\app\templates\mybase.html", line 78, in block "body"
    {% block content %}{% endblock %}
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask_appbuilder\templates\appbuilder\general\model\list.html", line 14, in block "content"
    {% block list_list scoped %}
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask_appbuilder\templates\appbuilder\general\model\list.html", line 16, in block "list_list"
    {{ widgets.get('list')()|safe }}
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask_appbuilder\widgets.py", line 34, in __call__
    return template.render(args)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask_appbuilder\templates\appbuilder\general\widgets\list.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask_appbuilder\templates\appbuilder\base.html", line 1, in top-level template code
    {% extends base_template %}
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\flask\templating.py", line 83, in _get_source_fast
    return loader.get_source(environment, template)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\jinja2\loaders.py", line 168, in get_source
    pieces = split_template_path(template)
  File "c:\users\ulixes\venv_fl_manager\lib\site-packages\jinja2\loaders.py", line 27, in split_template_path
    for piece in template.split('/'):
jinja2.exceptions.UndefinedError: 'base_template' is undefined
############################################################

Base template is defined in __init__py in this way 
appbuilder = AppBuilder(app, db.session)
and works fine for my own views except for administration panel.

Thank you for any suggestion

**Comment by dpgaspar** [comment]
Hi,

``appbuilder = AppBuilder(app, db.session)`` is not overriding the base_template. 

Take a look at:
https://flask-appbuilder.readthedocs.io/en/latest/_modules/flask_appbuilder/base.html?highlight=base_template

Can you please create a simple gist example?

**Comment by Ulixestoitaca** [comment]
https://gist.github.com/Ulixestoitaca/d659f676126c7b59cc568fa74413f0e5

is that ok?

**Comment by dpgaspar** [comment]
Sorry, create a gist of your __init__.py (where you are initializing AppBuilder)

Also take a look at the quicktemplates example, it will probably help.

**Comment by Ulixestoitaca** [comment]
This is __init__.py gist https://gist.github.com/Ulixestoitaca/87deeeb167d5ae96870eb0ef34e912cb 

Yes I have followed quicktemplates examples time ago, now I am in an advanced status with my app. I have never modified administration files, just worked on views.py and set up other files/classes which should not conflict with the rest of your app.

**Comment by dpgaspar** [comment]
Hi,

base_template arrives as undefined on base.html and that is strange since this is always passed to the templates on BaseView.render_template. You have to debug it, your ``__init__.py`` seems ok. Going to close this issue, feel free to reopen if you find something that indicates a possible FAB issue.

**Comment by Velas2** [comment]
For anyone else stumbling across this issue. I ran in to it as well.

Make sure you're passing required arguments to render_template.

Throws this error:
return render_template('List.html', items=myItems)

Corrected:
return render_template('List.html', items=myItems, base_template=appbuilder.base_template, appbuilder=appbuilder)

**Comment by EvilConsultant** [comment]
Thanks @Velas2  - I was stuck on the same issue. I am not am expert, so could be my lack of understanding, but following the quicktemplates example I was assuming that "return render_template('product.html', product=product) would work on a BaseView with my own template, but your guidance worked in my case. 

```
 class ProductView(BaseView):
    route_base = "/product"

    @expose("/id/<string:id>")
    def product_id(self, id):
        product = db.session.query(Product).filter_by(id=id).first()
        return render_template('product.html', product=product, base_template=appbuilder.base_template, appbuilder=appbuilder)
```

**Comment by taoli-ax** [comment]
> Thanks @velas2 - I was stuck on the same issue. I am not an expert, so could be my lack of understanding, but following the quicktemplates example I was assuming that "return render_template('product.html', product=product) would work on a BaseView with my own template, but your guidance worked in my case, as did calling self.render_template as noted in #1139
> 
> ```
>  class ProductView(BaseView):
>     route_base = "/product"
> 
>     @expose("/id/<string:id>")
>     def product_id(self, id):
>         product = db.session.query(Product).filter_by(id=id).first()
>         return render_template('product.html', product=product, base_template=appbuilder.base_template, appbuilder=appbuilder)
>         OR
>         return self.render_template('product.html', product=product)
> ```
> 
> I should probably take the time to understand what is happening... eh.

you should use :
`self.render_template()`
not : 
`render_template()`
that self point to flask running  instance
