### ISSUE TITLE
incompatibility with mongodb

### ISSUE THREAD

**Issue by mosynaq** [dpgaspar/Flask-AppBuilder#960]
### Environment

Flask-Appbuilder version: 2.0.0

pip freeze output:

```apispec==1.2.0
attrs==19.1.0
Babel==2.6.0
certifi==2019.3.9
chardet==3.0.4
Click==7.0
colorama==0.4.1
defusedxml==0.5.0
Flask==1.0.2
Flask-AppBuilder==2.0.0
Flask-Babel==0.12.2
Flask-JWT-Extended==3.18.1
Flask-Login==0.4.1
flask-mongoengine==0.9.5
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==3.0.1
MarkupSafe==1.1.1
marshmallow==2.19.2
marshmallow-enum==1.4.1
marshmallow-sqlalchemy==0.16.2
mongoengine==0.17.0
prison==0.1.0
PyJWT==1.7.1
pymongo==3.7.2
pyrsistent==0.14.11
python-dateutil==2.8.0
python3-openid==3.1.0
pytz==2019.1
PyYAML==5.1
requests==2.21.0
six==1.12.0
SQLAlchemy==1.3.3
urllib3==1.24.1
Werkzeug==0.15.2
WTForms==2.2.1
```

### Steps to reproduce
I followed the below steps to create an app:
```
(flask_appbuilder_venv37)$ flask fab create-app
Your new app name: my_app
Your engine type, SQLAlchemy or MongoEngine [SQLAlchemy]: MongoEngine
Downloaded the skeleton app, good coding!
(flask_appbuilder_venv37)$ cd first_app
(flask_appbuilder_venv37)$ export FLASK_APP=app
(flask_appbuilder_venv37)$ flask fab create-admin
Username [admin]:
User first name [admin]:
User last name [user]:
Email [admin@fab.org]:
Password:
Repeat for confirmation:
```
### Describe the actual results
In browser:
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
In Windows command prompt:
```flask run
 * Serving Flask app "app"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2019-04-23 14:20:18,128:INFO:flask_appbuilder.base:Registering class IndexView on menu
2019-04-23 14:20:18,129:INFO:flask_appbuilder.baseviews:Registering route / ('GET',)
2019-04-23 14:20:18,131:INFO:flask_appbuilder.base:Registering class UtilView on menu
2019-04-23 14:20:18,131:INFO:flask_appbuilder.baseviews:Registering route /back ('GET',)
2019-04-23 14:20:18,133:INFO:flask_appbuilder.base:Registering class LocaleView on menu
2019-04-23 14:20:18,133:INFO:flask_appbuilder.baseviews:Registering route /lang/<string:locale> ('GET',)
2019-04-23 14:20:18,135:INFO:flask_appbuilder.base:Registering class SecurityApi on menu
2019-04-23 14:20:18,136:INFO:flask_appbuilder.api:Registering route /api/v1/security/login ['POST']
2019-04-23 14:20:18,136:INFO:flask_appbuilder.api:Registering route /api/v1/security/refresh ['POST']
2019-04-23 14:20:18,138:INFO:flask_appbuilder.base:Registering class ResetPasswordView on menu
2019-04-23 14:20:18,138:INFO:flask_appbuilder.baseviews:Registering route /resetpassword/form ['GET']
2019-04-23 14:20:18,138:INFO:flask_appbuilder.baseviews:Registering route /resetpassword/form ['POST']
2019-04-23 14:20:18,145:INFO:flask_appbuilder.base:Registering class ResetMyPasswordView on menu
2019-04-23 14:20:18,146:INFO:flask_appbuilder.baseviews:Registering route /resetmypassword/form ['GET']
2019-04-23 14:20:18,146:INFO:flask_appbuilder.baseviews:Registering route /resetmypassword/form ['POST']
2019-04-23 14:20:18,154:INFO:flask_appbuilder.base:Registering class UserInfoEditView on menu
2019-04-23 14:20:18,154:INFO:flask_appbuilder.baseviews:Registering route /userinfoeditview/form ['GET']
2019-04-23 14:20:18,154:INFO:flask_appbuilder.baseviews:Registering route /userinfoeditview/form ['POST']
2019-04-23 14:20:18,162:INFO:flask_appbuilder.base:Registering class AuthDBView on menu
2019-04-23 14:20:18,162:INFO:flask_appbuilder.baseviews:Registering route /login/ ['GET', 'POST']
2019-04-23 14:20:18,163:INFO:flask_appbuilder.baseviews:Registering route /logout/ ('GET',)
2019-04-23 14:20:18,166:INFO:flask_appbuilder.base:Registering class UserDBModelView on menu List Users
2019-04-23 14:20:18,167:INFO:flask_appbuilder.baseviews:Registering route /users/action/<string:name>/<pk> ['GET']
2019-04-23 14:20:18,167:INFO:flask_appbuilder.baseviews:Registering route /users/action_post ['POST']
2019-04-23 14:20:18,167:INFO:flask_appbuilder.baseviews:Registering route /users/add ['GET', 'POST']
2019-04-23 14:20:18,167:INFO:flask_appbuilder.baseviews:Registering route /users/api ['GET']
2019-04-23 14:20:18,168:INFO:flask_appbuilder.baseviews:Registering route /users/api/column/add/<col_name> ['GET']
2019-04-23 14:20:18,168:INFO:flask_appbuilder.baseviews:Registering route /users/api/column/edit/<col_name> ['GET']
2019-04-23 14:20:18,168:INFO:flask_appbuilder.baseviews:Registering route /users/api/create ['POST']
2019-04-23 14:20:18,168:INFO:flask_appbuilder.baseviews:Registering route /users/api/delete/<pk> ['DELETE']
2019-04-23 14:20:18,168:INFO:flask_appbuilder.baseviews:Registering route /users/api/get/<pk> ['GET']
2019-04-23 14:20:18,169:INFO:flask_appbuilder.baseviews:Registering route /users/api/read ['GET']
2019-04-23 14:20:18,169:INFO:flask_appbuilder.baseviews:Registering route /users/api/readvalues ['GET']
2019-04-23 14:20:18,169:INFO:flask_appbuilder.baseviews:Registering route /users/api/update/<pk> ['PUT']
2019-04-23 14:20:18,169:INFO:flask_appbuilder.baseviews:Registering route /users/delete/<pk> ('GET',)
2019-04-23 14:20:18,169:INFO:flask_appbuilder.baseviews:Registering route /users/download/<string:filename> ('GET',)
2019-04-23 14:20:18,169:INFO:flask_appbuilder.baseviews:Registering route /users/edit/<pk> ['GET', 'POST']
2019-04-23 14:20:18,170:INFO:flask_appbuilder.baseviews:Registering route /users/list/ ('GET',)
2019-04-23 14:20:18,170:INFO:flask_appbuilder.baseviews:Registering route /users/show/<pk> ['GET']
2019-04-23 14:20:18,170:INFO:flask_appbuilder.baseviews:Registering route /users/userinfo/ ('GET',)
2019-04-23 14:20:18,193:INFO:flask_appbuilder.base:Registering class RoleModelView on menu List Roles
2019-04-23 14:20:18,193:INFO:flask_appbuilder.baseviews:Registering route /roles/action/<string:name>/<pk> ['GET']
2019-04-23 14:20:18,194:INFO:flask_appbuilder.baseviews:Registering route /roles/action_post ['POST']
2019-04-23 14:20:18,194:INFO:flask_appbuilder.baseviews:Registering route /roles/add ['GET', 'POST']
2019-04-23 14:20:18,194:INFO:flask_appbuilder.baseviews:Registering route /roles/api ['GET']
2019-04-23 14:20:18,194:INFO:flask_appbuilder.baseviews:Registering route /roles/api/column/add/<col_name> ['GET']
2019-04-23 14:20:18,195:INFO:flask_appbuilder.baseviews:Registering route /roles/api/column/edit/<col_name> ['GET']
2019-04-23 14:20:18,195:INFO:flask_appbuilder.baseviews:Registering route /roles/api/create ['POST']
2019-04-23 14:20:18,195:INFO:flask_appbuilder.baseviews:Registering route /roles/api/delete/<pk> ['DELETE']
2019-04-23 14:20:18,195:INFO:flask_appbuilder.baseviews:Registering route /roles/api/get/<pk> ['GET']
2019-04-23 14:20:18,195:INFO:flask_appbuilder.baseviews:Registering route /roles/api/read ['GET']
2019-04-23 14:20:18,196:INFO:flask_appbuilder.baseviews:Registering route /roles/api/readvalues ['GET']
2019-04-23 14:20:18,196:INFO:flask_appbuilder.baseviews:Registering route /roles/api/update/<pk> ['PUT']
2019-04-23 14:20:18,196:INFO:flask_appbuilder.baseviews:Registering route /roles/delete/<pk> ('GET',)
2019-04-23 14:20:18,196:INFO:flask_appbuilder.baseviews:Registering route /roles/download/<string:filename> ('GET',)
2019-04-23 14:20:18,196:INFO:flask_appbuilder.baseviews:Registering route /roles/edit/<pk> ['GET', 'POST']
2019-04-23 14:20:18,196:INFO:flask_appbuilder.baseviews:Registering route /roles/list/ ('GET',)
2019-04-23 14:20:18,197:INFO:flask_appbuilder.baseviews:Registering route /roles/show/<pk> ['GET']
2019-04-23 14:20:18,219:INFO:flask_appbuilder.base:Registering class UserStatsChartView on menu User's Statistics
2019-04-23 14:20:18,219:INFO:flask_appbuilder.baseviews:Registering route /userstatschartview/chart/ ('GET',)
2019-04-23 14:20:18,219:INFO:flask_appbuilder.baseviews:Registering route /userstatschartview/chart/<group_by> ('GET',)
2019-04-23 14:20:18,234:INFO:flask_appbuilder.base:Registering class PermissionModelView on menu Base Permissions
2019-04-23 14:20:18,235:INFO:flask_appbuilder.baseviews:Registering route /permissions/action/<string:name>/<pk> ['GET']
2019-04-23 14:20:18,235:INFO:flask_appbuilder.baseviews:Registering route /permissions/action_post ['POST']
2019-04-23 14:20:18,236:INFO:flask_appbuilder.baseviews:Registering route /permissions/add ['GET', 'POST']
2019-04-23 14:20:18,236:INFO:flask_appbuilder.baseviews:Registering route /permissions/api ['GET']
2019-04-23 14:20:18,236:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/column/add/<col_name> ['GET']
2019-04-23 14:20:18,236:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/column/edit/<col_name> ['GET']
2019-04-23 14:20:18,236:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/create ['POST']
2019-04-23 14:20:18,236:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/delete/<pk> ['DELETE']
2019-04-23 14:20:18,237:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/get/<pk> ['GET']
2019-04-23 14:20:18,237:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/read ['GET']
2019-04-23 14:20:18,237:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/readvalues ['GET']
2019-04-23 14:20:18,238:INFO:flask_appbuilder.baseviews:Registering route /permissions/api/update/<pk> ['PUT']
2019-04-23 14:20:18,238:INFO:flask_appbuilder.baseviews:Registering route /permissions/delete/<pk> ('GET',)
2019-04-23 14:20:18,238:INFO:flask_appbuilder.baseviews:Registering route /permissions/download/<string:filename> ('GET',)
2019-04-23 14:20:18,238:INFO:flask_appbuilder.baseviews:Registering route /permissions/edit/<pk> ['GET', 'POST']
2019-04-23 14:20:18,238:INFO:flask_appbuilder.baseviews:Registering route /permissions/list/ ('GET',)
2019-04-23 14:20:18,238:INFO:flask_appbuilder.baseviews:Registering route /permissions/show/<pk> ['GET']
2019-04-23 14:20:18,256:INFO:flask_appbuilder.base:Registering class ViewMenuModelView on menu Views/Menus
2019-04-23 14:20:18,256:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/action/<string:name>/<pk> ['GET']
2019-04-23 14:20:18,256:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/action_post ['POST']
2019-04-23 14:20:18,257:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/add ['GET', 'POST']
2019-04-23 14:20:18,258:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api ['GET']
2019-04-23 14:20:18,258:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/column/add/<col_name> ['GET']
2019-04-23 14:20:18,258:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/column/edit/<col_name> ['GET']
2019-04-23 14:20:18,258:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/create ['POST']
2019-04-23 14:20:18,258:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/delete/<pk> ['DELETE']
2019-04-23 14:20:18,259:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/get/<pk> ['GET']
2019-04-23 14:20:18,260:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/read ['GET']
2019-04-23 14:20:18,260:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/readvalues ['GET']
2019-04-23 14:20:18,260:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/api/update/<pk> ['PUT']
2019-04-23 14:20:18,260:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/delete/<pk> ('GET',)
2019-04-23 14:20:18,260:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/download/<string:filename> ('GET',)
2019-04-23 14:20:18,261:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/edit/<pk> ['GET', 'POST']
2019-04-23 14:20:18,261:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/list/ ('GET',)
2019-04-23 14:20:18,261:INFO:flask_appbuilder.baseviews:Registering route /viewmenus/show/<pk> ['GET']
2019-04-23 14:20:18,278:INFO:flask_appbuilder.base:Registering class PermissionViewModelView on menu Permission on Views/Menus
2019-04-23 14:20:18,279:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/action/<string:name>/<pk> ['GET']
2019-04-23 14:20:18,279:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/action_post ['POST']
2019-04-23 14:20:18,280:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/add ['GET', 'POST']
2019-04-23 14:20:18,280:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api ['GET']
2019-04-23 14:20:18,280:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/column/add/<col_name> ['GET']
2019-04-23 14:20:18,281:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/column/edit/<col_name> ['GET']
2019-04-23 14:20:18,281:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/create ['POST']
2019-04-23 14:20:18,281:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/delete/<pk> ['DELETE']
2019-04-23 14:20:18,281:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/get/<pk> ['GET']
2019-04-23 14:20:18,281:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/read ['GET']
2019-04-23 14:20:18,282:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/readvalues ['GET']
2019-04-23 14:20:18,282:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/api/update/<pk> ['PUT']
2019-04-23 14:20:18,282:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/delete/<pk> ('GET',)
2019-04-23 14:20:18,282:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/download/<string:filename> ('GET',)
2019-04-23 14:20:18,282:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/edit/<pk> ['GET', 'POST']
2019-04-23 14:20:18,282:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/list/ ('GET',)
2019-04-23 14:20:18,283:INFO:flask_appbuilder.baseviews:Registering route /permissionviews/show/<pk> ['GET']
2019-04-23 14:20:18,299:INFO:flask_appbuilder.base:Registering class OpenApi on menu
2019-04-23 14:20:18,300:INFO:flask_appbuilder.api:Registering route /api/<version>/_openapi ('GET',)
2019-04-23 14:20:18,590:INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-04-23 14:20:21,433:ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\base\fields.py", line 474, in to_mongo
    return ObjectId(six.text_type(value))
  File "d:\flask_appbuilder_venv37\lib\site-packages\bson\objectid.py", line 125, in __init__
    self.__validate(oid)
  File "d:\flask_appbuilder_venv37\lib\site-packages\bson\objectid.py", line 221, in __validate
    _raise_invalid_id(oid)
  File "d:\flask_appbuilder_venv37\lib\site-packages\bson\objectid.py", line 67, in _raise_invalid_id
    " or a 24-character hex string" % oid)
bson.errors.InvalidId: '1' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask_appbuilder\views.py", line 39, in index
    return self.render_template(self.index_template, appbuilder=self.appbuilder)
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask_appbuilder\baseviews.py", line 183, in render_template
    template, **dict(list(kwargs.items()) + list(self.extra_args.items()))
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\templating.py", line 133, in render_template
    ctx.app.update_template_context(context)
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\app.py", line 792, in update_template_context
    context.update(func())
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask_login\utils.py", line 368, in _user_context_processor
    return dict(current_user=_get_user())
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask_login\utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask_login\login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask_login\login_manager.py", line 321, in reload_user
    user = self.user_callback(user_id)
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask_appbuilder\security\mongoengine\manager.py", line 151, in load_user
    return self.get_user_by_id(pk)
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask_appbuilder\security\mongoengine\manager.py", line 148, in get_user_by_id

    return self.user_model.objects(pk=pk).first()
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\queryset\base.py", line 295, in first
    result = queryset[0]
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\queryset\base.py", line 195, in __getitem__
    queryset._cursor[key],
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\queryset\base.py", line 1578, in _cursor
    self._cursor_obj = self._collection.find(self._query,
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\queryset\base.py", line 1624, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\queryset\visitor.py", line 89, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\queryset\visitor.py", line 162, in accept
    return visitor.visit_query(self)
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\queryset\visitor.py", line 78, in visit_query
    return transform.query(self.document, **query.query)
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\queryset\transform.py", line 99, in query
    value = field.prepare_query_value(op, value)
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\base\fields.py", line 481, in prepare_query_value
    return self.to_mongo(value)
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\base\fields.py", line 477, in to_mongo
    self.error(six.text_type(e))
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\base\fields.py", line 166, in error
    raise ValidationError(message, errors=errors, field_name=field_name)
mongoengine.errors.ValidationError: '1' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
2019-04-23 14:20:21,784:INFO:werkzeug:127.0.0.1 - - [23/Apr/2019 14:20:21] "GET / HTTP/1.1" 500 -
2019-04-23 14:20:22,462:ERROR:flask.app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "d:\flask_appbuilder_venv37\lib\site-packages\werkzeug\routing.py", line 1960, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\base\fields.py", line 474, in to_mongo
    return ObjectId(six.text_type(value))
  File "d:\flask_appbuilder_venv37\lib\site-packages\bson\objectid.py", line 125, in __init__
    self.__validate(oid)
  File "d:\flask_appbuilder_venv37\lib\site-packages\bson\objectid.py", line 221, in __validate
    _raise_invalid_id(oid)
  File "d:\flask_appbuilder_venv37\lib\site-packages\bson\objectid.py", line 67, in _raise_invalid_id
    " or a 24-character hex string" % oid)
bson.errors.InvalidId: '1' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\app.py", line 1644, in handle_http_exception
    return handler(e)
  File "D:\my_app\app\views.py", line 16, in page_not_found
    return render_template('404.html', base_template=appbuilder.base_template, appbuilder=appbuilder), 404
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\templating.py", line 133, in render_template
    ctx.app.update_template_context(context)
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask\app.py", line 792, in update_template_context
    context.update(func())
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask_login\utils.py", line 368, in _user_context_processor
    return dict(current_user=_get_user())
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask_login\utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask_login\login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask_login\login_manager.py", line 321, in reload_user
    user = self.user_callback(user_id)
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask_appbuilder\security\mongoengine\manager.py", line 151, in load_user
    return self.get_user_by_id(pk)
  File "d:\flask_appbuilder_venv37\lib\site-packages\flask_appbuilder\security\mongoengine\manager.py", line 148, in get_user_by_id

    return self.user_model.objects(pk=pk).first()
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\queryset\base.py", line 295, in first
    result = queryset[0]
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\queryset\base.py", line 195, in __getitem__
    queryset._cursor[key],
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\queryset\base.py", line 1578, in _cursor
    self._cursor_obj = self._collection.find(self._query,
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\queryset\base.py", line 1624, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\queryset\visitor.py", line 89, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\queryset\visitor.py", line 162, in accept
    return visitor.visit_query(self)
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\queryset\visitor.py", line 78, in visit_query
    return transform.query(self.document, **query.query)
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\queryset\transform.py", line 99, in query
    value = field.prepare_query_value(op, value)
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\base\fields.py", line 481, in prepare_query_value
    return self.to_mongo(value)
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\base\fields.py", line 477, in to_mongo
    self.error(six.text_type(e))
  File "d:\flask_appbuilder_venv37\lib\site-packages\mongoengine\base\fields.py", line 166, in error
    raise ValidationError(message, errors=errors, field_name=field_name)
mongoengine.errors.ValidationError: '1' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
2019-04-23 14:20:22,556:INFO:werkzeug:127.0.0.1 - - [23/Apr/2019 14:20:22] "GET /favicon.ico HTTP/1.1" 500 -
```
As the error log says, there is a problem with mongodb.

**Comment by dpgaspar** [comment]
Hi @mosynaq,

Tested your example and found no problems. I would guess that:
```
mongoengine.errors.ValidationError: '1' is not a valid ObjectId, 
```

Seems like your accessing a new MongoEngine app with an SQLAlchemy cookie, clear you cookie and try again.

**Comment by mosynaq** [comment]
Thank you @dpgaspar ! It worked!
